### ISSUE TITLE
[テストケース案] Pow of Formal Power Series

### ISSUE THREAD

**Issue by MtSaka** [yosupo06/library-checker-problems#1002]
[ABC303 Ex](https://atcoder.jp/contests/abc303/tasks/abc303_h)にてLibrary CheckerでACが出ている自分のライブラリのFormal Power Seriesのpowを使った際に、以下のテストケースでRuntime Errorが出ました。
```
2 1
1
```
原因は未だわかっていませんが、この問題に
```
1 2
1
```
のようなケースを追加すると良いと思いました。
以下が提出です。
Pow of Formal Power Series AC: [https://judge.yosupo.jp/submission/96509](https://judge.yosupo.jp/submission/96509)
ABC303 Ex RE: [https://atcoder.jp/contests/abc303/submissions/41775315](https://atcoder.jp/contests/abc303/submissions/41775315)

**Comment by NachiaVivias** [comment]
興味で原因特定したので報告します。

```c++
// LC の提出のほう
432    FPS integral()const{
433      const int n=(*this).size();          // log 取ったあとなので n = 0 で来る
434      vector<mint>inv(n+1);
435      inv[1]=mint(1);                      //  out of range
```

（この提出とは関係ないようですが）他の単項式が与えられる場合も確認するべきだと思います。

**Comment by MtSaka** [comment]
ご指摘ありがとうございます。
少しためしてみたところ、他の単項式でもおそらく同様の原因でRuntime Errorが出ているようです。
このような場合のために単項式のテストケースの追加をすると良い感じでしょうか。

**Comment by NachiaVivias** [comment]
後で気づいたのですが、他にも配列外参照がある（ 451 行目）ようで、あくまで配列外参照なので落ちない場合がある、ということのようです。

私の気持ちとしては

- 具体的に落ちるケースを見つけたのならそのものを追加してほしい
- それ以外では M=0,1,2 など変えつつ生成したケースを追加しておきたい

というのがあります。

**Comment by maspypy** [comment]
```
1 2
1
```
を含む形で単項式をいくつか作ればいいかな

**Comment by maspypy** [comment]
↑誤操作です

**Comment by maspypy** [comment]
```
1 2
1
```
を含む形でいくつか単項式をつくります。

**Comment by maspypy** [comment]
と思ったら単項式ケース自体は存在しているなあ。

> 後で気づいたのですが、他にも配列外参照がある（ 451 行目）ようで、あくまで配列外参照なので落ちない場合がある、ということのようです。

ということは、既に適切なテストケースは存在しているということですか？だとすると追加する意味があまりないですが。
（作業しようと思ったけど一旦放置します）

**Comment by NachiaVivias** [comment]
今ある単項式は、定数項以外であって掛ける回数 $M$ が大きく、場合分けではじかれるので RE の原因にはなりえません。
そうでない（答えまで項が残る）ものは見当たらなかったので、追加する意味はあると思います。
