### ISSUE TITLE
[問題案] Consecutive Terms of Linear Recurrent Sequence

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#1007]
# 問題内容

https://judge.yosupo.jp/problem/kth_term_of_linearly_recurrent_sequence

と同じ。

compute $a_{c+i}$ for $i=0,1,...,M-1$

# 資料
https://qiita.com/ryuhe1/items/c18ddbb834eed724a42b
https://noshi91.hatenablog.com/entry/2023/06/04/233447

**Comment by maspypy** [comment]
https://judge.yosupo.jp/problem/shift_of_sampling_points_of_polynomial
に合わせて、N 個与えられて M 個答える形式にするのも自然か。

**Comment by maspypy** [comment]
作業者募集で。

**Comment by suisen-cp** [comment]
これ準備します

制約は $`d,k,c,a`$ は https://judge.yosupo.jp/problem/kth_term_of_linearly_recurrent_sequence と同じ、$`M`$ は https://judge.yosupo.jp/problem/inv_of_formal_power_series と合わせて $`M\leq 5\times 10 ^ 5`$ にしようと思います。

ただこの制約だとやや大きすぎる可能性もあって、C++ 実装の Fiduccia で 4.6 sec 程度掛かりました。Bostan-Mori で middle product や fft 再利用の工夫を加えて 1.3 sec 程度です (私の実装が悪いだけという可能性もありますが...)。

テストケースについては https://judge.yosupo.jp/problem/kth_term_of_linearly_recurrent_sequence の流用 + $`c`$ の末尾に $`0`$ が続くケースを入れようと思います。
