### ISSUE TITLE
Discord link doesn't work

### ISSUE THREAD

**Issue by adamant-pwn** [yosupo06/library-checker-problems#1013]
README.md has a [link](https://discordapp.com/channels/1087310259447681114/1087410091730423889/1087411950218129509) to Discord, but joining it is impossible. Is it intended?

![image](https://github.com/yosupo06/library-checker-problems/assets/14077831/1fb92a13-910c-4666-bd78-1cfd975dac07)

**Comment by maspypy** [comment]
discord invite link: https://discord.gg/DfJvTe5tzD
