### ISSUE TITLE
Add test cases to multiple problems

### ISSUE THREAD

**Issue by ToxicPie** [yosupo06/library-checker-problems#1016]
My submissions https://judge.yosupo.jp/submission/151477 and https://judge.yosupo.jp/submission/151482 use the following common trick to save mod operations:
```cpp
uint64_t sum = 0;
for (int i = 0; i < n; i++) {
    sum += (uint64_t)a[i] * b[i];
    if (i % 32 == 31) {
        sum = sum % MOD;
    }
}
``` 
But the above version is incorrect because 32 * 998244352^2 would overflow. However, it got AC on Convolution (Large).

A test that breaks it is
```
19 19
998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352
998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352 998244352
```
or any longer sequence of very large numbers.

I suggest that such test cases be added to every problem that requires similar operations (Convolution problems, Matrix Product, etc.) to catch the overflow bug.

**Comment by maspypy** [comment]
close
https://github.com/yosupo06/library-checker-problems/pull/1018
