### ISSUE TITLE
[問題案] 上限付き単調増加列の数え上げ

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#1019]
## 問題概要
非負整数 $A_0, \ldots, A_{N-1}$, $B_0, \ldots, B_{N-1}$ が与えられる．非負整数列 $(x_i)$ で次を満たすものを mod 998244353 で数えよ．

- $0\leq x_0 \leq \cdots \leq x_{N-1} < M$
- $A_i\leq x_i < B_i$

## 制約
$N,M\leq 2^{17}$

## 資料
https://noshi91.hatenablog.com/entry/2023/07/21/235339

**Comment by maspypy** [comment]
英語タイトル案
Number of Increasing Sequences Between Two Sequences

**Comment by maspypy** [comment]
作業者募集

**Comment by Mitsubachi-coder** [comment]
Mitsubachi と申します。作業をお手伝いできるなら、お手伝いしたいです。

**Comment by maspypy** [comment]
@Mitsubachi-coder 
ありがとうございます！
競技プログラミングのレベルがどのくらいの方なのか分からないですが、この問題案の内容や解法は理解していますか？

**Comment by Mitsubachi-coder** [comment]
AtC 黄色程度のレベルで、この問題の解法は理解しています。下限なし(A_i=0)のものに関しては既にコードを書いております。

**Comment by maspypy** [comment]
ありがとうございます。では、是非お願いします。

簡単な説明は
https://github.com/yosupo06/library-checker-problems/blob/master/docs/guideline.md
にあります。あとは他の問題のディレクトリを参考に、やってみてください。

不明点があれば、ここで聞いていただいてもよいですし、LC の discord や私の twitter などの方が楽でしたらそちらで聞いていただいても大丈夫です。

よろしくお願いします。

**Comment by Mitsubachi-coder** [comment]
ありがとうございます。何か疑問があればお伺いします。

**Comment by Mitsubachi-coder** [comment]
問題文について、
0 <= A_0 <= ... <= A_{N-1} <= M ( B についても同様)
と各種条件式の < を <= にするとすると資料と同じような条件で、かつそもそも存在しないかの判定がなくなり良さそうですが、どうでしょうか？

**Comment by maspypy** [comment]
$A_i\leq x_i\leq B_i$ を満たす $(x_i)$ を数えよ。

制約：
- $0\leq A_0\leq \cdots \leq A_{N-1} \leq M$
- $0\leq B_0\leq \cdots \leq B_{N-1} \leq M$
- $A_i \leq B_i$

ということですか？

**Comment by Mitsubachi-coder** [comment]
そうですね。

**Comment by maspypy** [comment]
うーんどうしようかな。
Library Checker は、割と自明なコーナーケース処理の面倒も見てくれている問題が多いので、解が明らかに 0 であるという場合もあってよい（たくさんは要らない）と思っているのですが、結構面倒ですか？

**Comment by Mitsubachi-coder** [comment]
自明でかつ処理が楽なので、おっしゃる通りいらないかもしれませんね。

**Comment by maspypy** [comment]
$A_i\leq B_i$ くらい入れておくのは問題設定の自然さという意味でも良いかもしれません。
区間クエリ問題で $L\leq R$ が制約に入っているくらいの意味で。

**Comment by Mitsubachi-coder** [comment]
そうですね、 $A_i \leq B_i$ は入れてもいいかもしれません。
$0 \leq x_i \leq M$ があるなら $0 \leq A_i \leq B_i \leq M$ の制約を入れても不自然ではないと思いますが、どうでしょうか？(その制約がなくても、処理は区間の共通部分取るだけで簡単なのでさほど問題はないと思います。)

**Comment by maspypy** [comment]
すいません、それはあってよいと思っていました。区間は $[a,b)$ のことが多いので

- 広義単調増加数列 $(x_i)$ で $A_i\leq x_i < B_i$ を満たすものを数えよ
- 制約：$0\leq A_i\leq B_i\leq M$
- $A$, $B$ の単調性は仮定しない

くらいでどうでしょうか？

**Comment by Mitsubachi-coder** [comment]
そうですね、私もその制約でいいと思います。

github についての質問もしたいのですが、 [https://yoshitaku-jp.hatenablog.com/entry/2018/07/07/225642](https://yoshitaku-jp.hatenablog.com/entry/2018/07/07/225642) に沿って [https://github.com/Mitsubachi-coder/library-checker-problems/pull/1](https://github.com/Mitsubachi-coder/library-checker-problems/pull/1) のようにフォルダとファイルを追加するコミットをしたつもりなのですが、全体のところには追加されていないようです。どこが間違っていますでしょうか？

**Comment by maspypy** [comment]
今回の場合、無のところにフォルダ、ファイルを作るよりも、
https://github.com/yosupo06/library-checker-problems
全体を Fork （コピーみたいなもの）してきてそこにフォルダ、ファイルを作っていくのが簡単だと思います。
![image](https://github.com/yosupo06/library-checker-problems/assets/45988013/31592776-8653-4904-8f79-bf0cfd76c886)

（私もかなり github 知らない人なので、もう少しできる人に見てくれるよう頼んでいます。）

**Comment by Mitsubachi-coder** [comment]
ありがとうございます。 Fork してやってみます。

問題文を書いてみました。英語で書くのは未経験なので、何か改善点があれば教えてくださると助かります。

英語版 
Given integers $N,M$ and two non-negative integer sequences $A = \left( A_0, A_1, \cdots, A_{N-1} \right), B = \left( B_0, B_1, \cdots, B_{N-1} \right)$ .

Find the number of a non-negative integer sequences $x = \left( x_0, x_1, \cdots, x_{N-1} \right)$ which satisfies the following conditions, and print it $\bmod \ 998244353$ .

- $0 \leq x_0 \leq \cdots \leq x_{N-1} < M$
- $A_i \leq x_i < B_i$

日本語版
整数 $N,M$ と長さ $N$ の非負整数列 $A = \left( A_0, A_1, \cdots, A_{N-1} \right), B = \left( B_0, B_1, \cdots, B_{N-1} \right)$ が与えられます。非負整数列 $x = \left( x_0, x_1, \cdots, x_{N-1} \right)$ で以下の条件を満たすものの個数を $\bmod \ 998244353$ で求めてください。

- $0 \leq x_0 \leq \cdots \leq x_{N-1} < M$
- $A_i \leq x_i < B_i$

**Comment by maspypy** [comment]
問題文はよいと思います。

**Comment by maspypy** [comment]
@Mitsubachi-coder 
これどのくらい作りましたか？困っているところはありますか？

**Comment by Mitsubachi-coder** [comment]
申し訳ありません。完全に失念しておりました。作業を進めます。

**Comment by Mitsubachi-coder** [comment]
gen/random.cpp などを作ろうと作業しています。
https://github.com/yosupo06/library-checker-problems/blob/master/sample/aplusb/gen/random.cpp
によると ../params.h というものが include されているのですが、これはなんでしょうか？手元ではエラーが出ます。

**Comment by maspypy** [comment]
info.toml に書いた定数を、問題文、生成器、verifier などに使える仕組みになっています。
生成器については、自動で生成される param.h を include する形でこれを実現しています。

> 手元ではエラーが出ます。
何をすると何というエラーが出たのか具体的に書いて欲しいです。library-checker-problems 直下で、
python generate.py sample/aplusb/info.toml --dev
は実行できますか？

**Comment by Mitsubachi-coder** [comment]
実行できました。 coloring パッケージを入れ忘れていました。ありがとうございます。

**Comment by Mitsubachi-coder** [comment]
hash.json の作成方法を教えていただいてもよろしいでしょうか。

**Comment by maspypy** [comment]
python generate.py sample/aplusb/info.toml --dev
問題名を作っているものに変更してこれを実行すると、エラーなく実行終了すれば hash.json が作られると思います

**Comment by Mitsubachi-coder** [comment]
実行し、生成に成功しました。ありがとうございます。

**Comment by Mitsubachi-coder** [comment]
https://github.com/yosupo06/library-checker-problems/pull/1185
一旦プルリクエストを作成してみました。 blocked などがあるのですが、どうすれば良いでしょうか。
