### ISSUE TITLE
`&` を含むMathJaxの表示が壊れている

### ISSUE THREAD

**Issue by kzrnm** [yosupo06/library-checker-problems#1027]
`$c_k = \sum_{i, j, i & j = k} a_i b_j$` や `$i & j$` が表示できてないようです。

https://judge.yosupo.jp/problem/bitwise_and_convolution
[math/bitwise_and_convolution/task.md](https://github.com/yosupo06/library-checker-problems/blob/master/math/bitwise_and_convolution/task.md)

**Comment by yosupo06** [comment]
ありがとうございます、どうやら`\\&`にする必要がありそうです

**Comment by NachiaVivias** [comment]
`\And` が好みです。バックスラッシュの個数を調整するのは環境に敏感で、今回のように面倒です。

`\And` は Statement Viewer で動作しました。また KaTeX の Supported Functions にも載っています。 https://katex.org/docs/supported.html#binary-operators

**Comment by yosupo06** [comment]
ありがとうございます　そちらの方が良さそうです
