### ISSUE TITLE
Min Plus Convolutionの日本語問題文でtypo発見

### ISSUE THREAD

**Issue by ebi-fly13** [yosupo06/library-checker-problems#1039]
Min Plus Convolutionの日本語問題文で $c_k = \min_{i + j = k} a_i b_j$ となっていますが、 $c_k = \min_{i + j = k} (a_i + b_j)$ だと思います。

https://judge.yosupo.jp/problem/min_plus_convolution_convex_convex
https://judge.yosupo.jp/problem/min_plus_convolution_convex_arbitrary

**Comment by maspypy** [comment]
ありがとうございます。
（表示バグみたいなやつかと思ったらめちゃくちゃ普通に間違ってるｗ）
