### ISSUE TITLE
[Problem proposal] Many Factorials

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#1058]
Problem name: Many Factorials
(Optional) Problem ID: many_factorials

https://github.com/yosupo06/library-checker-problems/issues/128 の制約強化

## Problem

$`Q`$ 個の非負整数 $`N _ 1, N _ 2, \ldots, N _ Q`$ が与えられるので、それぞれに対して $`N _ i! \bmod 998244353`$ を求めよ。/ Given $`Q`$ non-negative integers $`N _ 1, N _ 2, \ldots, N _ Q`$. Print $`N _ i! \bmod 998244353`$ for each $`i = 1,2,\ldots,Q`$.

##  Constraint

- $`1\leq Q\leq 10 ^ 5`$
- $`0\leq N _ i \lt 998244353`$

## Solution / Reference

- https://nyaannyaan.github.io/library/modulo/factorial.hpp.html
  - precalculates $`(i\cdot \lfloor\sqrt{P}\rfloor)! \bmod 998244353`$ for all $`i = 0, 1, \ldots, \lfloor P/\lfloor\sqrt{P}\rfloor\rfloor`$ in $`O(\sqrt{P} \log P)`$ time
- https://yukicoder.me/problems/no/2166, https://www.mathenachia.blog/yukicoder-2166-usereditorial/
  - evaluates $`\displaystyle A(x,i) = \prod _ {i = 1} ^ j (x + i)`$ for $`O(Q+\sqrt{P})`$ pairs $`(x, j)\ (0\leq j\lt \lfloor\sqrt{P}\rfloor)`$ in $`O( (Q+\sqrt{P})\cdot (\log(Q + \sqrt{P})) ^ 2)`$ time

## Note / Disucussion

- 上記の制約で想定解 (C++) を手元で計測したところ $`0.5`$ sec 程度でした
- $`(i\cdot \lfloor\sqrt{P}\rfloor)! \bmod 998244343`$ を前計算してクエリ毎に $`O(\sqrt{P})`$ 時間だけ掛ける解法は、ランダムケースで $`5`$ sec, 最悪ケースで $`10`$ sec 程度でした (近い方の値から計算すると最悪でも $`5`$ sec 程度？)
- 既存問題の制約強化に当たる問題をどのように扱うかについてよく分かっていません。issue を立てるのが不適当であればすみません。

**Comment by maspypy** [comment]
ありがとうございます。確かに普通にできますね。良いと思います。
要求しているアルゴリズムが違うので、既存問題との重複も問題ないかと思います。

**Comment by suisen-cp** [comment]
ありがとうございます

想定解は持っているので、準備します。 テストケースとしては以下のものを入れる予定です。

- Factorialの流用
- 下位k bit(12≦k≦16)が1でk+1 bit目が0のもの
     = ブロックサイズ2冪の前計算の最悪ケース (shift of sampling points of polynomialによるダブリングの自然な実装を想定)

**Comment by suisen-cp** [comment]
前計算に時間を掛けてブロックサイズを例えば $`2 ^ 9`$ などにすると想定解以外の解法が全てかなり高速化されることに気づきました。

ということで実装してみるとクエリ毎に高々 $`2 ^ 8`$ 回掛け算するのが一番速かったです。

特殊な分割統治ライブラリの verify という面で意味はありそうですが、速度的には面白くない感じになるかもしれません。

**Comment by suisen-cp** [comment]
Forumから辿ってくる方へ:

https://suisen-kyopro.hatenablog.com/entry/2023/11/22/201600 の方にある程度解法をまとめたので、良ければ参考にしてください。
