### ISSUE TITLE
[問題案] Counting Spanning Trees (Undirected / Directed)

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#1082]
[問題]
（無向）
$N$ 頂点 $M$ 辺の無向グラフが与えられる．全域木を数える．使う辺番号が違うなら違うとする．
mod 998244353．

（有向）
$N$ 頂点 $M$ 辺の有向グラフが与えられる．根 $r$ も与えられる． $r$ を根とする有向全域木を数える．使う辺番号が違うなら違うとする．
mod 998244353．

[制約]
$N\leq 500$

[解法]
行列木定理

**Comment by NachiaVivias** [comment]
とりあえずは sparse 仕様ではないほうが良いと思います。 （需要が多そうな、全要素持つものの verify が不便になって辛そうなので）
