### ISSUE TITLE
latex render seems broken in problem "Polynomial Root Finding (Mod 998244353)"

### ISSUE THREAD

**Issue by Misuki743** [yosupo06/library-checker-problems#1094]
<img width="1115" alt="截圖 2024-01-22 上午12 32 34" src="https://github.com/yosupo06/library-checker-problems/assets/92742051/b67e4218-ed23-4d99-b3d4-dbfca1604e98">

just found out this is broken, also in Japanese version.

**Comment by maspypy** [comment]
Thank you for reporting it! It is fixed now.
