### ISSUE TITLE
[問題案] Counting Square-free numbers

### ISSUE THREAD

**Issue by tko919** [yosupo06/library-checker-problems#1102]
問題名:Counting Square-free numbers

## 問題文

$N$ 以下の無平方数の個数を数えてください。

##  制約

- $1 \leq N \leq 10^{18}$

## 解法

https://smsxgz.github.io/post/pe/counting_square_free_numbers/

## メモ

- 制約は要調整

**Comment by maspypy** [comment]
$2/5$ 乗で解けるという話がありますね、 $10^{18}$ 制約でも行けると思います。
https://arxiv.org/pdf/1107.4890.pdf

**Comment by maspypy** [comment]
あ、参考リンク先に書いてありました、すいません。
