### ISSUE TITLE
CIが人からのプルリクに対して走らない

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#111]
何かの設定忘れだろう #110

**Comment by yosupo06** [comment]
多分治った

**Comment by kmyk** [comment]
これって何が原因でしたか？

**Comment by yosupo06** [comment]
<img width="826" alt="スクリーンショット 2019-10-02 16 28 04" src="https://user-images.githubusercontent.com/7629145/66025526-aa031e00-e531-11e9-9ce7-79346bfa6347.png">
これがOffになってました

**Comment by kmyk** [comment]
なるほど、ありがとう。
