### ISSUE TITLE
[テストケース案] Counting Primes

### ISSUE THREAD

**Issue by lpha-z** [yosupo06/library-checker-problems#1111]
# 概要

よくコピペされている提出に誤りが含まれているため、これを落とすケースを追加したいです。

# 詳細

[現在最速の提出](https://judge.yosupo.jp/submission/107115)は多くの提出にコピペされていますが、未初期化配列（180行目：`bool skip[v+1];`）を触っている部分（186行目等）があり、未定義動作を起こしています。
しかし、以下の二点により、現在のテストケースではACとなってしまうようです。

* 入力が十分大きい場合、偶然にも0埋めされた領域に`skip[v+1]`が確保されるため、偶然正しく動作する
    * 他の大きな配列確保があるため、スタックがかなり伸長される。一般に伸長されたスタック部分は0埋めされていることが多い
* 入力が十分小さい場合（29未満が入力された場合）はこの部分には到達しないため、正しく動作する

この関数を二回呼び出すとおかしな挙動を示すなど、実用上も問題があると思われます。

# 対策

微妙な大きさの入力により、一連の解答を落とすことができます。

gcc13.1を使った実験では、`57`を入力するとセグメンテーションフォルトで落ちる、`101`を入力すると`4`が返ってくる（WA）、`199`を入力すると`0`が返ってくる（WA）、との結果を得ました。
これら三つをテストケースに追加すればよいと思いますが、コンパイラのバージョンが変わると落とせなくなる可能性があります。

なお、現在のテストケースには微妙な大きさの入力である`100`が含まれますが、これはよくわからない偶然により正しい答えを返すようです。

# 相談

(1) このような（特定のアルゴリズムではなく）特定のソースコードの解答を落とすようなテストケースを追加するのは気が引けるところですが、間違った実装が広まるのもよくないと思うので、追加を提案したいです。

(2) 200以下のすべての数をテストする、などの網羅的なテストにすることも考えられます。コンパイラのバージョンが変わっても落とせそうだという点では安心ですが、ジャッジサーバーの負荷等が心配です。特定ケースの追加と網羅的なテストのどちらがよいでしょうか。

(3) 嘘解答に上記提出をコピーして含めようかと思っていますが、ライセンス的にまずいなどありましたらご指摘ください。

問題なさそうであれば、私が実装してプルリクエストを出そうと思っています。

**Comment by maspypy** [comment]
> (1) このような（特定のアルゴリズムではなく）特定のソースコードの解答を落とすようなテストケースを追加するのは気が引けるところですが、間違った実装が広まるのもよくないと思うので、追加を提案したいです。

特定のソースコードに対するテストケースもありがたいので、追加でよさそうです。

> (2) 200以下のすべての数をテストする、などの網羅的なテストにすることも考えられます。コンパイラのバージョンが変わっても落とせそうだという点では安心ですが、ジャッジサーバーの負荷等が心配です。特定ケースの追加と網羅的なテストのどちらがよいでしょうか。

今までの運用だと、落ちると分かっているものを数個足しておくということかな。

> (3) 嘘解答に上記提出をコピーして含めようかと思っていますが、ライセンス的にまずいなどありましたらご指摘ください。

これは確か、やらないようにしていた気がします。ただ、バージョンが変わっても落としたい解答が落ちることが確認できている方が良いというのもわかるので、どうしましょうか。（ @yosupo06 ）

**Comment by yosupo06** [comment]
件の提出は特にライセンスが明記されていないので、そのままコピーすると無断転載になるという認識です。この程度の長さのソースコードに著作権が認められるのかという話を聞いたことがありますが、あまり詳しくないです…

**Comment by lpha-z** [comment]
Terms and conditions に "As a condition of submission, User grants the organizer a license to use, reproduce, adapt, modify, publish, distribute, publicly perform, create a derivative work from, and publicly display the Submission." と書かれているので、organizerに対してはライセンスしているとの認識です。私がorganizerに含まれるのかはわからないです。

**Comment by maspypy** [comment]
@yosupo06 
結論どうしますか？ok なら ok でいいし、ダメならダメでそのように準備しましょうということでもいいと思いますが。

**Comment by lpha-z** [comment]
わかりました、ではソースコードの追加はなしということで進めさせていただきます
