### ISSUE TITLE
[問題案] Point Set Tree Path Rooted Composite Sum

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#1136]
Problem name: Point Set Rooted Tree Path Composite Sum

## 問題案

- $N$ 頂点の木、
- $N$ 個の整数 $a _ 0 , a _ 1 , \ldots , a _ {N-1}$ 、
- $N-1$ 個の整数 $b _ 0 , b _ 1 , \ldots , b _ {N-2}$ 、
- $N-1$ 個の整数 $c _ 0 , c _ 1 , \ldots , c _ {N-2}$

が与えられます。辺 $i$ は頂点 $u _ i$ と頂点 $v _ i$ を双方向に結びます。

$0\leq e \leq N-2$ を満たす整数 $e$ について、 $f _ e (x) = b _ e x + c _ e$ とします。

頂点 $0$ から頂点 $v$ までの単純パスに含まれる辺を順に $e _ 0,e _ 1, \ldots , e _ k$ として、 $P(v) = f _ {e _ 0}(f _ {e _ 1}(\ldots f _ {e _ k}(a _ v) \ldots ))$ とします。

クエリが $Q$ 個与えられるので順に処理してください。各クエリは次の $2$ 種類のいずれかです。

- `0 i x` : $a_i$ を $x$ に更新して、その後 $\sum_v P(v)$ を出力する。
- `1 e x y` : $(b_e, c_e)$ を $(x, y)$ に更新して、その後 $\sum_v P(v)$ を出力する。

## 制約

- $1 \leq N \leq 2 \times 10^5$
- $1 \leq Q \leq 2 \times 10^5$
- $0 \leq A_i \lt 998244353$
- $0 \leq B_i \lt 998244353$
- $0 \leq C_i \lt 998244353$

## 想定解

Static top tree / HLD + Segment tree

## Note

題名, 問題設定は Tree Path Composite Sum に合わせました。
将来的に全方位木 ver を追加する可能性を考慮して題名に Rooted を入れました。

**Comment by NyaanNyaan** [comment]
ありがとうございます。題名はそのようにしようと思います。
特に問題なさそうなので準備を始めようと思います

**Comment by yosupo06** [comment]
制約にQがないように見えます

**Comment by NyaanNyaan** [comment]
うっかりしていました、修正します
