### ISSUE TITLE
テストケース Range Chmin Chmax Add Range Sum

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#1138]
https://discord.com/channels/1087310259447681114/1098609236965085256/1234075520153555025
beats がバグっているが Library Checker で AC する？？という話があったらしい？？
足すべきケースが何か調べていません。落ちるべき提出がどれかも知りません。

@hitonanode 何か知ってたら教えてください

**Comment by hitonanode** [comment]
https://github.com/hitonanode/cplib-cpp/issues/331 ですが、モノイドに作用がはたらく際、モノイドのもともとの最小値が作用の chmin の値に一致している場合の処理がバグっています。

今回のバグだと、例えば [Range Chmin Chmax Add Range Sum - Library Checker](https://judge.yosupo.jp/problem/range_chmin_chmax_add_range_sum) の [私の提出](https://judge.yosupo.jp/submission/108208) は
```txt
5 2
0 0 3 1 0
0 1 4 1
3 0 4
```
で落ちます（想定は 2、私の提出は 1）。

逆バージョンとして、モノイドのもともとの最大値が作用の chmax に一致している場合にバグっているコードは
```txt
5 2
0 0 1 0 1
1 1 5 1
3 0 5
```
で落とせます。

等号の場合の処理がバグの原因なので、 $A$ の値域が狭いケースがあると容易に落とせそうです。例えば以下の要領でランダムケースを作ると普通に落とせていそうです。

<details>

```python
import random

random.seed(0)

N = 1000
Q = 1000

MINA = -3
MAXA = 3

A = [random.randint(MINA, MAXA) for _ in range(N)]

print(N, Q)
print(*A, sep=' ')

for _ in range(Q):
    tp = random.randint(0, 3)
    l, r = 0, 0

    while l >= r:
        l = random.randint(0, N)
        r = random.randint(0, N)

    if tp <= 2:
        b = random.randint(MINA, MAXA)
        print(tp, l, r, b)
    else:
        print(tp, l, r)
```

</details>

**Comment by hitonanode** [comment]
とりあえず上記の方針でテストケース追加 PR 出しましょうか？ （どなたがやる形でもよいです）

**Comment by maspypy** [comment]
ありがとうございます、作業までしていただけるならば、もちろんそうしていただけた方がありがたいです。
