### ISSUE TITLE
[問題案] Rectangle Sum(rectangle_sum)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#118]

**Comment by yosupo06** [comment]
2次元平面上に重み付きの点がN個ある。クエリがQ個くる

- l, r, d, u : l <= x < r, d <= y < uの点の重みの総和を求める

クエリ先読み / wavelet matrix

**Comment by yosupo06** [comment]
問題ID意見募集(point_add_range_sumに合わせた)

**Comment by yosupo06** [comment]
rectangle_sumでええか

**Comment by yosupo06** [comment]
点列に合わせ、x0, y0, x1, y1の順に

**Comment by maspypy** [comment]
問題名：「Static Point Add Rectangle Sum」 とするのはどうでしょうか？

https://github.com/yosupo06/library-checker-problems/issues/771

との整合性です、探すときに少し見つけにくく感じたので。
