### ISSUE TITLE
generate.py の `|` による Union の是非

### ISSUE THREAD

**Issue by kzrnm** [yosupo06/library-checker-problems#1181]
`|` による Union [PEP604](https://peps.python.org/pep-0604/) は Python 3.10 以降の機能なので Python 3.9 とかで動かすとエラーしてしまいます。

https://github.com/yosupo06/library-checker-problems/blob/da3aaf98eb97a1ac2fea250c0a80970cc58fdaf4/generate.py#L33

typing.Union を使ったほうが良いのではないでしょうか。

https://github.com/yosupo06/library-checker-problems/blob/6c1c6d7d74ac80f40409718156c635da1e3e75d0/generate.py#L35

あるいは対応バージョンを Python 3.10+ としてしまうのもアリかもしれません。

https://github.com/yosupo06/library-checker-problems/blob/da3aaf98eb97a1ac2fea250c0a80970cc58fdaf4/README.md?plain=1#L13

**Comment by yosupo06** [comment]
ありがとうございます　https://devguide.python.org/versions/ これを眺めたところpython3.10ぐらいは要求していい気分になりました　ubuntu22.04の標準がpython3.10なので困る人はそういないだろうと思っています
