### ISSUE TITLE
testcase for RMQ: add test where there exists a subarray with multiple minimums

### ISSUE THREAD

**Issue by lrvideckis** [yosupo06/library-checker-problems#1195]
https://judge.yosupo.jp/submission/218286

this should RTE

**Comment by lrvideckis** [comment]
but really I just wanted to test my monotonic stack code https://judge.yosupo.jp/submission/218285

**Comment by lrvideckis** [comment]
yes, thank you!

**Comment by maspypy** [comment]
It's been added, and the solution is now RE. Thank you!
