### ISSUE TITLE
[テストケース] Closest/Furthest Pair of Points のケース near_grid が意図通りでないと思われる

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#1204]

**Comment by NachiaVivias** [comment]
`near_grid` の入力データは点の座標が `-500000000 -500000000` 付近に偏っています。

https://github.com/yosupo06/library-checker-problems/blob/e2952b19f02692818c4de94568a0c8295aeddac7/geo/closest_pair/gen/near_grid.cpp#L34-L41

`int d = LIM / (N - 1);` というのが `int d = LIM / (n - 1);` の間違いだと思います。変更すると、 x,y それぞれおよそ `-500000000` ～ `500000000` の範囲でグリッド状に点が配置されます。

**Comment by maspypy** [comment]
ありがとうございます、私のほうでなおします（なおした cpp を追加します）
