### ISSUE TITLE
[Problem proposal] Minimum Diameter Spanning Tree

### ISSUE THREAD

**Issue by robinyqc** [yosupo06/library-checker-problems#1208]
Problem name: Minimum Diameter Spanning Tree
Problem ID: minimum_diameter_spanning_tree

## Problem

Given a simple connected undirected graph with $n$ vertices and $m$ edges, find the spanning tree with minimum diameter.

##  Constraint

Depends on the way to calculate all-pairs shortest path.

## Solution / Reference

+ [OI-Wiki (in Chinese)](https://oi-wiki.org/graph/mdst/)
+ https://codeforces.com/blog/entry/7372
+ [CF 266D](https://codeforces.com/problemset/problem/266/D)
+ [SPOJ MDST](https://www.spoj.com/problems/MDST/)

## Note / Disucussion

+ Weighted graph or unweighted graph? For unweighted graph there exists $O(\frac{n^3}w)$.
+ Dense graph or sparse graph?

**Comment by maspypy** [comment]
Japanese Reference
https://www.slideshare.net/slideshow/ss-17402143/17402143
