### ISSUE TITLE
[テストケース] Suffix Array

### ISSUE THREAD

**Issue by NokonoKotlin** [yosupo06/library-checker-problems#1211]
<a href = "https://judge.yosupo.jp/submission/221284">嘘解法の提出(提出 221284)</a>

Ukkonen アルゴリズムによる Suffix Tree の構築で Suffix Link の構築をサボっても通ってしまいます。詳細な説明はできませんが、以下のケースで TLE すると思います。Suffix Link の構築をサボっている部分は提出コードの 278 行目のコメントアウトの部分です。

[hack_sft.txt](https://github.com/user-attachments/files/16243678/hack_sft.txt) (追記 : 制約違反があったので修正しました)

**Comment by NokonoKotlin** [comment]
添付したケースの最後の文字が制約違反でした ( 現在は `!` になっています)。お手数をおかけしますが、適当な文字で置換しておいてください。

**Comment by NokonoKotlin** [comment]
想定アルゴリズムと異なるので微妙な話かもしれませんが、Z-algorithm などの他の部分文字列系の問題にも Suffix Tree を使えるので、それらにも対応が必要かもしれません。

**Comment by maspypy** [comment]
ありがとうございます。
・これをそのまま足す
・ついでに、単一文字から10か所程度ランダム変更したものを足してもいいかな。
----
参考
S.size() = 499981
i = 7122 S[i] = s
i = 249980 S[i] = g
i = 374980 S[i] = s
i = 437480 S[i] = w
i = 468730 S[i] = o
i = 484355 S[i] = q
i = 492167 S[i] = v
i = 496073 S[i] = k
i = 498026 S[i] = h
i = 499003 S[i] = p
i = 499491 S[i] = d
i = 499735 S[i] = z
i = 499857 S[i] = g
i = 499918 S[i] = a
i = 499949 S[i] = l
i = 499964 S[i] = z
i = 499972 S[i] = z
i = 499980 S[i] = p

**Comment by maspypy** [comment]
追加されました、ありがとうございます
