### ISSUE TITLE
[テストケース] Eulerian Trail

### ISSUE THREAD

**Issue by physics0523** [yosupo06/library-checker-problems#1212]
有向、無向ともに $O(N^2)$ かかる(DFSする際に毎回辺のリストを全部舐めてしまう)実装が落ちていません。
以下のようなケースで落ちます
```
2 200000
0 1
1 0
0 0
0 0
...
0 0
```
```
100000 200000
0 1
1 0
0 2
2 0
...
0 99999
99999 0
```
落ちるべき実装の例:
https://judge.yosupo.jp/submission/222002

**Comment by maspypy** [comment]
ありがとうございます、追加しました
