### ISSUE TITLE
[問題案] Number of Substrings(number_of_substrings)

### ISSUE THREAD

**Issue by sigma425** [yosupo06/library-checker-problems#123]
# 問題概要
文字列 S が与えられる。S の相異なる部分文字列の数を求めよ
- 問題ID: {number_of_substrings}
- 問題名: {Number of Substrings}

## 入力

```
S
```

## 出力

```
ans
```

## 制約
|S| <= 500,000

**Comment by yosupo06** [comment]
良さそうです

**Comment by yosupo06** [comment]
#3 Suffix Automaton
