### ISSUE TITLE
[テストケース] Counting Square-free Integers

### ISSUE THREAD

**Issue by ecottea** [yosupo06/library-checker-problems#1232]
n 以下の平方数の個数を求める際に (int)sqrt(n) としている AC コード（[#232556](https://judge.yosupo.jp/submission/232556)）に対し，N=138757285551932082 での Hack に成功しました．
当該提出：https://judge.yosupo.jp/hack/13

上記の N は，(int)sqrt(n) != (int)sqrtl(n) を満たす n をランダムに試すことで見つけました．
この条件を満たしても Hack に失敗する n も存在したので，複数個追加すべきかもしれません．

**Comment by maspypy** [comment]
ありがとうございます、追加しました
