### ISSUE TITLE
Checkers' bug in polynomial problems

### ISSUE THREAD

**Issue by awerty-noob** [yosupo06/library-checker-problems#1239]
It's obvious that the answer $a_i \in \mathbb{Z}_{MOD}$, but I noticed that the checker doesn't check this condition, like `sqrt_of_formal_power_series`:
https://github.com/yosupo06/library-checker-problems/blob/0b83c9629b924b404b06b591106489b214c42ae0/polynomial/sqrt_of_formal_power_series/checker.cpp#L141-L143

This is an emission, right?

**Comment by NachiaVivias** [comment]
Thank you for your report. Will fix it soon.
