### ISSUE TITLE
[Problem proposal] Fermat's theorem on sums of two squares

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#1241]
Problem name: Fermat's theorem on sums of two squares

## Problem

Tケース与えられる。

非負整数Nが与えられるので、$x^2 + y^2 = N$なる非負整数x, yが存在するか判定し、するなら一つ構成

##  Constraint

- $T <= 100$
- $N <= 10^{18}$

## Solution / Reference

- https://en.wikipedia.org/wiki/Fermat%27s_theorem_on_sums_of_two_squares
- https://manabitimes.jp/math/844

定理のstatementに従うととりあえず存在判定 / Nが4k+1型の素数の場合への帰着 が可能。

Nが4k + 1型の素数の時にどうやって構築するかであるが、実は高校数学の美しい物語の方の「フェルマーの二平方和定理の証明」に書いてある方法に従うと O(log N)になっているはず。X^2 + Y^2 = kNなる(X, Y)からX'^2 + Y'^2 = k'N (k' <= k/2)なる(X', Y')を構成している。

計算量のボトルネックはケースごとのfactorize

## (Optional) Input

```
T
N
N
:
```

## (Optional) Output

```
X Y
```

存在しない場合`-1 -1`を出力

## (Optional) Note / Disucussion

- CTFで見た (https://alpacahack.com/challenges/easy-factoring) が競プロのフォーマットに乗りそうなので提案　競プロで出題されたことがあるかは不明
- ボトルネックが非本質のfactorize、Nを10^9以下にしてケースを増やす？
- Noの場合の出力って`-1 -1`と`-1`のどっち

**Comment by maspypy** [comment]
持ってるので割とすぐ作れます。全部出力でも行けるかな。
p=1 mod 4 で p^k で割れるときの $\prod(k+1)$ の定数倍が個数みたいになるけど、雑に $k=1$ だけで見積もると 1000 個的なオーダー。（$0\leq x\leq y$ 出力とかにすると 出力を 1/8 倍にできるとかも）

**Comment by maspypy** [comment]
three square sum, four square sum （これは 1 つ出力）もついでにやっちゃおうか

**Comment by maspypy** [comment]
自分の解法
four square : 3 つでできないとする。4 で割っていって 8k+7 とする。x_1ならひとつ x_1=1 でできる。
three square, https://math.stackexchange.com/questions/483101/rabin-and-shallit-algorithm https://maspypy.github.io/library/nt/three_square.hpp

n が十分大きいとする。n=x^2+p, n=x^2+2p という作り方をする。（p=1 mod 4, 素数）
x をランダムにとったときに n-x^2 がそういう数になる確率は素数の密度を考えると十分高いと考えられるのでできている。

問題点：十分大きい n すべてがこの方法でできるかどうかは証明がないので想定解が壊れる可能性がある

**Comment by maspypy** [comment]
two square : done

three, four : これもやろうかなと言い出したものの問題点をどうするか考えるのが面倒なので、言い出さなかったことにします。欲しい人は改めて提案してもらうということで。
