### ISSUE TITLE
[Problem proposal] orderedset operations

### ISSUE THREAD

**Issue by toriitakuto** [yosupo06/library-checker-problems#1243]
Problem name: ???

整数の順序付き集合での操作を verify できればいいなと思いました．似たものとして Predecessor Problem がすでにありますが，それのより汎用的なものをイメージしています．

## Problem
非負整数の集合 $S$ に対して，以下の処理を行う．

- 値 $x$ の追加・削除
- 値 $x$ の存在判定
- $S$ の要素のうち $x$ 番目に小さいものを出力
- $S$ の要素のうち $x$ 以下のものの個数を出力
- $S$ の要素のうち $x$ 以上/以下のもので最小/最大のものを出力

## Constraint
- $Q\leq 1e6$
## Note / Disucussion
- $S$ は最初空にするかどうか
- 要素の上限は 1e9?1e18?

**Comment by maspypy** [comment]
ありがとうございます、これ
https://github.com/yosupo06/library-checker-problems/issues/659
とまとめていい感じにしたいな

区間和とかまで聞いちゃうと要求が高すぎますか？

**Comment by toriitakuto** [comment]
区間和が使いたい状況は上で書いた操作と比べると頻度がかなり少ないと思うので，個人的にはいらないと思います

**Comment by maspypy** [comment]
659 とかなり同じかと思ったけど、確かに 659 よりだいぶ低機能ですね。
Predecessor Problem と比べると、要素数がとりたいということですか。

**Comment by maspypy** [comment]
ちょうどそれを verify できる感じの問題は存在しない気がするので、何らか置いて良さそうです。
制約は特に大きくする理由がないので 10^9 で考えています。（10^7 の方が verify できるものが増える可能性はあってどうしよう）

**Comment by kemuniku** [comment]
日本語問題文のクエリ2にある「|S| < kならば」という文は「|S| < xならば」が正しいと思います。(英語問題文では|S| < xとなっています)

**Comment by maspypy** [comment]
ありがとうございます、なおします
