### ISSUE TITLE
[テストケース案] (Counting Primes)

### ISSUE THREAD

**Issue by Mitsubachi-coder** [yosupo06/library-checker-problems#1244]
Lucy DP を基にした [#235301](https://judge.yosupo.jp/submission/235301) が [Hack #33](https://judge.yosupo.jp/hack/33) や [Hack #34](https://judge.yosupo.jp/hack/34) で落ちる($N = 15, 35$ counting_primes_vector(n) のところ)

原因は $\frac{N}{i}$ の商を大小別に管理しているが，サイズの取り方や大小の指定を間違えると $\lfloor \sqrt{N} \rfloor$ から $\lfloor \frac{N}{\lfloor \sqrt{N} \rfloor} \rfloor$ の間が指定された時に壊れたりするため

おそらく $N = a^2 - 1$ みたいな形の $N$ を入れておくと良さそう？

**Comment by maspypy** [comment]
ありがとうございます、追加しました
