### ISSUE TITLE
[問題案] Vertex Add Path Sum (vertex_add_path_sum)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#125]
# 問題概要

木が与えられる。

- 0 p x: a_p += x
- 1 u v: u, v間のパス(両端含む)のaのsum

## 入力

```
N Q
a_0 a_1 ... a_{N - 1}
u_0 v_0
u_1 v_1
:
u_{N - 2} v_{N - 2}
Query0
Query1
:
Query_{Q - 1}
```

## 出力

```
```

## 制約

- 1 <= N <= 200,000

**Comment by yosupo06** [comment]
辺と数列swapした方がいいな

**Comment by yosupo06** [comment]
うっかりmasterにpushしたけど

**Comment by yosupo06** [comment]
ジェネレーターが配列外アクセスしてる

**Comment by ryuhei-mori** [comment]
問題文で N,Q ≤ 200,000 となっていますが、実際には 500,000 がテストケースにおける N と Q の最大値のようです。

**Comment by yosupo06** [comment]
わ、本当ですね　ありがとうございます
