### ISSUE TITLE
[問題案] Min Plus Convolution (Concave and Arbitrary)

### ISSUE THREAD

**Issue by ecottea** [yosupo06/library-checker-problems#1252]
## 問題概要

[Min Plus Convolution (Convex and Arbitrary)](https://judge.yosupo.jp/problem/min_plus_convolution_convex_arbitrary) と同じで，a の条件のみ凸から凹に変更

## 解法

(Monotone Minima or SMAWK Algorithm) + 分割統治

基本的に https://noshi91.github.io/Library/algorithm/concave_max_plus_convolution.cpp と同じ方法を用いる．
a が凹であるため無効値の配置が悪いが，無効値を含まない矩形に分割してそれぞれで行最小値を求めれば良い．

-----

https://noshi91.hatenablog.com/entry/2020/10/27/175112 に O(n α(n)) で可能との記述があるのですが，具体的な方法は把握できておりません．

テストケースは Min Plus Convolution (Convex and Arbitrary) のものを流用し，全ての値 x を
 10^9 - x に置き換えて作れば速いかと思っています．

**Comment by maspypy** [comment]
すいません、見ていませんでした。確かにあった方がいいですね。
見栄え的には concave-concave も入れてしまってもいいかも。
生成方法もありがとうございます。すぐ準備できると思います。

自分も n log n しかわからないな、資料ありますか？（ @noshi91 ）

**Comment by ecottea** [comment]
Monotone Minima + 分割統治の O(n (log n)^2) を想定解とするので問題なければ作業に取り掛かろうと思うのですがそれで良いでしょうか？
（git や github の扱いに不慣れなため少々時間がかかってしまうかもしれません……）

**Comment by maspypy** [comment]
それはぜひお願いします。不明点はなんでも聞いてください。（ここでも twitter でも、discord でも連絡がつきます）
