### ISSUE TITLE
[テストケース案] Find Linear Recurrence

### ISSUE THREAD

**Issue by hly1204** [yosupo06/library-checker-problems#1253]
[Hack #100](https://judge.yosupo.jp/hack/100).

It seems that [Submission #196170](https://judge.yosupo.jp/submission/196170) and [Submission #186538](https://judge.yosupo.jp/submission/186538) use the wrong method to adjust the result (actually I don't understand their solution).

**Comment by maspypy** [comment]
Thank you! I haven't looked into the solution, but I confirmed that the output of the source code you provided results in WA, so I'll add that.
