### ISSUE TITLE
零多項式の取り扱い

### ISSUE THREAD

**Issue by hidesato-fujii** [yosupo06/library-checker-problems#1261]
[Polynomial Composite Set Power Series](https://judge.yosupo.jp/problem/polynomial_composite_set_power_series) 

多項式の入力として空列が与えられますが、他の問題群では $(0)$ で与えている/出力しているようなのでそのように統一して 1<=M としてはどうでしょうか。制約を強くする方向の変更なので大きな問題は起こらないと思います。

ジャッジの思想として「零多項式の係数列の配列である空列aに対して、一般にa[0]にアクセスしたり、i<=a.size()-1をして死ぬことへの対策に入れている」というのも合理性はあると思いますが、このあたりの思想/ガイドラインはどこかに書かれていますか

**Comment by maspypy** [comment]
$n-0,l=r$ 等のコーナーケースを入れるかということについては admin 複数で話し合われたことがありますが、コーナーケースを入れたいという考えが主流でしたし、少なくとも入れてよいということになっています。（オンラインジャッジでは珍しいですが、 Library verify という用途が想定されているからこそです。）
一般公開された場所に書かれてはいないと思いますし、明確なルールというほどにはなっていないです。

統一性もある程度は重視されていると思いますが、準備時期も準備者も多岐にわたることとから難しいところもありますし、統一のために過去問を $n=0$ を入れる側に変更していくということは行われませんでした。

統一以外の利点は何かありますか？

**Comment by hidesato-fujii** [comment]
> 統一以外の利点は何かありますか？

特にありません。そういう思想/事情でそうなっているというのであればそれで問題ないと思います
