### ISSUE TITLE
[テストケース] Line Add Get Min

### ISSUE THREAD

**Issue by toriitakuto** [yosupo06/library-checker-problems#1265]
https://judge.yosupo.jp/hack/124

出力クエリがないと壊れたので，そのようなケースがあってもよいと思いました．（落ちる原因：見るべき x の集合のサイズが 2 冪ではないときに適当に値を追加して 2 冪になるようにするが，空のときに壊れる）

~~Line Add Get Min~~ Segment Add Get Min では出力クエリがないとき RE で落ちることを確認しています．

**Comment by toriitakuto** [comment]
コメントの内容を間違えていました（Segment Add Get Min のテストケースは現状のもので問題ないです）

**Comment by maspypy** [comment]
ありがとうございます、追加されました
