### ISSUE TITLE
Python 3.5 対応

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#127]
現在の generate.py は Python 3.5 では動きませんが、これが 3.5 でも動くようになってほしいです。
C++ 向けの CI 環境におまけで付いてくる Python 処理系は古いことがあり、そういう場合にうれしいためです。
たとえば、私のライブラリの CI (Travis CI) から generate.py を叩いたところ、Python 3.5 だったらしく fail しました。
https://travis-ci.org/kmyk/competitive-programming-library/jobs/593973244

ただし、Python 3.5 に対応するということは、3.6 の新機能を封印することであることに注意してください。すっきり書けていたところを消して可読性の低い汚いコードで置き換えることになるかもしれません。そこそこつらいです。

**Comment by kmyk** [comment]
対応する気があるならプルリクを書くつもりですが、出した場合にマージはされそうですか？

**Comment by yosupo06** [comment]
はい、需要があるなら3.5は対応するつもりでした　もちろん対応していただけるならありがたいです

**Comment by kmyk** [comment]
CI の再実行したら通りました。ありがとうございました。
