### ISSUE TITLE
[問題案] n! mod p

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#128]
問題ID: 募集
問題名: 募集

# 問題概要

n, pが与えられる。n! % pを求めてください

## 入力

```
N P
```

## 制約

- 1 <= N <= P <= 10^9

## 議論

- Pは素数？
- 任意mod?
- 制約は？

**Comment by yosupo06** [comment]
@koba-e964 さんがやっていただけるそう ありがたい(もしかしてコメントないとassign出来ない？)

**Comment by koba-e964** [comment]
私にアサインしてください。

**Comment by Maruoka842** [comment]
これ、忘れ去られていたらやりますが…。

**Comment by yosupo06** [comment]
@koba-e964

**Comment by koba-e964** [comment]
代わりにやっていただけると助かります 🙏

**Comment by maspypy** [comment]
これ作業に入った形跡はあるけど、制約は決まっていないですね。
合成数だと、素べきごとに解いてCRTということだと思うんですが、CRTとかは別の問題で面倒を見ることにして、素数でよいでしょうか。

素数ならば、アルゴリズムは変わらないので 998244353 固定でよいと思います。
この場合、埋め込みを使った階乗計算という別解があるので、verify できるライブラリが増えます。

**Comment by maspypy** [comment]
作業します。

**Comment by maspypy** [comment]
done https://github.com/yosupo06/library-checker-problems/pull/1051
