### ISSUE TITLE
ICE Compile error: no space left on device

### ISSUE THREAD

**Issue by wdwind** [yosupo06/library-checker-problems#1291]
https://judge.yosupo.jp/submission/252436

```
Error response from daemon: failed to create task for container: failed to start shim: mkdir /var/lib/containerd/io.containerd.runtime.v2.task/moby/09ec1afbfe4ad09b082a2c37fd280a4577845673393e018c4efad910e0883b71: no space left on device: unknown
```

Need to clean up some files or get a new instance?

**Comment by yosupo06** [comment]
Yeah it seems that the judge server's disk was running out, though I allocate 50GB. The number of problems of this judge are increasing.

**Comment by wdwind** [comment]
Retried, and it is fixed now. Thank you!
