### ISSUE TITLE
Reduce output data of convolution_mod_large

### ISSUE THREAD

**Issue by Tiphereth-A** [yosupo06/library-checker-problems#1293]
The size of total testcase of [convolution_mod_large](https://judge.yosupo.jp/problem/convolution_mod_large) reached over 10GB (5.19 GB input + 5.15 GB output) after #1285, which could exceed the [storage limitation of GitHub Action](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) in [some cases](https://github.com/competitive-verifier/competitive-verifier/issues/162). Maybe we could change the output format as

$$
s_{0}\ s_{1}\ \cdots\ s_{\lfloor((N-1)+(M-1))/K\rfloor},
$$

where

$$
s_{i}=\bigoplus_{j=iK}^{\min((N-1)+(M-1), (i+1)K-1)}c_{j}\cdot 2^{L(j\bmod K)},
$$

and $K$, $L$ are positive integrals s.t. $KL\leq 34$ since $998244352<2^{30}$. For example, we can choose $K=16$ and $L=2$, which may make total output size to 1/8 of its original size.

**Comment by EarthMessenger** [comment]
Why choose hash values ​​so weird and complicated?

**Comment by EarthMessenger** [comment]
Changes in output values ​​will cause all previous AC programs to WA.

**Comment by Tiphereth-A** [comment]
> Why choose hash values ​​so weird and complicated?

1. This hash function preserves as much information as possible about the last digit of all numbers of the result, which ensures that fft_killer works well. Maybe other hash functions work better, but I'm not sure...

2. This hash function should be efficient and easy to be parallelized.

**Comment by maspypy** [comment]
This issue is not a problem with Library Checker, so we will not address it.
For this particular issue, it might be best to forego testing with GitHub Actions and verify it through submission or local execution instead.

**Comment by Tiphereth-A** [comment]
> This issue is not a problem with Library Checker, so we will not address it.
> For this particular issue, it might be best to forego testing with GitHub Actions and verify it through submission or local execution instead.

Okay...

**Comment by yosupo06** [comment]
Sorry for the delayed response, I want to know the details of this problem a bit more because our judge also uses GitHub Actions to upload testcases.

In my understanding, we can use up to 14GB storage in Github Actions, so the total size of test cases of this problem is still under the limit ([ref](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)).

**Comment by yosupo06** [comment]
Probably we should clarify something about our testcases. As I said, at least we can implicitly promise

- The total size of the testcase of a single problem is up to 14GB (= Github Actions Limit).

**Comment by Tiphereth-A** [comment]
> In my understanding, we can use up to 14GB storage in Github Actions, so the total size of test cases of this problem is still under the limit ([ref](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)).

Thanks! It exceeds the storage limit in my repository since the validation script doesn't remove user's output which has been tested, so it actually uses >15GB (5.19 GB input + 5.15 GB answer + 5.15 GB user's output) of space. By the way, I'm not familiar with the validation scripts in this repository, would this repository run into the same problem when we test for a large number of problems in one runner?

I think there are two ways to solve this problem: keep the output format and optimize the validation script, or reduce the output data. If we keep the output format, we could add 5 more testcases of the maximum size at most, since the space required for a test case of the maximum size is about 700MB. If we  reduce the output data, we could add 20 more testcases of the maximum size at most under the output format I provided.

**Comment by yosupo06** [comment]
>  would this repository run into the same problem when we test for a large number of problems in one runner?

We generates all problem testcases in one runner but we upload and cleanup problems one by one.

I invesitaged a bit

- `convolution_mod_large`'s wrong solution is only `naive.cpp` (which throws assertion for large inputs), so actually our disk usage is less than 14GB (input + answer + small output)
- it seems to that the actual disk limit of Github Actions is *more than 14GB*, this [run](https://github.com/yosupo06/library-checker-problems/pull/1295) used 15GB (input + answer + full output) but it was succeeded.

**Comment by yosupo06** [comment]
From your [log](https://github.com/competitive-verifier/competitive-verifier/issues/162#issue-2697789244), I started to wonder `competitive_verifier` may have 2 copies of input/output internally actually ...?

- `.competitive-verifier/cache/library-checker-problems/convolution/convolution_mod_large/in`
- `..competitive-verifier/cache/problems/e8be5d7faaf48a5884ce8f6590912a22/test/example_00.in`

**Comment by yosupo06** [comment]
https://carlosbecker.com/posts/github-actions-disk-space/

I just found this article, maybe we can get more disk space

**Comment by Tiphereth-A** [comment]
> https://carlosbecker.com/posts/github-actions-disk-space/
> 
> I just found this article, maybe we can get more disk space

Thank you, it helps a lot!
