### ISSUE TITLE
[問題案] 回文木（これいる？）

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#134]
回文木（これいる？）

_Originally posted by @beet-aizu in https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-539535260_

**Comment by yosupo06** [comment]
回文木実は持ってないんで、問題案を募集します

**Comment by hos-lyric** [comment]
理想としては，木構造と suffix link をそのまま出力したいです
具体的な出力方法は議論の余地がありそうだけど，たとえば，
各位置について，
- ノードがあるかどうか (その位置を末尾とする最長回文は，今まで登場しているかどうか)
- 木構造での親ノードの番号
- suffix link の先の番号
とかは，標準的な気がします

**Comment by maspypy** [comment]
なんと先に deque 版が用意されました。さすがに普通の回文木も入れたいです。

@hos-lyric 
いま提案されているものが、木構造を出力するというものですが、この案をもうちょっと具体的に教えて欲しいです。
（問題文は何とかするとして、想定している入出力の例とかあると嬉しい）

**Comment by maspypy** [comment]
・木を出力 → 各文字がどのノードに対応するかを出力
・各文字に対して木の情報を順に出力していく
どうやると分かりやすいか

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/175 と合わせて形式を考える。

**Comment by maspypy** [comment]
問題文の下書き。palindrome tree/palindromic tree どっちが一般的かわからない

----

文字列 $S$ が与えられます．これらからなる  のノードに次のようにして番号をつけます．

- $P$ を $S$ の回文部分文字列からなる集合，$n=|P|$ とします（空文字列を含む）．
- palindromic tree とは，$P$ の要素および `ODD`, という特別な頂点からなる 2 つの木です．
- palindromic tree のノードには，次のように番号をつけてください．まず `ODD` は番号 $-1$ とします．それ以外のノードはある $S[i...j-1]$ に対応します．そのような $(i,j)$ を $j$ が最小となるようにとったとき，$j$ について昇順に $0, 1, \ldots, n-1$ の頂点番号をつけてください．特に空文字列は $i=j=0$ ととれるので，頂点番号 $0$ となります．

まず，palindromic tree の情報を次の形式で出力してください

- $n$：集合 $P$ の要素数
- $p_0,p_1,\ldots,p_{n-1}$：親のノードの番号．ただし $p_0=-1$ と定める？これ `ODD` っぽくて嫌かも
- $v_{0},\ldots,v_{n}$： $S[0..n-1]$ の max suffix palindrome に対応するノードの番号

さらに，suffix link の情報を次の形式で出力してください．

- $s_0,s_1,\ldots,s_{n-1}$：suffix link の番号

**Comment by hos-lyric** [comment]
考え直した結果，最も緩くして次の形式もありかもと思いました．
ノードに好きな順に番号を付けて以下の 3 行を出力する (同型判定を checker が行う)：
- 頂点数
- 親 ID たち
- suffix link たち

が，↑で提案されたように $v$ も出力まではありだなと思うので，それに賛成です．
詳細：
- 問題名：論文初出がたぶん eertree なので，どれを選ぶのかいい基準が存在するのかすらわからない……
- 空文字列の親や suffix link は単に出力しなくていいと思いました (連続 substring としての空文字列，特殊がちなので特殊扱いに違和感ないです)
- $v _ n$ は $v _ {|S|}$ ですよね
- 問題文上はもはや木と言わずに $P$ の元に～のように番号を付けて， $p, s$ は「先頭と末尾を削ったものはどこですか」「max proper suffix はどこですか」と書いてもいいかもと思いました
- 出力順は好みの問題ですが $p, s$ は並んでる方がなんかよさそうかもしれません (?)

**Comment by maspypy** [comment]
ありがとうございます、細かいところは準備時に調整することにして、そんな感じで準備してみてしまいます。
