### ISSUE TITLE
[問題案] Convolution (mod 1,000,000,007)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#145]
問題ID: convolution_mod_1000000007
問題名: Convolution (mod 1,000,000,007)

# 問題概要

https://judge.yosupo.jp/problem/convolution_mod と同じ、modだけ違う(1,000,000,007)

## 入力

同じ

## 制約

- N <= 2^18

**Comment by yosupo06** [comment]
- FFTで筆算みたいにやる
- NTT * 3 + Garner

前者は任意modだろうが関係ない　後者は多分関係がある？

garnerはいつか足すので、こっちはmod 1,000,000,007で作ってしまう？

**Comment by yosupo06** [comment]
mod 1,000,000,007版も作りたい気持ちになった

流石にIDがconvolution_mod_1000000007はイケてないか…？(今まで仮定していた[a-z_]+という制約に違反するのはもとより)

**Comment by SamZhangQingChuan** [comment]
Hi there. May I know how "fft killers" actually kill my fft? Many thanks.

**Comment by yosupo06** [comment]
https://github.com/yosupo06/library-checker-problems/blob/master/math/convolution_mod/gen/fft_killer.cpp

Each elements of arrays of "fft killers" are big. Especially, for each element x, (x >> 15) and (x % (1 << 15)) are big.

If you divide arrays into half(15bit-15bit) and use FFT to convolution, "fft killer" may broke your code. Though accuracy of FFT is quite good, it is severe in this constraints.

**Comment by adamant-pwn** [comment]
Is there still a way to solve this with complex-valued FFT without severe performance loss?

**Comment by adamant-pwn** [comment]
@yosupo06 I was told that changing a[i] to a[i]-mod when 2 * a[i] > mod is sufficient to bypass fft_killer with x >> 15 and x % (1 << 15). And it indeed is. Do you think this one can be hacked as well? Maybe numbers that are close to mod / 2?
