### ISSUE TITLE
[問題案] Maximum Independent Set

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#151]
(任意) 問題ID: maximum_independent_set
問題名: Maximum Independent Set

# 問題概要

単純とは限らない $N$ 頂点 $M$辺の無向グラフ
最大独立点集合を構成 & 出力

## 入力

```
N M
u_0 v_0
u_0 v_0
:
u_{M - 1} v_{M - 1}
```

## 出力

```
X
v_0 v_1 ... v_{X - 1}
```

## 制約

N <= 40
M <= 1000
- u_i != v_i

**Comment by yosupo06** [comment]
N <= 40が一番鉄板かな

**Comment by yosupo06** [comment]
自己辺(これあると問題の定義がよくわからなくなる)禁止するのに多重辺ありなのやだな　両方onかoffかにするか

**Comment by yosupo06** [comment]
https://math.stackexchange.com/questions/2202063/maximal-independent-sets-in-regular-graphs これ足すと良さそう

**Comment by Maruoka842** [comment]
頂点数120でも解けます。
https://yukicoder.me/problems/no/382

**Comment by Maruoka842** [comment]
頂点数120でも解けます（yosupo さんも通されてるので釈迦に説法ですが）。
https://yukicoder.me/problems/no/382

**Comment by yosupo06** [comment]
これはランダムケースというのに依存しているはずです

**Comment by Maruoka842** [comment]
120は言い過ぎですが（すみません）、枝狩りするときに実は指数の底が小さくなっているのでもう少し頂点数が多くても解けます。例えば https://arxiv.org/abs/1312.6260 など。

**Comment by sansen0796** [comment]
一部の提出のハックケースを投げようとファイルを編集をしていて気づいたのですが
verifier.cpp では辺数0を許すのに対し問題文は辺数1以上となっています
どちらが正しいのでしょうか

**Comment by yosupo06** [comment]
今更ながらこのジャッジ1 <= Mと0 <= Mが入り混じってるんですね…

準備の時の記憶がもうないんですが、gen/を見る限り0 <= Mがただしそうです
