### ISSUE TITLE
[問題案] Enumerate Primes(enumerate_primes)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#158]
問題ID: enumerate_primes
問題名: Enumerate Primes

# 問題概要

1 ~ Nの素数を100個おきで出力。素数リストをp_0 p_1 ...として、p_{100i + K}

## 入力

```
N K
```

## 出力

```
$X$
p_K p_{100+K} p_{200+K} ...
```

Xは出力の個数

## 制約

N <= 1e8?(速度次第)

https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-542843026

**Comment by yosupo06** [comment]
O(N log log N)なら当然持ってますが、それより上を要求したい？そもそも高速な篩とO(N log log N)でどのぐらい差がつくのかもわからない

**Comment by yosupo06** [comment]
サーバーの都合上TLは10sぐらいにしたくて、そうするとジャッジは2.5sぐらいでは動いて欲しい

**Comment by yosupo06** [comment]
素数を100個おきに出力するという案

**Comment by hos-lyric** [comment]
- 出力の 1 行目は \pi(N) がいい気がする
- K を入力で与えるなら 100 の方も与えていい気がする (あまり変わらない)

(速い篩試そうという意思はあるんですがタスクをためまくっている おゆるしを)

**Comment by yosupo06** [comment]
> (個人的には遅いライブラリが TL 内に収まってしまうのは別に構わないという思考をしていたのだけど理念的にはどうなんでしょう？)

別に構わないです　理想的にはTLEは無限にしたいが、サーバーの都合上適当にうち切っているというスタンス

**Comment by yosupo06** [comment]
> * 出力の 1 行目は \pi(N) がいい気がする

そうですね $\pi(N) X$ かな(出力サイズが入力から非自明な時はなんとなくサイズも出させている)

> * K を入力で与えるなら 100 の方も与えていい気がする (あまり変わらない)

100 <= Kって制約がなんか気持ち悪いかなって　少なくともmod Kで幾つのものを出力させるかは指定した方が良さそう

**Comment by hos-lyric** [comment]
> > * K を入力で与えるなら 100 の方も与えていい気がする (あまり変わらない)
> 
> 100 <= Kって制約がなんか気持ち悪いかなって　少なくともmod Kで幾つのものを出力させるかは指定した方が良さそう

N の上限とかに依存するだろうし変更がありうるから与えたほうがいいかなーというのがちょっとありました
どちらかというと N / M <= 10^6 みたいな制約が自然なのかもしれない．これも気持ち悪さはなくもない

**Comment by yosupo06** [comment]
> どちらかというと N / M <= 10^6 みたいな制約が自然なのかもしれない．これも気持ち悪さはなくもない

checkerが複雑になりますが、そもそも理想的には全部出力させたいが、出力が重いっていう背景を踏まえて (出力の個数) <= 10^6 が一番いい気がしてきました

**Comment by hos-lyric** [comment]
input checker に負担を押し付けて綺麗にするのはありだと思います

ところで出力速度で差をつくのがあんまりよくない気がするので 10^5 個くらいかなとか思っていたのですが (10^5 個でも差がつくかも) (高速入出力をやっていない立場の発言)，だからといって 10^1 個にするとちょっと違うしちょうどいいところというのはむずかしいですね

**Comment by yosupo06** [comment]
高速入出力の速度はそれ用の問題も置いたので、あんまり気にしないことにしようと思ってます(そもそも既に様々な問題で入出力が律速になっており…)
