### ISSUE TITLE
[問題案] 長さ N の広義単調増加列で和が M 以下のものの数

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#159]
(任意) 問題ID: {ID}
問題名: {名前}

# 問題概要

## 入力

```
```

## 出力

```
```

## 制約

長さ N の広義単調増加列で和が M 以下のものの数
https://twitter.com/maroon_kuri/status/1171708639914029057?s=20

_Originally posted by @beet-aizu in https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-540593922_

**Comment by maspypy** [comment]
狭義単調増加になるように変形すれば

https://judge.yosupo.jp/problem/sharp_p_subset_sum

の特殊ケースになるので、重複として閉じます。
