### ISSUE TITLE
[問題案] Tetration(tetration_mod)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#166]
問題ID: tetration_mod
問題名: Tetration

# 問題概要

A↑↑B mod Mを出力 Tケース

## 入力

```
T
A B M
A B M
:
A B M
```

## 制約

- T 100ぐらい？
- 0 <= A < M
- 0 <= B, M <= 10^9

https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-545479203

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/submission/1982 怪しそう

**Comment by beet-aizu** [comment]
Hack機能欲しい、欲しくない？（ところで何が怪しいのかわからないです（(double)a？

**Comment by beet-aizu** [comment]
2 2 2 で落ちた気がします　小さいケース全列挙したいのでTの制約10^4にしていいですか？
