### ISSUE TITLE
Directed MST の output 

### ISSUE THREAD

**Issue by kopricky** [yosupo06/library-checker-problems#17]
Directed MST のサンプル #2 の答えがおかしいように思います.

**Comment by yosupo06** [comment]
おかしいですね…

**Comment by hos-lyric** [comment]
とりあえず checker で `uf.merge(p, i)` してない

**Comment by hos-lyric** [comment]
ない辺を使ったらいけないというのも判定されていない

**Comment by hos-lyric** [comment]
https://github.com/yosupo06/library-checker-problems/blob/d6054bab2b42598d04d98f5289aa1fa819cb354e/graph/directedmst/sol/correct.cpp#L172
pc - 1 から逆順に見ないといけなかったりしない？ (何も理解せず物を言っています)

**Comment by yosupo06** [comment]
↑これで治った気がします、ありがとうございます！
