### ISSUE TITLE
[問題案] General Weighted Matching

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#171]
(任意) 問題ID: general_weighted_matching
問題名: Weighted Matching

# 問題概要

#77 の重み付きver

## 入力

```
N M
u v w
u v w
:
u v w
```

## 出力

```
X Y
a b
a b
:
a b
```

X = 本数
Y = 最大重み

## 制約

- N <= 300 or 500
- E <= N choose 2

想定解持ってなし

**Comment by potetisensei** [comment]
ライブラリ持ってるよ

**Comment by yosupo06** [comment]
本当ですか　ぜひ協力していただけると助かります

**Comment by potetisensei** [comment]
暇になったらいいよ（あとmin-25さんのコードはネット上にあがっています

**Comment by yosupo06** [comment]
(ブログから引っ張ってくるのはライセンスとかがやばそうなオーラを感じています)
もちろんお暇な時で大丈夫です！

**Comment by antma** [comment]
I had implementations on rust and scala languages both were rewritten from [Joris van Rantwijk python code](http://jorisvr.nl/article/maximum-matching).
As I understand rust sources can't be used as master correct solution, so I collect below C++ implementation.
In Joris's page there two links to C++ implementations.
Also [on codeforces](https://codeforces.com/blog/entry/92339?#comment-810317) it was mentioned Min25 [C++ implementation](https://gist.github.com/min-25/b984122f97dd7f72500e0bd6e49906ca).
In boost library there is another C++ [implementation](https://www.boost.org/doc/libs/1_76_0/libs/graph/doc/maximum_weighted_matching.html).
