### ISSUE TITLE
[問題案] 全方位木DP

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#172]
(任意) 問題ID: {ID}
問題名: {名前}

# 問題概要

## 入力

```
```

## 出力

```
```

**Comment by yosupo06** [comment]
各頂点について、全ての頂点への距離の和とかでいいかな

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/861
があるので、閉じておきます。
