### ISSUE TITLE
[問題案] Shortest Path

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#173]
(任意) 問題ID: shortest_path
問題名: Shortest Path

# 問題概要

N頂点M辺の(単純とは限らない)有向グラフが与えられる。頂点sからtへの最短経路を構築

## 入力

```
N M s t
u v d
u v d
:
u v d
```

## 出力

```
X
edge_id edge_id edge_id ... edge_id
```

Xは辺数。パスが存在しない場合は-1

## 制約

N <= 500,000
M <= 500,000
0 <= d <= 1e9

(完全に忘れていた…)

**Comment by windows-server-2003** [comment]
やります

**Comment by windows-server-2003** [comment]
出力は(a_i, b_i)をX行出力するではなくてよいですか ?

**Comment by yosupo06** [comment]
作ったのがなんと半年前なのでずれてますね

- グラフは単純
- 出力は(a_i, b_i)をX行

の方がいいと思います！

**Comment by windows-server-2003** [comment]
了解です
