### ISSUE TITLE
[問題案] Line Add Get Min(line_add_get_min)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#174]
(任意) 問題ID: add_line_get_min
問題名: Add Line Get Min

# 問題概要

N 本の直線 y = a_i x + b_i が存在します。 Q 個のクエリを処理してください。

- 0 a b: 直線 y = ax + b を追加
- 1 p: x = p での y 座標の最小を求める。

## 入力

```
N Q
a0 b0
a1 b1
:
a{N-1} b{N-1}
que
que
:
que
```

## 出力

```
```

## 制約

- 1 <= N, Q <= 200,000
- |値| <= 1e9 (正負は割とバグを引き起こしそうなため)
- |b| <= 1e18 (ax + bでaxは10^18までいくため)

**Comment by kmyk** [comment]
Add Segment Get Min もほしいです (Li-Chao tree)

**Comment by yosupo06** [comment]
データ構造は初期化O(N)かO(N log N)かという要素もあるため、最初にN本直線を与えることに

**Comment by yosupo06** [comment]
bが10^9なのは不自然なので、10^18

**Comment by yosupo06** [comment]
#205

**Comment by yosupo06** [comment]
forumのリンクがここになっていない
