### ISSUE TITLE
[問題案]System of Linear Equations(system_of_linear_equations)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#18]
N x M次元の行列A、長さNのベクトルbが与えられます。A x = bを満たすxを求めてください。(mod 998244353)

入力
```
N M
A
b0 b1 b2 ...
```
出力

解空間のランク(存在しない場合-1)
解のうちどれか一つ
解空間の基底ベクトル(M次元) (行ベクトルとして、縦に並べる)

制約

N, M <= 500

**Comment by yosupo06** [comment]
よく考えたらランクをMとしてM + 1行出力しないといけないだった

**Comment by hos-lyric** [comment]
線型連立方程式 / system of linear equations のほうがいいかもしれない
(単に一次方程式でもいいかもしれない)

入力や出力で行ベクトルが横に並んでるのはちょっとだけ気持ち悪いかもしれない

ほんとうは実数係数のやつも verify したいけど，verify したい点は誤差案件で，誤差はわからなさすぎてつらいですね

**Comment by yosupo06** [comment]
とりあえず作った、ケースが全くまともじゃないからマージはまだ

**Comment by SamZhangQingChuan** [comment]
in the statement, it should say "calc x" instead of "calc b"
