### ISSUE TITLE
[問題案] Vertex Set Path Composite(vertex_set_path_composite)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#190]
(任意) 問題ID: Vertex Set Path Composite
問題名: vertex_set_path_composite

# 問題概要

木が与えられる。頂点 $i$ には関数 f_i(x) = (a_i x + b_i) が置いてある。

- 0 p c d: f_p(x) = (cx + d)に変更
- 1 u v x: u, v間のパスの頂点(両端含む)の関数列f_v(...f_u(x))を求める

## 入力

```
N Q
a_0 b_0
a_1 b_1
:
a_{N-2} b_{N-2}
u_0 v_0
u_1 v_1
:
u_{N - 2} v_{N - 2}
Query0
Query1
:
Query_{Q - 1}
```

## 出力

```
```

**Comment by beet-aizu** [comment]
Dynamic Tree 版も欲しいです
