### ISSUE TITLE
二部グラフの辺彩色

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#192]
二部グラフの辺彩色

_Originally posted by @yosupo06 in https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-559974220_

**Comment by yosupo06** [comment]
> 二部グラフの辺彩色

これどうせなら平面グラフのΔ辺彩色もほしくない？（は？）
ちなみにアルゴリズム1つしか知らないし実装量は知らない（まあ花分解とかよりは軽いイメージでいる）
その上競プロで出るかと言われると......

_Originally posted by @potetisensei in https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-559974629_

**Comment by yosupo06** [comment]
平面グラフのΔ辺彩色　これも初めて知った概念だけど、多分5色定理の証明を拡張した感じだろうか　計算量は…

**Comment by potetisensei** [comment]
こんにちわ〜
えっと、次数によってダメだったりする場合があるはずで、素な平面グラフだと成り立たない場合があった気がする
https://web.eecs.umich.edu/~pettie/matching/Gabow-Nishizeki-etal-algorithms-for-edge-coloring.pdf
31ページを見てね
多分なんだけど（いや実は理解してないんだけど）、Misra & Gries algorithm + ちょっとぐらいの実装量で実現できて、そんなにやばいものではないはず？
この論文クッソ長いのは他のアルゴリズム紹介してる（O(|E|sqrt(|V|log|V|))）のやべーの）からで、31ページ周辺だけ見ればいいです

**Comment by potetisensei** [comment]
あ、あと多分理解が正しければ内部的にMisra & Gries algorithmが挟まるので最悪計算量はどうせO(|V||E|)。アルゴリズムの内容的に乱択で速くなると信じてるんですが、手元のやつ乱択出来るような実装にしてないからわからん

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/393
重複させてしまいました。
