### ISSUE TITLE
[問題案] Montmort Number (montmort_number_mod)

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#196]
(任意) 問題ID: {montmort_mod}
問題名: {Montmort}

# 問題概要
1からNまでの各Kに対して、長さKの撹乱順列の個数 mod M を順に出力

## 入力

```
$N$ $M$
```

## 出力

```
$A_1$ $A_2$ $\ldots$ $A_N$
```

## 制約
$2 \leq N \leq 10^6$
$2 \leq M \leq 10^9$

**Comment by yosupo06** [comment]
実はこの数列初見なんですが、多分 https://judge.yosupo.jp/problem/bernoulli_number に合わせて問題名/IDはMontmort numberの方が良さそうな気がします

**Comment by beet-aizu** [comment]
_mod が素数じゃなくてもいいやつ(=modが固定ではなく与えられるやつ) だと思ってました　まあどっちでもいいです

**Comment by yosupo06** [comment]
あ、numberをつけた方がよくない(Montmortは人名なので)という話でした
言われると入力でmodが与えられると_modが付きがちな気がしてきました(何も考えてませんでした) のでmontmort_number_modにしましょう

**Comment by Y-jiji** [comment]
In English version, the $i$ should be $k$ (a typo maybe)?
