### ISSUE TITLE
[問題案]Point Add Range Sum(point_add_range_sum)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#20]
長さNの数列a_iにQ個のクエリ

- 1 k x: a_k += x
- 2 l r: sum a_l ~ a_{r-1}

N, Q <= 500,000(200,000?)
0 <= a_i, x <= 1e9

想定
- fenwick tree
- segment tree

**Comment by Maruoka842** [comment]
代入の＝は一般的でなくて混乱するので、\leftarrow （$a_p=a_p+x$ の＝）の方がよいと思います。

**Comment by jpfr12** [comment]
Hi everyone.
if segment tree is a possible solution, can anyone tell me what's wrong with my implementation? it gives TLE on "max_sum" tests ;(
my code: https://judge.yosupo.jp/submission/15281
