### ISSUE TITLE
[問題案] Queue Operate All Composite (queue_operate_all_composite)

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#208]
SWAG を verify したい https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-559591931

**Comment by yosupo06** [comment]
Clarが来ました

- l,rの定義がない - 要するに今持っている関数列全体です
- fが空の時にクエリ2が何を返すべきかよくわからない - 1を返してください

**Comment by kmyk** [comment]
@yosupo06 とりあえずこの issue を再 open しておいてほしいです
