### ISSUE TITLE
[問題案]k-th root

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#21]
a,n, mが与えられる

x^n = a(mod m)を満たすxを求める

**Comment by Maruoka842** [comment]
O(p^{1/4+ε})だと下の制約で最悪ケース1secぐらいで丁度良いと思います。
pが合成数の場合の解法は考えたことないです。

### 問題概要

p_i, a_i, k_i について x^k=a_i (mod p_i) を満たすxを出力せよ。
ただし解が存在しなければ-1を出力せよ。

### 入力
Q
p_1 a_1 k_1
p_2 a_2 k_2
\vdots
p_{Q} a_{Q} k_{Q}
### 制約
Q < 5e3
p_i < 1e9
a_i < p_i

**Comment by yosupo06** [comment]
- (非本質ですが) https://judge.yosupo.jp/problem/sqrt_mod に合わせて Q -> T、a_i -> Yで、入力順はK, Y, P (かY, K, P) としたいです
- Pは素数でいいと思います
- 速度は測らないと謎ですが、そんなものな気がします

**Comment by Maruoka842** [comment]
入力順、了解です。
Kの制約を忘れていました。
1<= K < 1e9
のつもりでした。K=0を含めるかどうかはどうしましょうか。
X^K=1 mod Pの解にX=0,K=0を含めるかなど。

**Comment by yosupo06** [comment]
入れておいていいと思います -> K = 0

**Comment by Maruoka842** [comment]
worst_caseでも100msで思ったより速いですね………

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/submission/5840 出ちゃいけないものが出てます

**Comment by Maruoka842** [comment]
解説です。
https://yukicoder.me/problems/no/981/editorial
