### ISSUE TITLE
[問題案] Dynamic Tree Vertex Add Path Sum(dynamic_tree_vertex_add_path_sum)

### ISSUE THREAD

**Issue by niuez** [yosupo06/library-checker-problems#223]
問題ID: dynamic_tree_vertex_add_path_sum
問題名: Dynamic Tree Vertex Add Path Sum

# 問題概要

木が与えられる

(クエリの形は暫定)

- link `0 v u`: vとuを繋げる(vとuは同じ連結成分に含まれない)
- cut `1 v u`: 辺(v, u)を削除する
- add `2 v x`: 頂点vに重みxを加える
- sum `3 v u`: パスvu上にある頂点の重みの総和を出力

## 入力

```
N Q
a_0 a_1 ... a_{N - 1}
u_0 v_0
u_1 v_1
:
u_{N - 2} v_{N - 2}
Query0
Query1
:
Query_{Q - 1}
```

## 出力

```
```

## 動的木のクエリ

木を変化させるクエリはどうしますか?

- 森を扱う(linkクエリ, cutクエリを別々に行う)
- 木の状態を維持する(cutしたらlinkをすぐに行う)
- 頂点を加える(linkのみ, cutがverifyできない)
  - これにするとvertex_addという名前がかぶっている気がする

重みは #114 が決まり次第合わせます

**Comment by yosupo06** [comment]
> 重みは #114 が決まり次第合わせます

#114 あんまり書いてないですね…　(1点add/区間sum)はガンガン追加する方針にしています ref. #20 





> 木を変化させるクエリはどうしますか?

個人的には森を扱うのが一番わかりやすくていいと思います　準備も一番大変ですが

**Comment by yosupo06** [comment]
と思ったんですが、

> * 木の状態を維持する(cutしたらlinkをすぐに行う)

これでも

- dynamic tree感がある
- パスがない場合の出力を考えなくていい

とかのメリットがあるんですね(逆に、パスがない場合の処理をverifyしたいならデメリットかも)

**Comment by niuez** [comment]
パスがない場合というのは別の問題にするべきな気がします. Dynamic Tree系の問題で毎回パスがない場合のクエリを処理させていると, 本来verifyしたいクエリが処理できなくなって困る気がします.

Dynamic Tree Connected Two Verticesのような問題を用意したほうが良さそうです

**Comment by yosupo06** [comment]
はい　問題を分けるのに賛成です

**Comment by niuez** [comment]
作成済みのリストに入れてほしいです...

**Comment by yosupo06** [comment]
checkerを直す
