### ISSUE TITLE
[問題案] Dynamic Connectivity

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#225]
(任意) 問題ID: dynamic_connectivity
問題名: Dynamic Connectivity

# 問題概要

N頂点M辺の無向グラフが与えられる。以下のQ個クエリが飛んでくる

- `0 u v`: 無向辺(u, v)を追加
- `1 u v`:  無向辺(u, v)を削除
- `2 u v`: 頂点u, vが連結なら1、そうで無いなら0を出力

## 入力

```
N M Q
a_0 b_0
:
a_{M - 1} b_{M - 1}
Query_0
Query_1
:
Query_{Q-1}
```

## 出力

```
```

## 制約

N, M, Q <= 200,000

**Comment by yosupo06** [comment]
オンラインクエリ版もって無いのでどのぐらいの定数倍なのか不明

**Comment by maspypy** [comment]
https://judge.yosupo.jp/problem/dynamic_graph_vertex_add_component_sum

これとの重複と見なして、閉じます。こちらも欲しいという事情が出てきた場合には別に立ててください。
