### ISSUE TITLE
[問題案]漸化式のkth / berlekamp massey

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#23]
入力の順番

**Comment by hos-lyric** [comment]
計算量違うし分離した方がよさそう
(実は漸化式を陽に経由せずに最初のたくさん項から k-th が求まったりする……？)

**Comment by yosupo06** [comment]
#170 こっちにリンク飛ばしてなかった

**Comment by yosupo06** [comment]
#330 + #170 で、#170はまだだけど重複しているのでこっちをclose
