### ISSUE TITLE
[問題案] Range Affine Range Sum(range_affine_range_sum)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#233]
(任意) 問題ID: range_transform_range_sum
問題名: Range Transform Range Sum

# 問題概要

遅延伝搬の例を作っておく

1次関数、区間適用、区間sum

長さNの整数列a_0, a_1, ..., a_{N - 1}が与えられる。Q個のクエリを処理

- 0 l r c d: a_l, ..., a_r-1それぞれについて、a_i = c * a_i + bをする
- 1 l, r: a_l ~ a_r-1の総和を出力

全てmod 998244353

## 入力

```
```

## 出力

```
```

**Comment by yosupo06** [comment]
TransformはAffine Transformationからの着想、もっといいネーミングあるかも？

**Comment by kmyk** [comment]
Range Transform だと曖昧すぎる気がするので Range Affine Range Sum とか Range Linear Range Sum はどうでしょうか？ (Affine や Linear は英語として微妙そうだけど)

**Comment by yosupo06** [comment]
英語がわからないと言う話はあるんですが、動詞を今まで入れてきたので動詞がいいな　と書いたところで一応調べたらCompositeが動詞じゃないと言う事実を知りました

**Comment by yosupo06** [comment]
合成関数の合成を動詞的なアレでやるならcomposeが適切だったのかな？　じゃあもうなんでもいいんでaffineにしましょう

**Comment by yosupo06** [comment]
これ区間のサイズが遅延伝搬に必要ですね　今(想定と愚直が全然会わないので)気づきました

**Comment by yosupo06** [comment]
まあ区間のサイズが必要なタイプの遅延伝搬はあるあるなので、OKとしましょう

**Comment by Maruoka842** [comment]
代入の＝は混乱するので、\leftarrowの方がよいと思います。
