### ISSUE TITLE
problems.tomlからうっかり問題を消してしまってもCIが通る

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#237]
題の通り

検出しようと思うと結構adhocは避けられない感じになりそう
pull reqのdiffを見れば防げると言う話もあるが、どうするか

**Comment by kmyk** [comment]
いっそ `problems.toml` を消してしまうのはどうでしょうか。
`problems.toml` には問題の一覧が書かれているだけで、これは単に `info.toml` が置いてあるディレクトリを全列挙すれば済むはず。なので `problems.toml` はいらなさそう。

**Comment by yosupo06** [comment]
かなりアリな気がしてきました #239
