### ISSUE TITLE
problems.tomlを消す？

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#239]
problems.tomlを消すと言う提案( https://github.com/yosupo06/library-checker-problems/issues/237#issuecomment-569735983 )

メリットデメリットがあるため、検討

Pros:

- #237 #238 が解決する
- 問題を追加する時に、その問題に対応するディレクトリ以外を一切触らなくて良くなる

Cons:

- 問題ID -> directoryの変換が非自明
- 破壊的変更、特にonline-judge-tools(及びonline-judge-verify-helper)が壊れる
  - まずはproblems.tomlも管理するがdeprecatedにし、おいおい消すような感じにすると多分丸い

**Comment by yosupo06** [comment]
いや消すか　いらないと言う気持ちが強くなってきた

**Comment by yosupo06** [comment]
- [ ] Titleを移す
- [ ] generate.pyの仕様を決める
- [ ] ojの方の修正

**Comment by kmyk** [comment]
online-judge-tools の修正はまかせてください
