### ISSUE TITLE
[問題案] Range Chmin Chmax Add Range Sum (range_chmin_chmax_add_range_sum)

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#243]
(任意) 問題ID: {ID}
問題名: {名前}

# 問題概要

ぜんぶのせ segment tree beats です (参考: https://tjkendev.github.io/procon-library/cpp/range_query/segment_tree_beats_2.html )

長さNの整数列a_0, a_1, ..., a_{N - 1}が与えられる。Q個のクエリを処理

- `0 l r b`: a_l, ..., a_r-1それぞれについて、a_i = min(a_i, b) をする
- `1 l r b`: a_l, ..., a_r-1それぞれについて、a_i = max(a_i, b) をする
- `2 l r b`: a_l, ..., a_r-1それぞれについて、a_i = a_i + b をする
- `3 l, r`: a_l ~ a_r-1の総和を出力

## 制約

- 1≤N,Q≤500,000

## メモ

- 問題IDこれでいい？
- Range Update は Range Chmin + Range Chmax で済むので省略
- Range Min (取得) や Range Max (取得) はふつうのセグ木でもできるので省略
- Range Chmin Range Sum だけの問題もついでに作るとよい気がしています。(ところでクエリの種類を `0`, `1`, `2`, `3` でなく `chmin` `chmax` `add` `sum` とかにすればクエリが増減してもコードを使いまわせてうれしいかもしれない)

**Comment by kmyk** [comment]
> 全てmod 998244353

mod はいらないでしょ、修正

**Comment by yosupo06** [comment]
提案ありがとうございます！ 

> * 問題IDこれでいい？

はい いいと思います(Range Chmin Range Chmax Range Add Range Sumでも詠唱感(？)があって楽しいですが)


- 実は値を10^9にするとlong longに収まらないという要素があります(値をAとして QNA + o(QNA))

値を10^6にするかsumでmodを取るかのどちらかだと思います。値を10^6にするのを推します(一部だけmodが入ると違和感がある)

**Comment by yosupo06** [comment]
chmin, chmaxの値をどうするかという話があり、ムズいな

**Comment by kmyk** [comment]
add によって値が 5 * 10^11 ぐらいになるのに chmin, chmax は 10^6 までなのはおかしいという話ですか？
選択肢は以下の 3 つぐらいしかないはず。(3.) がきれいかなと思いますがどうでしょうか

1. verify の用途には十分だし気にしない
1. add クエリは b ≤ 10^4 にして chmin, chmax クエリは b ≤ 10^8 にするなど
1. 「各時点において数列の要素は常に 10^12 より小さい」みたいな制約を足すして全部 10^12 とかでやる

**Comment by yosupo06** [comment]
はい、その通りでなんとなく値の値域？次元？みたいなのが揃ってないとやだと言う感覚があります(もちろんverifyには十分ですが…)

私も3がいいと思います checkerの手間が増えますけど許容範囲でしょう(既にもっとすごい問題がありますし)

**Comment by Maruoka842** [comment]
イコールを更新の意味で使うと混乱するので（特にa_i=a_i+b）矢印などの別の記号の方が良くないでしょうか。
