### ISSUE TITLE
[問題案] 根付き木のhashを用いた同型判定

### ISSUE THREAD

**Issue by 259-Momone** [yosupo06/library-checker-problems#246]
(任意) 問題ID: rooted_tree_hash
問題名: rooted tree hash

# 問題概要

根付き木の同型判定

どのような問題形式がいいでしょうか 考えていたものを以下に書きます

- 木が与えられます。頂点0を根とし、この木のそれぞれの頂点に対応する部分木のうち同型でないものがいくつあるか数えてください。

## 入力

```
N
木
```

## 出力

```
uniqueな部分木の個数
```

## 制約

決定的なO(NlogN)のアルゴリズムがあります 熨斗袋さんがO(N)のアルゴリズムを構築したと言っていました

**Comment by yosupo06** [comment]
提案ありがとうございます！

問題概要: いい気がします

ID / 問題名: 使用するアルゴリズムより問題自体を表した名前をつけたいです　rooted_tree_hash より rooted_tree_isomorphismとかそんな感じにしたいです

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/number_of_substrings これに合わせてNumber of Subtreesとかいいかもしれません　ところで今思い返すとNumber of Distinct Subtreesにするべきだったかもなと思うので、Number of Distinct Subtreesもアリです
