### ISSUE TITLE
[問題案] Sort Points by Argument

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#248]
(任意) 問題ID: sort_points_by_argument
問題名: Sort Points by Argument

# 問題概要

二次元平面にN個の点が与えられる atan2(x, y)でsortして出力

言い換えると、y = 0, x < 0の半直線からスタートして、反時計回りに点をsort

(x=0, y=-1): これは一番最後に置く(atan2(0, -1) = Piより)
(0, 0): 入力としてそもそも与えるか？ atan(0, 0) = 0なのを考えれば(0, 1)と同じ
同じ2点の順序: どちらでもよい

## 入力

```
N
x0 y0
:
xN-1 yN-1
```

## 出力

```
x0 y0
:
xN-1 yN-1
```

## 制約

N <= 200,000 or 500,000

**Comment by polyomino-24** [comment]
ググってみた感じだと、argumentよりもsort(ing) points by polar angleとかin counterclockwise orderとかの方がいいかもしれません(検索力が低いかも)
あと、偏角でsortと言われると(1,0)スタートな感じがする気がします

**Comment by yosupo06** [comment]
ありがとうございます　私も調べてみましたが複素数だとargument、2次元の点だとpolar angle(or counterclock wize)みたいな印象を受けました

どちらかというと2次元の点を複素数として扱うのは特殊な感じがするので、polar angleとかにしたほうが良さそうな感じがします　ありがとうございます

また、(1, 0)スタートなのはなんか理由とかありますでしょうか？　偏角をwikipedeiaで調べてみたんですが(雑)、(x<0, y=0)がスタート&ゴールのように見えます(偏角を[-PI, PI]と[0, 2PI]のどっちで定義するかと言う話かも)　https://ja.wikipedia.org/wiki/%E8%A4%87%E7%B4%A0%E6%95%B0%E3%81%AE%E5%81%8F%E8%A7%92

**Comment by polyomino-24** [comment]
数学に明るくないので角度といったら正なつもりでした
[-PI,PI)で考えるのも合理的なのでどっちでもいいと思います!

**Comment by yosupo06** [comment]
適当にいくつか言語を調べてみたんですが、どれもatan2は[-PI, PI]っぽいので、これで行こうと思います　指摘ありがとうございます！

**Comment by beet-aizu** [comment]
x, yは整数ですか？

**Comment by yosupo06** [comment]
はい

**Comment by yosupo06** [comment]
XYが整数とかく
