### ISSUE TITLE
[問題案]オイラー路

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#25]
euler tour / pathなどをどうするか？

全部まとめる？

**Comment by maspypy** [comment]
辞書順最小の～が必要になったが、これもやるかどうか。

**Comment by maspypy** [comment]
とりあえず案を書きます。

# 問題
グラフが与えられる。Eulerian Trail があるか判定し、あれば次の形式で出力せよ。

頂点の列と辺の列という形式（https://judge.yosupo.jp/problem/cycle_detection_undirected）

```
Yes
v_0 v_1 ... v_n
e_0 e_1 ... e_{n-1}
```

- 自己ループ、多重辺はありうる
- 連結とは限らない
- 有向・無向で 2 問つくる

**Comment by noshi91** [comment]
- 孤立点があるときに No になるかどうか

**Comment by maspypy** [comment]
No になる定式化、ありましたっけ。すべての辺を通るものを想定していました。

**Comment by maspypy** [comment]
作業者募集で。

**Comment by maspypy** [comment]
有向・無向のどちらかだけでもよいです。

**Comment by maspypy** [comment]
作ります。

予定
- 作るべきケースがよくわからないので、マルチテストケースにします。
- $m=0$ も入れます（任意の 1 点 0 辺からなるパスが満たす）
- $n=0$ は入れません
