### ISSUE TITLE
入出力の速度の影響が強すぎてライブラリの速度比較が困難なのをなんとかしたい

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#250]
ライブラリの速度は重要ですが、現状はその比較が困難でつらいです。
たとえば https://judge.yosupo.jp/problem/convolution_mod は最速提出が 130ms ぐらいですが、`scanf`, `cin` を使うとそれぞれここから 100ms, 300msぐらい遅くなり、比較が成立しません。

現状挙がっている案は以下です。

1. Topcoder 形式で関数本体だけ計測する
1. 入力を乱数生成して入出力量を減らす
1. 全員に高速入出力を使わせる
    1. 入出力専用のベンチマーク問題を作る
    1. 高速入出力を使った入出力パートを提供する

https://twitter.com/yosupot/status/1201518018271989762
https://twitter.com/a3VtYQo/status/1201524251536195584

**Comment by yosupo06** [comment]
> 1. Topcoder 形式で関数本体だけ計測する

全部の言語に対応するのは非現実的だと考えています　C++に限ってのサポートとかならばまだ可能かもしれませんが、コンパイルのところから変えないといけないので積極的にやりたくはないです

> 2. 入力を乱数生成して入出力量を減らす

(Convolutionなどの)数え上げ系に限れば可能かもしれません　そうではない問題に対しては特殊なテストケースの作成が著しく困難になるはずで、verifyの方が弱くなっては本末転倒な気がします

> 3\. 全員に高速入出力を使わせる

この方針が一番現実的だと思います　ただすごい設計(全ケースをzipにまとめてSQLにbyteaとして突っ込む)をしたせいで問題ごとに(全入力、出力をzipしたもの)のサイズが1.7G(SQLのRAM)を超えると多分デプロイできなくなるという話があり、あまり大容量は厳しそう

**Comment by yosupo06** [comment]
どうやらlong long 2e6個が動きそうなことがわかったんで、入出力専用の問題を作ります a + b (1e6ケース)とかで良さそう
