### ISSUE TITLE
random.h の uniform_pair がなんだか変

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#253]
`random.h` の `uniform_pair` は現状次のようになっています。
コメントは

1. 「閉区間 [l, r] から (必ずしも異なるとは限らない) 2要素をsortして返す」

な感じですが、実装は

2. 「2点以上含む閉区間 [l, r] から異なる2要素をsortして返す」

です。

https://github.com/yosupo06/library-checker-problems/blob/800d18c347328309c92502248051eefda9057fd9/common/random.h#L79-L90

そして実際の使われ方には (1.) を想定しているものがほぼすべてで、結果として微妙にバグってます。
たとえば [point_add_range_sum](ttps://judge.yosupo.jp/problem/point_add_range_sum) の `random.cpp` では以下のように使われているんですが、以下の問題があります。

-   N = 1 を許す制約だけど N = 1 で `assert` で落ちる。
-   長さ 1 の区間のクエリが生成されない。

https://github.com/yosupo06/library-checker-problems/blob/800d18c347328309c92502248051eefda9057fd9/datastructure/point_add_range_sum/gen/random.cpp#L27-L28

ところで、どうせ仕様変更するなら、用途を考えると (3.) 「空でない半開区間 [l, r) から空でない部分区間を返す」にしたい気もします。

**Comment by yosupo06** [comment]
ありがとうございます、ああー大惨事…

空でない区間[l, r)を生成する用途がほとんどのはずなんですが、uniform / uniform_pairが並んでいて区間の開閉が違うと困惑するんじゃないかと思ってこうしています(uniformはuniform_int_distributonに合わせて閉区間にした) 現に失敗していますが

**Comment by yosupo06** [comment]
ランダムな2点を返すという設計はあまりおかしくない気がしてしました

[l, r) から空でないランダムな半開区間を選ぶ はuniform_pair(l, r)で、実はそのまま対応しています

**Comment by yosupo06** [comment]
なので、実は仕様変更するまでもなくkimiyukiさんの提案した仕様になっていて、使い方を完全に間違えていた が正しい気がしています😖
