### ISSUE TITLE
非再帰セグ木は2べきでバグりがちだしそういうテストケースが入っててほしい

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#259]
実際にわたしの非再帰遅延セグ木も2べきでバグっていました。

N = 1, 2, 3, ..., 10 ; Q = 1000 ぐらいのケースを並べておくのがよいかなと思います。
いまそういうケースが入ってない問題は以下の4つです。

- `staticrmq` #34
- `point_set_range_composite` #122
- `point_add_range_sum` #20
- `range_affine_range_sum` #233

**Comment by yosupo06** [comment]
とても同意します
