### ISSUE TITLE
random.h の uniform もなんだか変

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#261]
コメントには `[lower, upper]` とある (実装も `uint64_t next(uint64_t upper)` を読む限りたぶんそうなってる) が、実際の利用では `[lower, upper)` が想定されていそう。

実装 (`[lower, upper]` って言ってる)

https://github.com/yosupo06/library-checker-problems/blob/5face7acd002a8fe2cd76fa6744f0901c194eb36/common/random.h#L65-L70

利用例 (MOD 未満の値を生成したいので `[lower, upper)` を想定してそう) https://judge.yosupo.jp/problem/convolution_mod

https://github.com/yosupo06/library-checker-problems/blob/5face7acd002a8fe2cd76fa6744f0901c194eb36/math/convolution_mod/gen/random.cpp#L12-L19

**Comment by yosupo06** [comment]
これはconvolution作るときに普通にミスった感じですね ありがとうございます
