### ISSUE TITLE
[問題案]Sqrt Mod(sqrt_mod)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#27]
Tケース

y, pが与えられる。x^2 = y (mod p)なるxを1つ求めよ(存在しない場合、-1)

- 1 <= T <= 100,000
- 2 <= p <= 10^9
- 0 <= y < p
- p is prime

**Comment by yosupo06** [comment]
ケース生成が重過ぎる

**Comment by hos-lyric** [comment]
問題一覧に表示されてない気がする
(どこを直せばいいのかわからないので報告でゆるして)

**Comment by yosupo06** [comment]
あぁ〜忘れてた〜

**Comment by yosupo06** [comment]
#61 でついでにy = 0も入ったので、いっかい閉じます

**Comment by yosupo06** [comment]
テストケースが弱い？

**Comment by hos-lyric** [comment]
今ので弱いかどうかはわからず…… (あとで眺めたい (希望))

ところで，わたしのやつ (Cipolla) は最悪 O(log p) だけど，有名な Tonelli–Shanks は p - 1 が 2 で割れるほど遅い (2 乗かかる) という話があり，これもやはり複数ケース要注意案件だったりする

**Comment by yosupo06** [comment]
弱いという報告を受けたの、sqrt(母関数)の方だった…

それはそうとしてTonelli-Shanksの最悪計算量は完全に忘れていたので、OK(結果論)

**Comment by yosupo06** [comment]
p - 1が2で割れる、ということでmod 998244353 onlyを足しました
