### ISSUE TITLE
破壊的変更をされるとverify-helperが死ぬ

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#270]
@kmyk 解決策をご存知ないですか

**Comment by kmyk** [comment]
ないです

- 破壊的変更で壊れないようにするだけなら library-checker-problems のバージョンを固定すればよい。でも library-checker-problems に新規問題が追加されても verify helper を更新するまで使えなくなってしまい、むしろ手間が増える
- 入出力データを web 上から取得するようにすると generate.py を叩かなくてよくなる。しかし今度は web frontend が落ちたときに動かなくなるので結局変わらない
- verify helper は Library Checker 以外にも AOJ が落ちたり破壊的変更したりしても死にます。Library Checkerだけを頑張ってもあまり意味がない

**Comment by beet-aizu** [comment]
涙　とまらな
