### ISSUE TITLE
generate_test.py がキャッシュの有無を考慮していない

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#274]
「すでに `in/*` や `out/*` があれば実行を省略する」の機能があるので、次のふたつが必要です:

1. `generate_test.py` を実行するたびに `in/*` `out/*` を削除する
2. 複数回実行しても失敗しないことを確認するテストを書く

(1.) は tempdir を作ってそこへ諸々のデータをコピーし、その中でテストを行うようにするのがおすすめです。

**Comment by yosupo06** [comment]
忘れてました　ありがとうございます
