### ISSUE TITLE
FPS系に答えに0が含まれるテストデータが欲しい

### ISSUE THREAD

**Issue by windows-server-2003** [yosupo06/library-checker-problems#283]
MOD取るときの不注意なんですけど[これ](https://judge.yosupo.jp/submission/3981)とかが例えば
```
2
1 0
```
で答えの要素に998244353を吐いて落ちるのでそのようなケースがあると喜びます
同様のことが起こるかもしれない問題 : 
#42 
#46 
#65 
#66 
#73 
#145

**Comment by yosupo06** [comment]
(MOD - i) % MODを(MOD - i)と書いてしまうということですね　確かにありそう

**Comment by windows-server-2003** [comment]
はい

**Comment by windows-server-2003** [comment]
やります、NをMAXにするのは避けた方が良いですか ?
別にTLEで落とすわけじゃないのにやたらテストが重くなりそうだなっていう一方であんまり小さいとN <= 100の時だけ愚直畳み込みするみたいな最適化してたときに困ると思いました

**Comment by yosupo06** [comment]
多分追加するのは1,2ケースだと思うので、特に避けなくて大丈夫です

**Comment by windows-server-2003** [comment]
ありがとうございます
