### ISSUE TITLE
[問題案] Frequency Table of Tree Distance

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#292]
問題ID: {ID}
問題名: {名前}

# 問題概要

木が与えられます。各頂点対(i, j)について、dist(i, j)を求めて、各K = 0,1,...,N-1について、dist(i, j) = Kとなるペアがいくつあるか数える

## 入力

```
```

## 出力

```
```

## 制約

N <= 100,000?200,000?

## 検討

- 問題ID
- ペアはordered?unordered?

**Comment by hos-lyric** [comment]
メモ：https://judge.yosupo.jp/submission/48554 が https://atcoder.jp/contests/abc312/tasks/abc312_g のサンプル 2 で落ちた (たぶん配列サイズ)
ケースを足すかもしれません (実際に RE 起こす条件はよくわかってないので適当に……)
