### ISSUE TITLE
English translaation

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#295]
海外のプロたちが参加してくれると、問題追加速度が上がってうれしい

**Comment by yosupo06** [comment]
賛成です

**Comment by yosupo06** [comment]
とりあえずジャッジサイトの2言語対応(accept-language?)と、問題文の翻訳さえすれば平気かな

**Comment by kmyk** [comment]
- Accept-Language は (正しいのだけど) 操作できないのであまり推奨できなくて ([参考](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Accept-Language))、AtCoder みたいに Cookie で設定できた方がうれしいです。
  手間だけ考えるとひとまずは日本語問題文と英語問題文をそのまま両方併記するのもありな気がする。 It is the easiest to write the problem statements in both Japanese and English.
- 翻訳は [CONTRIBUTING.md](https://github.com/yosupo06/library-checker-problems/blob/master/docs/CONTRIBUTING.md) もほしい

**Comment by yosupo06** [comment]
> * Accept-Language は (正しいのだけど) 操作できないのであまり推奨できなくて ([参考](https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Accept-Language))、AtCoder みたいに Cookie で設定できた方がうれしいです。

これ知りませんでした、ありがとうございます

>   手間だけ考えるとひとまずは日本語問題文と英語問題文をそのまま両方併記するのもありな気がする。 It is the easiest to write the problem statements in both Japanese and English.

これありです　なぜなら一切多言語とか考えた設計をしていないため

**Comment by yosupo06** [comment]
ひとまずの次のステップとしては、task_en.md / task_ja.mdを用意して、それをhtmlgen.pyで

<div class="ja">
問題文 ~
</div>
<div class="en">
Problem Statement ~
</div>

みたいなhtmlにして、後はサイトのヘッダかなんかで調整するのが楽かな(サーバーからO(言語数)倍の問題文を受け取ることになるけど、定数倍(というかどうせja / en以外は対応しない気がするし)だしいいかな

**Comment by yosupo06** [comment]
#417 で一応形になった

**Comment by kmyk** [comment]
:tada:
