### ISSUE TITLE
[問題案] Dynamic Tree Vertex Set Path Composite (dynamic_tree_vertex_set_path_composite)

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#307]
(任意) 問題ID: dynamic_tree_vertex_set_path_composite
問題名: Dynamic Tree Vertex Set Path Composite

# 問題概要

#190 と #223 を合体させたやつ

木が与えられる。頂点 $i$ には関数 f_i(x) = (a_i x + b_i) が置いてある。

- 0 u v w x: 辺(u, v)(u,v)を削除, 辺(w, x)(w,x)を作成。
- 1 p c d: f_p(x) = (cx + d)に変更
- 2 u v x: u, v間のパスの頂点(両端含む)の関数列f_v(...f_u(x))を求める

## 入力

```
N Q
a_0 b_0
a_1 b_1
:
a_{N-2} b_{N-2}
u_0 v_0
u_1 v_1
:
u_{N - 2} v_{N - 2}
Query0
Query1
:
Query_{Q - 1}
```

## 出力

```
```

**Comment by yosupo06** [comment]
良さそうです
