### ISSUE TITLE
[問題案] Range K-th Smaller

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#310]
問題名: Range K-th Smaller

# 問題概要
長さ N の非負整数列 A が与えられ、Q 個のクエリを処理
-  l, r, k について A_l ... A_{r-1} のうち k 番目に小さい値を出力

## 入力

```
N Q
A_0 A_1 ... A_{N-1}
l_0 r_0 k_0
l_1 r_1 k_1
:
l_{Q-1} r_{Q-1} k_{Q-1}
```

## 出力

```
```

## 制約
- N < 2e5
- Q < 2e5
- A_i < 1e9

## 検討事項
- smaller or larger
- k を 0-indexed or 1-indexed
- A_i < 1e9 or 1e18

**Comment by yosupo06** [comment]
提案ありがとうございます！

> * smaller or larger

smallerの方が自然だと思います

> * k を 0-indexed or 1-indexed

0-indexedでいいんじゃないでしょうか　日本語だと変ですがsortしてa[k]と考えれば自然だと思います

> * A_i < 1e9 or 1e18

1e9でいいと思います

**Comment by emkjp** [comment]
「$k_i$ 番目に小さい値を出力する」→ 「$k_i + 1$ 番目に小さい値を出力する」
にすれば、問題文として不自然ではなくなると思いました。
