### ISSUE TITLE
[問題案] Nim Product (F_{2^{64}})

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#317]
問題ID: nim_product_64
問題名: Nim Product (F_{2^{64}})

想定アルゴリズム: 何かしら前計算して速くやる
参考資料: https://en.wikipedia.org/wiki/Nimber

# 問題概要
T cases.
Given A and B, calculate the nim product of A and B.

## 入力

```
T
A_0 B_0
...
A_{T-1} B_{T-1}
```

## 出力

```
answer_0
...
answer_{T-1}
```

## 制約
- 1 <= T <= 10^6
- 0 <= A, B < 2^{64}

**Comment by hos-lyric** [comment]
https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-533288249

やる意思があります
近頃 2 回も出ちゃったので (もう出ないか？)
もっと大きい体上でやるやつもあり得るし出題の機運もありそうだけど，2^64 はそれはそれで出題されがちなのでとりあえず

問題名
[nim|nimber] [product|multiplication] で 4 通りもありがち
Google に聞いて一番多かった "nim product" に仮でしといた

**Comment by hos-lyric** [comment]
制約，適当に書いてしまった

毎回 64^2 するのともっとがんばるのを区別できるようなサイズにはする
(別に 64^2 が AC するようなサイズでもいいけど)
ちょい小さいデータも入れる

ファイルサイズ的な制約はわかりません

意見募 @yosupo06

**Comment by yosupo06** [comment]
せっかくだし10^6ケースにしてみましょうか　サーバーが耐えられるかはやってみないとわかりませんが、行ける気がしてます(ええ…)　自明な上界としてケースを圧縮したものが3.5G超えると壊れるのは確かです

**Comment by yosupo06** [comment]
https://codeforces.com/contest/1314/problem/F 貼っておきます(実際実装例として優秀な気がする、この問題)

**Comment by yosupo06** [comment]
タイトルぶっ壊れたんですが(残念)、急いで調査します

**Comment by hos-lyric** [comment]
シングルクォート文字列はエスケープ要らない可能性 (無知で物を言っています)
https://qiita.com/minoritea/items/c0de47b8beb813c655d4#%E6%96%87%E5%AD%97%E5%88%97

**Comment by yosupo06** [comment]
直りました
