### ISSUE TITLE
markdownのja / enを使いやすくする

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#326]
`<div markdown="1" class="lang-ja">`は長い？

```
{{lang en}}
Hello World
{{end}}
{{lang ja}}
こんにちは 世界
{{end}}
```

とか

```
{{lang Input 入力}}
--------

- 1 <= N <= 100,000
```

とか(en, ja以外が来ると壊れる / 特に理由なくgoのtemplateに合わせていたが、無理があるかも)

**Comment by kmyk** [comment]
(ところで、`task.md` のテンプレート記法はそろそろ手動解析をやめて既存のエンジン ([Jinja](https://github.com/pallets/jinja) とか) に任せた方がよさそう)

**Comment by yosupo06** [comment]
依存ライブラリ数をとるか、可読性をとるかといったところですね(このままテンプレート増えてくならどっかで移った方が良さそう)

**Comment by yosupo06** [comment]
とりあえずpythonのテンプレートエンジンはJinja2一強を感じたので、これを調査

**Comment by yosupo06** [comment]
## task.md草案

aplusbのtask.mdは以下のようになる

    {{keyword.statement}}
    ---------

    {{ setlang('en') }}
    You are given integers $A$ and $B$. Print $A + B$.
    {{ resetlang() }}
    {{ setlang('ja') }}
    整数 $A, B$ が与えられます。 $A + B$ を出力してください。
    {{ resetlang() }}

    {{keyword.constraints}}
    ---------

    - $0 \leq A, B \leq {{param.A_AND_B_MAX}}$


    {{keyword.input}}
    ---------

    ```
    $A$ $B$
    ```

    {{keyword.output}}
    ---------

    ```
    $A + B$
    ```

    {{keyword.sample}}
    ---------

    {{example.example_00}}

    {{example.example_01}}

## 変換コードの実装

 https://gist.github.com/yosupo06/97e4170c32c4468c4c2944450cbd1e8dにconvert.py, task.md, test.html(出力結果) が置いてある

`aplusb/in/example*.in`, `aplusb/out/example*.out`を全部同じディレクトリに置いて実行するとtask.mdがtest.htmlになる

**Comment by yosupo06** [comment]
task.mdの草案が重要　なにか案などあれば

**Comment by hos-lyric** [comment]
```
{{section.statement.en}}
English

{{section.statement.ja}}
日本語

{{section.constraints}}
- $0 \le N \le {{param N_MAX}}$

...
```

とかがシンプルでいいかなと思いますが (命名は適当) (これは .md なのか？ 知りません)，
どうせ何かをコピペするので作問側の手間は (変換作業が苦しくならなければ) あまり変わらないかもしれません

**Comment by yosupo06** [comment]
まとめすぎるとちょっと変な位置(入力とか出力とかに)注釈を入れたい時に困りそう

```
{{keyword.hoge}}
---------
```

はもう定型なんだからまとめれば、というのは、とてもそう

**Comment by yosupo06** [comment]
## {{keyword.statement}}

    {{ lang.en }}
    You are given integers $A$ and $B$. Print $A + B$.
    {{ lang.ja }}
    整数 $A, B$ が与えられます。 $A + B$ を出力してください。
    {{ endlang }}

    ## {{keyword.constraints}}

    - $0 \leq A, B \leq {{param.A_AND_B_MAX}}$

    ## {{keyword.input}}

    ```
    $A$ $B$
    ```

    ## {{keyword.output}}

    ```
    $A + B$
    ```

    {{ lang.en }}
    You can't print $A - B$
    {{ lang.ja }}
    $A * B$とかを出力しないでください
    {{ endlang }}

    ## {{keyword.sample}}

    {{example.example_00}}

    {{example.example_01}}

マイナーな修正を行い、全体的に短くなるようにしました

```## hoge```とかは無理に消す必要ないかなと思い(markdownの修飾は無理に消すとエディタで編集するときわかりにくそうなので)

**Comment by yosupo06** [comment]
```{{constraint N_MAX}}```と書いたら勝手に制約が生えるというのもアリそうだが、これはやるなら別チケット

**Comment by yosupo06** [comment]
jinja2を使うとKaTex(≒mathjax)が暴発することがわかったので(以下に例)、ちょっと考えます…

```
$a_{{N-1},0}$ $a_{{N-1},1}$ ... $a_{{N-1},{N-1}}$
```

**Comment by kmyk** [comment]
その問題は無視してもよい気がします。`$a_{ {N-1},0}$ $a_{ {N-1},1}$ ... $a_{ {N-1},{N-1} }$` のように空白を入れれば暴発しないし、暴発しても `jinja2.exceptions.TemplateSyntaxError` で落ちるぽいので CI の時点で気づいて修正できるためです。

**Comment by yosupo06** [comment]
texに非自明な制限が入ると、エラーメッセージが読み取りにくいことを考えるとcontributerの体験が不要に悪くなる気がしてきて避けたいです

かといって今までのように正規表現でルールを書き続けるのはやめたいので、折衷案としてはjinja2のdelimiterを変更することだと思います。
https://stackoverflow.com/questions/33775085/is-it-possible-to-change-the-default-double-curly-braces-delimiter-in-polymer 本来のjinja2との互換性は消えますが、元々markdownとのキメラな上に再利用するものでもないので、大した問題ではなさそう

**Comment by yosupo06** [comment]
`{: param.MAX_N :}`にしようと思います　理由はコロンはmarkdownでもtexでも使わなそうな記号のため

**Comment by yosupo06** [comment]
f : R -> Rなどで使いますが…

**Comment by yosupo06** [comment]
`@{param.A_AND_B_MAX}` にします。選定理由は@なんてマジで使わなそうだからです　使わないと信じています

**Comment by hos-lyric** [comment]
これは雑談ですが関数のときは \colon を使うべきという話がある (要求し出すと contributer の体験が悪化)．他には比としてのコロンがあるけど久しく使ってないですね

`{:` や `:}` でない `:` が特殊判定されるのでなければ `:` でもよいかもしれません

`@` は少なくとも数式中はなくても生きていけそうです．`}` が変に判定されるとかがなければよいと思います
