### ISSUE TITLE
[問題案] Many A + B

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#329]
問題ID: many_aplusb
問題名: Many A + B

想定アルゴリズム: 入出力の速度計測 / テスト

# 問題概要

TケースのA + B

## 入力

```
T
A B
A B
:
A B
```

## 出力

```
A+B
A+B
:
A+B
```

## 制約

T <= 1e6
A, B <= 1e18

**Comment by yosupo06** [comment]
https://twitter.com/___n___z/status/1235103149511176192

**Comment by yuppe19** [comment]
MEMORY ってメモリ使用量ですよね？
単一クエリの問題の提出と比較すると、どの提出も妙に多い気がします。
こんなもんなんでしょうか…。

**Comment by yosupo06** [comment]
確かに多いですね　入力ファイルがキャッシュに乗って、それが加算されてるかもしれません(対処法は、不明…)

**Comment by yosupo06** [comment]
全部10^18のケースを入れる(入力が17byteか18byteかで実は結構違う)
