### ISSUE TITLE
[問題案]Unionfind(unionfind)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#33]

**Comment by yosupo06** [comment]
経路圧縮のみのやつのworst case、Rankのみのやつ(あとRankの代わりに重みを使うやつ)のworst caseを用意する

経路圧縮のみのやつは http://www.csd.uwo.ca/~eschost/Teaching/07-08/CS445a/p245-tarjan.pdf に乗ってるかな(フィボナッチ数みたいなイメージの変な木の構築だったはず)

両方のやつの最悪ケース(\alphaかかるやつ)は、いるかな…？

**Comment by hec12** [comment]
UnionFindの各要素の連結成分のサイズを取得するクエリもverifyしたい．これは別の問題として切り出しても良い気がします．

**Comment by maspypy** [comment]
別問題の提案がすでにあるので、close

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/unionfind のforumはここを指していそう？
