### ISSUE TITLE
[問題案] Find Linear Recurrence (Berlekamp-Massey)

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#330]
問題ID: find_linear_recurrence
問題名: Find Linear Recurrence

想定アルゴリズム: Berlekamp-Massey

# 問題概要
整数列 A_0, ..., A_{N-1} が与えられる．
以下を満たす整数列 c_1, ..., c_d (d >= 0) であって d が最小のものを 1 つ求めよ：
- 0 <= c_j < 998244353 (1 <= j <= d)
- A_i == \sum_{j=1}^d c_j A_{i-j} (mod 998244353) (d <= i < N)

## 入力
```
N
A_0 ... A_{N-1}
```

## 出力
```
d
c_1 ... c_d
```

## 制約
- 0 <= N <= 5000
- 0 <= A_i < 998244353

**Comment by hos-lyric** [comment]
戦争要素がありすぎる

- 問題 ID・問題名
  - Mathematica に FindLinearRecurrence というのがあるから滅茶苦茶な命名ではないという程度
- 列の長さ
  - l と言って長さ l+1 の列を求めるのは今までの何かの問題と合致してない気がする
  - でも次数である l のほうが自然な値ではある
- 列の順番
  - 問題文に書く添え字はどっちでもいいとして出力の順番をどっちにするかという話
  - 具体例を出さないと頭こわれる：例えば Fibonacci 数列だったら X^2-X-1 と 1-X-X^2 のどっちですか？という話
  - 特性方程式と言ったら前者を指しそうで (自信ない)，後者は母関数を有理式で書いた場合の分母で，どっちが自然な概念なんだろう……．
- 1 を出力するか否か，符号をどっちにするか
  - Fibonacci 数列だったら 1-X-X^2 だから [1, -1, -1] を出力する vs a_i = 1 a_{i-1} + 1 a_{i-2} だから [1, 1] を出力する
  - Mathematica は後者

戦争要素でないと思っている点

- N = 0 のときは l = 0 が答え (なくてもよい)
- まったく漸化式がないときは l = N が答え
- N < 2 l くらいのとき (たぶん) に答えが一意とは限らないので special judge
- 法が素数じゃないときはわたしはアルゴリズムを知らないのですが計算量が変わるらしい？のでとりあえず 998244353 で

**Comment by hos-lyric** [comment]
l という文字の使用も戦争ポイント
(自分のコードで l になっていたというだけ．m とか d とかも候補だと思う)
(後から変えられるけど議論や gen を読みやすくするために決めとくと便利かも)

**Comment by yosupo06** [comment]
こっちの出力と #170 の入力を合わせたい

個人的にはa_4 = 2 * a_3 + 3 * 2a_2 + 4 * a_1だったら、

```
3
2 3 4
```
を出力かな

**Comment by hos-lyric** [comment]
#170 と合わせたいのはとてもわかる
a_4 = 2 * a_3 + 3 * a_2 + 4 * a_1 だったら

```
3
2 3 4
```

を出力する形式は大変一理あるので従っていこうと思います

↑↑↑を書き換えた
文字はどうでもいいけど l が d になった．#170 を N 項間 (N + 1 項間) にするなら d が n で N が K か？ってなるけど「d 次の漸化式」ってよくありそう．たぶん．

やっていきます

**Comment by yosupo06** [comment]
変数名見逃してました　慣例に合わせるとこの位置に出力する変数名はXなんですが(思考停止の産物)、流石にdでいいと思います

**Comment by hos-lyric** [comment]
ここでの大小の使い分けがよくわかってないけど N, a, d, c で準備中
(#170 では d, c が入力になりそうで，D, c なのか……？)

**Comment by adamant-pwn** [comment]
Hi, it seems that the testset lacks some cases in which the answer consists of zeros, but of the lower amount than `n`.

For example, I have a solution that for the testcase
```
6
0 1 0 0 0 0
```
would output
```
6
0 0 0 0 0 0
```
I believe, the correct answer here is something like
```
2
0 0
```

**Comment by adamant-pwn** [comment]
Another example is
```
6
0 1 1 1 1 1
```
My program would output
```
6
0 0 0 0 0 0
```
but the correct answer is
```
2
1 0
```

**Comment by adamant-pwn** [comment]
or
```
6
1 2 2 2 2 2
```
My output:
```
5
2 998244351 2 998244351 2
```
Correct output is same as above...

**Comment by kmcshane123** [comment]
Several submissions fail when the mod is changed 1000000007.
For example
input
12
1 1 4 8 23 55 144 360 921 2329 5924 15024
answer should be
2 2 1000000005 1
while some of the submissions produce a recursion of length 5
for example Nyaan's and hly1204's submissions.
