### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#331]
$998,244,353$
->
$998{,}244{,}353$

いつも複数の整数に見えてしまって気になります
`{,}` を使うのはもしかしたらバッドノウハウかもしれないけどお手軽だと思います
`htmlgen.py` だけでも直ったらうれしいです

**Comment by yosupo06** [comment]
${{params MOD}}$か{{params MOD}}のどっちかは壊れそう　でも後者のような使い方しないかな
