### ISSUE TITLE
--verifyをオンにしてたら自動で--ignore-cacheもオン

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#333]
--verifyを付けてるのにキャッシュ使いたいこと、あるか？

**Comment by hos-lyric** [comment]
他の操作でもキャッシュが使われて個人的に直感に反することがありました (例：generator を編集してオプションなしで走らせたときにデータが更新されなくてどうしようかとやや困った)
デフォルトでキャッシュを使わず --cache オプションを足すくらいが機能も減らずにいいかなと思いました
パソコン弱者より

**Comment by yosupo06** [comment]
デフォルトの挙動は全て普通のユーザー(ただテストケースを見たい人)の挙動にしようと思っています　なのでキャッシュはデフォルトかなぁと思います

ですが実際問題generate.pyはオプションが多すぎてよく分からないので、なんとかしたい
