### ISSUE TITLE
[問題案] Stirling Number of the First Kind

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#336]
問題ID: stirling_number_of_the_first_kind
問題名: Stirling Number of the First Kind

想定アルゴリズム: 二分木っぽくかけ算する O(N (log N)^2) or 資料参照 O(N log N)
参考資料:
https://discuss.codechef.com/t/chefknn-editorial/18179
https://min-25.hatenablog.com/entry/2015/04/07/160154

# 問題概要
s(n, k) を X (X - 1) ... (X - (n - 1)) の X^k の係数とする
N が与えられるので s(N, 0), ..., s(N, N) を mod 998244353 で求める

## 入力

```
N
```

## 出力

```
s(N, 0) ... s(N, N)
```

## 制約

- 0 <= N <= 500,000

**Comment by hos-lyric** [comment]
もめどころ

- 符号つきにするか符号なしにするか

制約

- bernoulli_number とかその辺に合わせただけで，適当
- N 巨大で k が小さいのを求めるのはもっと速くできたりするかも？でもわたしは知りません

**Comment by yosupo06** [comment]
- 符号つきか符号なし調べてみた限り、両方出てきて謎といった感じです。個人的にはunsignedの方が出力が見やすそうだなと思いますが、準備する人に決める権利があるということでいいと思います

- O(N log N)で高速そうなのでN = 500,000でいいんじゃないかと思います(もちろんCIの速度によってはというのはありますが)

**Comment by hos-lyric** [comment]
- 符号つきのほうが第 2 種と対称な定義ができたりして好きなのですが完全に宗教．ところで Mathematica の StirlingS1 が符号つきでした．符号つきでやっていく決意が
- 制約はむしろ大きくしてもいいんじゃない？の意図でしたが別に大きくする必要もさほどないので他と合わせておきます

**Comment by hos-lyric** [comment]
ところで問題 ID は stirling_number_1 とかでもいいかもしれないと思ってきました
admin 様の好みはありますか

**Comment by yosupo06** [comment]
- 符号に関して強い主張はないです
- 制約はベリファイの理想的には大きければ大きいほどいいです　が他の部分の制約(ジャッジ並列度が1なのでTLEでめっちゃ詰まる)とか気にして今ぐらいになってます
- 私はstirling_number_of_the_first_kindでいいんじゃないかなと思ってます 調べた限りこの表現ばっかりなので
