### ISSUE TITLE
[問題案] Stirling Number of the Second Kind

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#337]
問題ID: stirling_number_of_the_second_kind
問題名: Stirling Number of the Second Kind

想定アルゴリズム: 式を書いて畳み込むだけ O(N log N)
参考資料: https://min-25.hatenablog.com/entry/2015/04/07/160154

# 問題概要
S(n, k) を第 2 種 Stirling 数とする．
N が与えられるので S(N, 0), ..., S(N, N) を mod 998244353 で求める

## 入力

```
N
```

## 出力

```
S(N, 0) ... S(N, N)
```

## 制約
- 0 <= N <= 500,000

**Comment by hos-lyric** [comment]
こっちは定義でもめるとかはないと思う
畳み込むだけではあるけど，「0^N, ..., N^N をちょっと速く求める」をチェックしたい人も使えるかもしれない (?)

**Comment by yosupo06** [comment]
良さそうです
