### ISSUE TITLE
[問題案]Static RMQ(staticrmq)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#34]

**Comment by yosupo06** [comment]
クエリが完全にランダムだとブロック分割で容易に<O(n), O(1)>が達成できてしまうので、幅の小さいクエリばっかのケースを用意する

**Comment by madhur4127** [comment]
It is amusing to see that O(1) sparse table solution has the same time as O(log n) iterative segment tree.

[Sparse table - 85 ms](https://judge.yosupo.jp/submission/14847)
[Segment Tree - 86 ms](https://judge.yosupo.jp/submission/14849)

**Comment by yosupo06** [comment]
We need O(N log N) time for constructing the sparse table and N = Q in this problem...
