### ISSUE TITLE
[問題案] Dynamic Graph Vertex Add Component Sum

### ISSUE THREAD

**Issue by hotman78** [yosupo06/library-checker-problems#347]
問題名: Dynamic Graph Vertex Add Component Sum

想定アルゴリズム: Dynamic connectivity
参考資料:
https://en.wikipedia.org/wiki/Dynamic_connectivity
http://web.stanford.edu/class/archive/cs/cs166/cs166.1166/lectures/17/Small17.pdf
https://u.cs.biu.ac.il/~liamr/p723-holm.pdf

# 問題概要
頂点iにAiが書かれた頂点数のNの空グラフが与えられます
以下のQ個のクエリを処理してください
`0 u v` : 頂点uと頂点vを繋ぐ辺を張る
(このクエリの前、頂点uと頂点vは辺で結ばれてない事が保証されます)
`1 u v` : 頂点uと頂点vを繋ぐ辺を削除する
(このクエリの前、頂点uと頂点vは辺で結ばれている事が保証されます)
`2 i x` : A_i←A_i+x
`3 i` : 頂点iとの間にpathが存在する頂点に書かれた値の総和を出力
## 入力
```
N Q
A_0 A_1 ... A_N
Query_0
...
Query_1
```

## 制約
```
N,Q<=200000
0<=u,v,i<N
```

**Comment by yosupo06** [comment]
クエリの片方は辺削除ですか？参考資料などみるに

**Comment by yosupo06** [comment]
- Connectivity SumじゃなくてComponent Sumかなと思いました なんとなく(連結成分 に対応する単語だと良さそうです)
- 実装したことないのでどのぐらいの速度が出るのかわからないんですが、2s ぐらいには収まってほしいです(多分最悪ケースを作るのが難しいタイプだと思うんで、できれば余裕を持って1s)

**Comment by hotman78** [comment]
題名と問題文を修正しました
ありがとうございます
今色々作ってみたところランダムケースでは愚直の方が早くて悲しい思いをしてます
多分愚直dfsは見る必要のある頂点数増やせば落とせると思うんですが、
全域木を作って辺のreplaceは愚直にやる中途半端ダイコネを落とすのはだいぶ大変そうですね...
色々やってみます

**Comment by hotman78** [comment]
N,Q<=300000の問題で1154msだったので1msで行けるかもしれません

**Comment by hotman78** [comment]
https://qiita.com/hotman78/items/78cd3aa50b05a57738d4
書きました

**Comment by maspypy** [comment]
@hotman78 
すべてのテストケースが u_i < v_i を満たすようですが、どうしましょうか。
（gen.uniform_pair を利用しているため）

1. u_i < v_i を制約に入れる
2. テストケースを作り直す or 追加する

それぞれの利点としては

1. 作問作業が楽。
2. 実用的なライブラリ作りの役に立つ

だと思います。（だとすると、すこし面倒だけど 2. かな、お願いできますか？）
