### ISSUE TITLE
[問題案]Lowest Common Ancestor(lca)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#35]

**Comment by sion-k** [comment]
There is typo on constraints. $0 \le p_i < i$ should changed to $0 \le p_i < N$

**Comment by NachiaVivias** [comment]
> There is typo on constraints. $0\leq p _ i \lt i$ should changed to $0 \leq p _ i \lt N$

No problem. The `verifier.cpp` ensures $0\leq p _ i\lt i$ .

https://github.com/yosupo06/library-checker-problems/blob/2f96c0a261c2ad7df16b19e1008e93d82fdaec99/graph/lca/verifier.cpp line 14
