### ISSUE TITLE
[[solution]] の wrong かどうかを主張しないときどうすればいいのかわからない

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#351]
困ります

具体的には TLE 付近だろうなというのを置くとき困ります
永遠にチェックが通らない #350 

というか何も書かなければ正解とも不正解とも主張しないと思っていました
wrong = false との違いがわからない

**Comment by yosupo06** [comment]
元々はwrongがなくて別の解法を置いておく場所だったので、後方互換性です

**Comment by yosupo06** [comment]
今までは特にTLE付近(というか、間に合っても間に合わなくても差し支えがない)解法がなかったんで、どうしようかな…

**Comment by yosupo06** [comment]
allow_tleというのをつけました 例: https://github.com/yosupo06/library-checker-problems/blob/master/test/allow_tle/info.toml
