### ISSUE TITLE
[問題案]Strongly Connected Components

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#36]

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/submission/3393 提出眺めてたらFail発見　ええ…

**Comment by sansen0796** [comment]
https://judge.yosupo.jp/submission/3739
checher.cpp を読んでみましたが答えのチェックが連結成分の数以外抜け落ちてるのが原因かと

**Comment by yosupo06** [comment]
修正します　ありがとうございます！

**Comment by Kazun1998** [comment]
2-SAT の cycle_unsat_00, 01 にあたるテストケースを SCC にも欲しいです.
(下のライブラリを用いて提出すると, SCC だと通りますが, 2-SAT だと該当ケースで RE になるからです.)

 https://judge.yosupo.jp/submission/92241
