### ISSUE TITLE
[問題案] Three Edge Connected Components

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#360]
問題名: Three Edge Connected Components

# 問題概要
無向グラフを 3-辺連結成分に分解

## 入力

```
N M
a_0 b_0
a_1 b_1
:
a_{M-1} b_{M-1}
```

## 出力

```
K
l_0 v_{0,0} v_{0,1} ... v_{0,l_0-1}
:
l_{K-1}  v_{K-1,0} ... v_{K-1,l_{K-1}-1}
```

## 制約
N, M <= 2*10^5

## 検討事項
入力をどこまで制限するか
- 連結 / 2-辺連結
- 多重辺の有無
- 自己辺の有無

**Comment by yosupo06** [comment]
入力の制約 : なんでもあり
多重辺 : 欲しい
自己ループ : あってもなくても全く関係ない？とりあえずいれて置いてよさそう

と思います

**Comment by noshi91** [comment]
https://github.com/yosupo06/library-checker-problems/blob/master/graph/three_edge_connected_components/task.md
二辺連結成分分解になっています

**Comment by yosupo06** [comment]
英語を足す時に片方書いてコピペしたんでそういうことですね…　申し訳ありません

**Comment by bqi343** [comment]
Where can I read about this (in English)?

**Comment by noshi91** [comment]
Norouzi, N., & Tsin, Y. H. (2014). A simple 3-edge connected component algorithm revisited. Information Processing Letters, 114(1-2), 50-55. [Link](https://www.sciencedirect.com/science/article/abs/pii/S0020019013002470)

The model solution was written based on this paper.
