### ISSUE TITLE
[問題案] Two Edge Connected Components

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#366]
https://github.com/yosupo06/library-checker-problems/issues/360 の三を二にする。

**Comment by yosupo06** [comment]
二重辺連結成分だったら木を出したいかもしれないんですが、どう思いますか

**Comment by yosupo06** [comment]
例

出力

```
K
l_0 v_{0,0} v_{0,1} ... v_{0,l_0-1}
:
l_{K-1}  v_{K-1,0} ... v_{K-1,l_{K-1}-1}
u_0 v_0
:
u_{N - 2} v_{N - 2}
```

**Comment by beet-aizu** [comment]
それは橋の列挙と問題を分けた方がよくないですか？（橋を得られない二辺連結成分分解のアルゴリズムがないとは限らないため）

**Comment by yosupo06** [comment]
別に二重辺連結成分さえ求まれば各辺について端点が同じ連結成分かどうかを調べるだけでよくて

単純に、二重辺連結成分を使う問題のうち多くが二重辺連結成分を求めて木にしてその上で木上のクエリなどを行う問題なので(自分調べ)、木もあったほうが便利かなと思いました

**Comment by yosupo06** [comment]
橋の列挙というより、木を作る方に目的を置いてます　まあ同じなんですが

**Comment by beet-aizu** [comment]
その理屈で言うとSCCもDAGを出力した方が便利じゃないですか？　https://judge.yosupo.jp/problem/scc
二重辺連結成分を求めるパートが合っているのに木の部分でバグらせるみたいなことはあんまりなさそうなので、ただ解く側の手間が増えるだけのような気がします

長々と書いたんですが、別に木を出力してもいいです（は？）　対して変わらないので

**Comment by yosupo06** [comment]
確かにどっちでもいい気がしてきたので　じゃあ出力しない方向で

**Comment by yosupo06** [comment]
そもそも連結じゃないから木じゃないんですよね(気付き)
