### ISSUE TITLE
サンプル数のチェック

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#369]
サンプルが3つあるのにtask.mdに2個しかなかったら警告を出してほしい

**Comment by yosupo06** [comment]
あれ、警告いま出しませんか？

**Comment by beet-aizu** [comment]
./generate.py graph/two_edge_connected_components/info.toml --verify --refhash
だと出なかったんですが、もしかしなくても問題文生成のオプションが必要ですね？（ガイドラインに書いてあると嬉しいです）

**Comment by yosupo06** [comment]
確かに、htmlを生成するときにチェックするので
