### ISSUE TITLE
[問題案] Biconnected Components

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#371]
#366 の辺を頂点にする
問題名の参考: https://en.wikipedia.org/wiki/Biconnected_component

**Comment by beet-aizu** [comment]
単純グラフにした方がよさそう（自己ループの解釈が意味不明になるので）

**Comment by yosupo06** [comment]
何を出力させるか、どう出力させるかが難しそう

**Comment by beet-aizu** [comment]
辺集号族を出力させるつもりでいました。
そもそも  https://atcoder.jp/contests/arc062/tasks/arc062_d 以外で使ったことがなく…

**Comment by yosupo06** [comment]
グラフは単純で(u, v)型で出力 が過去の問題と統一感があるが…

**Comment by beet-aizu** [comment]
前処理で単純にしても結果が変わらないので単純にします（僕のライブラリ、こわれた）
とりあえず辺集合族のままにします
