### ISSUE TITLE
Windows対応

### ISSUE THREAD

**Issue by windows-server-2003** [yosupo06/library-checker-problems#373]
素の(pythonとg++くらいしか入っていない)Windowsの対応をやりたいと思っています
TODO :
 - putc_unlocked/getc_unlockedが使えないので#ifdef _WIN32とかで_putc_nolockと使い分ける(コード修正)
 - なぜかMinGW[-w64]はデフォルトで%lldを認識しないので-D__USE_MINGW_ANSI_STDIOをする(コンパイルオプション修正)
 - 一部のrepマクロ展開後for (int (i) = 0; ...の(i)がエラーになるのでどうにかする(これはコードの方を直すのが適切だと思っています)
 - \r\nなせいでhashが全然合わない、どうにかする
 - stackが足りないので-Wl,--stack=100000000とかを付ける(コンパイルオプション修正)
 - これは提案ですが全データ生成の実行コマンドは環境依存が激しいので```./generate.py $(find . -name "info.toml" -not -path "./test/*")```とかの代わりにgenerate_all.pyとかを置いて中でglobとかするのはどうでしょうか

**Comment by yosupo06** [comment]
> * putc_unlocked/getc_unlockedが使えないので#ifdef _WIN32とかで_putc_nolockと使い分ける(コード修正)

これは多分コードからputc_unlocked / getc_unlockedを消してscanf / printfにしてしまう方がいいです(そんなに数も多くない気がする)

> * 一部のrepマクロ展開後for (int (i) = 0; ...の(i)がエラーになるのでどうにかする(これはコードの方を直すのが適切だと思っています)

これはよくわからないです　C++の規格違反のコードが含まれている？


> * なぜかMinGW[-w64]はデフォルトで%lldを認識しないので-D__USE_MINGW_ANSI_STDIOをする(コンパイルオプション修正)
> * stackが足りないので-Wl,--stack=100000000とかを付ける(コンパイルオプション修正)

これはgenerate.pyをちょっといじるだけで簡単な気がしています

> * これは提案ですが全データ生成の実行コマンドは環境依存が激しいので`./generate.py $(find . -name "info.toml" -not -path "./test/*")`とかの代わりにgenerate_all.pyとかを置いて中でglobとかするのはどうでしょうか

そもそも全データ生成をCI以外(=開発者、利用者のパソコン)ですることを想定していないのでいらないと考えています　全データ生成をしたいことがありますか？

> * \r\nなせいでhashが全然合わない、どうにかする

これ最悪ですね　一番面倒な問題だと思います

**Comment by windows-server-2003** [comment]
> これは多分コードからputc_unlocked / getc_unlockedを消してscanf / printfにしてしまう方がいいです(そんなに数も多くない気がする)

分かりました、これって書いた人にコンタクト取った方がいいですよね
> これはよくわからないです　C++の規格違反のコードが含まれている？

よく見たら-Wparentheses(ただの警告)で規格に適合してそうです(該当コードは例えば```int (x) = 0;```とかです)
ただ-Wno-parenthesesやるとifの中で==を=にしちゃうアレとかもろもろの演算子優先順位の警告とかも消えちゃいそうなのでうーんとなっています
あと他に-Wmaybe-uninitializedが出るコードがあります
> これはgenerate.pyをちょっといじるだけで簡単な気がしています

はい
> そもそも全データ生成をCI以外(=開発者、利用者のパソコン)ですることを想定していないのでいらないと考えています　全データ生成をしたいことがありますか？

確かにないですね
> これ最悪ですね　一番面倒な問題だと思います

pythonをいろいろいじったら全部\n出力にはできたんですけどtestlibがWindows上では\r\n以外認めてくれないのでまたいろいろいじってverifierへの入力もWindows上では\r\nにするようにする予定です

**Comment by yosupo06** [comment]
> > これは多分コードからputc_unlocked / getc_unlockedを消してscanf / printfにしてしまう方がいいです(そんなに数も多くない気がする)
> 
> 分かりました、これって書いた人にコンタクト取った方がいいですよね

特に取る必要はないはずです

> > これはよくわからないです　C++の規格違反のコードが含まれている？
> 
> よく見たら-Wparentheses(ただの警告)で規格に適合してそうです(該当コードは例えば`int (x) = 0;`とかです)
> ただ-Wno-parenthesesやるとifの中で==を=にしちゃうアレとかもろもろの演算子優先順位の警告とかも消えちゃいそうなのでうーんとなっています
> あと他に-Wmaybe-uninitializedが出るコードがあります

warning出るなら直した方が良さそうですね

> > これ最悪ですね　一番面倒な問題だと思います
> 
> pythonをいろいろいじったら全部\n出力にはできたんですけどtestlibがWindows上では\r\n以外認めてくれないのでまたいろいろいじってverifierへの入力もWindows上では\r\nにするようにする予定です

出力の方はよくわかっていないんですが、MinGWで普通にprintf("Hello\n")とやると"\r\n"と"\n"のどっちが出てくるんでしょうか

verifierの方ですが、readEolnの挙動が環境依存なのが最悪という気がするので、readEolnをreadChar('\n')にしてしまうのがいい気がしています(これは機械的に置換できるのでそんなに大変ではない気がする)

**Comment by yosupo06** [comment]
windowsという名前のブランチを用意しました、ここだとgithub actionsがwindowsのテストもするようになっている(当然今はテスト落ちる)ので、このブランチをmergeしてからpull requestを送っていただけるとwindowsで動くかテストできると思います(多分)

**Comment by windows-server-2003** [comment]
出力は少なくともPythonのsubprocessで受け取ると\r\nになって出てきます

その他了解しました
