### ISSUE TITLE
[問題案] Associative Array

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#376]
(任意) 問題ID: {ID}
問題名: {名前}

想定アルゴリズム: map<int, int>

# 問題概要

map<int, int> mpを持っている。Q個のクエリを処理。

- `1 x y` : mp[x] = y
- `2 x` : print mp[x]

## 制約

Q <= 1,000,000? 500,000?

ハッシュテーブルを自作したり、unordered_mapの悪質度を計測したり

**Comment by cai-lw** [comment]
`unordered_map_killer` doesn't seem to be killing anything. My submission using `unordered_map` runs on these cases just as fast as on random cases. https://judge.yosupo.jp/submission/59102

**Comment by fairy-lettuce** [comment]
https://judge.yosupo.jp/hack/658
C# の `long` は上位・下位の 32 bit ずつの XOR がハッシュになるため非常に衝突しやすい
