### ISSUE TITLE
[問題案]Assignment Problem(assignment)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#38]

**Comment by yosupo06** [comment]
最悪ケースがない

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/submission/3784

**Comment by beet-aizu** [comment]
Capacity Scaling で O(N^4 log N) が通ってしまいました https://judge.yosupo.jp/submission/24228
全く詳しくないんですが最悪ケースが作れたりしますか

**Comment by beet-aizu** [comment]
> Capacity Scaling で O(N^4 log N) が通ってしまいました https://judge.yosupo.jp/submission/24228
ちゃんと見積もったらO(N^3 log N) でした　お騒がせしました

**Comment by adamant-pwn** [comment]
It would be cool if there is an anti-SPFA test too...
