### ISSUE TITLE
[問題案] Sum of Totient Function

### ISSUE THREAD

**Issue by Maruoka842** [yosupo06/library-checker-problems#384]
(任意) 問題ID: {sum_of_totient_function}
問題名: {Sum of Totient Function}

# 問題概要
オイラーのトーティエント関数の和\sum_{i=1}^N \phi(i)を998244353で割った余りを求めてください。

## 入力

```
N
```

## 出力

```
\sum_{i=1}^N \phi(i) \bmod 998244353
```

## 制約

1 \leq N \leq 10^10

TL: 5sec

**Comment by yosupo06** [comment]
想定計算量はO(N^{2/3})ですか？(昔どこかで聞いた気がするんですが、自信がないです)

良さそうに思えます

**Comment by Maruoka842** [comment]
O(N^(2/3))もある( https://min-25.hatenablog.com/entry/2018/11/11/172216 )のですが、O(N^(2/3+eps)) ( https://yukicoder.me/wiki/sum_totient ) が想定です。

**Comment by yosupo06** [comment]
良さそうです
