### ISSUE TITLE
[問題案] Pow of Formal Power Series

### ISSUE THREAD

**Issue by Maruoka842** [yosupo06/library-checker-problems#386]
https://github.com/yosupo06/library-checker-problems/issues/88#issuecomment-569512865

問題ID: {pow_of_formal_power_series}
問題名: {Pow of Formal Power Series}

# 問題概要
f(x):=\sum_{i=0}^{N-1} a_i x^iとします。
f(x)^M \bmod x^{N}を998244353で割った余り\sum_{i=0}^{N-1} b_ix^iを求めてください。

## 入力

```
n
t
s_1
s_2
\vdots
s_n
```

## 出力
```
b_0 b_1 \dots b_{N-1}
```

## 制約
```
1 \leq N \leq 500000
0 \leq a_i < 998244353
1 \leq M \leq 10^9
```

**Comment by yosupo06** [comment]
良さそうに思えます

**Comment by yosupo06** [comment]
入力形式は、
```
N M
a_0 a_1 ...
```
とかかな

**Comment by Maruoka842** [comment]
・Mに負整数は含めたほうが良いでしょうか？
・Mに有理数を含めたほうが良いでしょうか？

**Comment by Maruoka842** [comment]
・Mに負整数を含めたほうが良いでしょうか？
・Mに有理数を含めたほうが良いでしょうか？

**Comment by yosupo06** [comment]
(正整数以外だとちゃんと定義できるのかすらあまり知らないんですが)個人的にはいらないとおもいます

**Comment by Maruoka842** [comment]
了解です～（sqrtと同じように定義します）

**Comment by Maruoka842** [comment]
乗法群の位数はp(p-1)まで取り得るのでM≦1e19でもよいかもしれません。

**Comment by maspypy** [comment]
ちなみに有理数 M に対する f(x)^M は、普通は定数項が 1 を仮定した上で定義しますね。

**Comment by yosupo06** [comment]
実はダブリングでやる方じゃない方(log, exp)をあんまりわかってないんですが、Mが整数でも定数項が1じゃないと壊れたりするでしょうか？

**Comment by maspypy** [comment]
log は定数項=1、exp は定数項=0、となるものに対して定義され、 f^M = exp(M log f) となる f も当然定数項が 1 のものに限られます（それ以外は定義の時点で壊れます）。
(2x+3x^2)^3 = 8x^3 * (1 + (3/2)x)^3
のように式変形すれば、定数項が 1 のものに帰着できますね。

**Comment by hos-lyric** [comment]
correct.cpp がオーバーフローでこわれます

input
```
7 715827883
0 0 0 0 0 0 1
```

expected
```
0 0 0 0 0 0 0
```

actual
```
0 0 1 0 0 0 0
```

これ以外にテストケースが弱いポイントがあるとすると，
M mod 998244353 をとってしまうやつ ((定数項が 1 のやつ)^(有理数) の場合はそれでいいけどこの問題だとダメ)
が現状通ってもおかしくなさそうに見えます (確認していません)

この辺もあるしオーバーフロー回りもあるしなので制約は 0 <= M <= 10^18 がいいなぁと思ったのですが，問題追加後のこの手の変更がどのくらいいいのかわかりません (0 を入れたり 10^18 までにしたりはそれぞれ今ある提出に実際にそこそこ影響があると思います)

**Comment by maspypy** [comment]
制約の破壊的変更が行われました。（$[1, 10^9]$ → $[0, 10^{18}]$）
リジャッジで AC ではなくなった方は、 $M=0$ や、$M$ が巨大な場合の実装を確認してください。
