### ISSUE TITLE
[問題案] Inv of Polynomial

### ISSUE THREAD

**Issue by Maruoka842** [yosupo06/library-checker-problems#387]
問題ID: {inv_of_polynomial}
問題名: {Inv of Polynomial}

参考資料: 
{ http://people.csail.mit.edu/madhu/ST12/scribe/lect06.pdf }
{ https://dl.acm.org/doi/10.1145/800125.804045 }

# 問題概要

互いに素な多項式f(x):=\sum_{i=0}^{N-1} a_ix^iとg(x):=\sum_{i=0}^{N-1} b_ix^iが与えられる。
f(x)h(x) \equiv 1 \bmod g(x)
なるh(x)を998244353で割った余り\sum_{i=0}^{N-1} c_ix^iを
求めよ。

## 入力

```
N
a_0 a_1 \dots a_{N-1}
b_0 b_1 \dots b_{N-1}
```

## 出力

```
c_0 c_1 \dots c_{N-1}
```

## 制約
1 \leq N \leq 100000
0 \leq a_i < 998244353
0 \leq b_i < 998244353

**Comment by yosupo06** [comment]
これが出来るということを全然知らなかったんで、参考資料を、読みます…

**Comment by Maruoka842** [comment]
計測してみました。私の実装だとN=1e5で9s、N=5e4で4sでした。
N=5e4で出題しても良いでしょうか？

**Comment by Maruoka842** [comment]
・FPSではなくて多項式なので、a_{N - 1} != 0, b_{M - 1} != 0
・h(x)が存在するために a_{0} !=0 , b_{0} != 0

**Comment by Maruoka842** [comment]
【ゆる募】愚直な割り算を使ったHGCDを落とす abnormal remainder sequence のテストケース

**Comment by Maruoka842** [comment]
愚直な割り算を使った HGCD を落とす abnormal remainder sequence のテストケースが欲しいのですが、作り方が分かっていません。

**Comment by hly1204** [comment]
> 愚直な割り算を使った half-GCD を落とす abnormal remainder sequence のテストケースが欲しいのですが、作り方が分かっていません。

Maybe we could do this in a "reverse" way of doing the extended Euclidean algorithm. I have made such cases in this way.

(a, b)->(b, a mod b) (normal way)
(a + b * r, b)<-(b, a) (reverse way)
r is a random polynomial we generated. Let deg(r) > 1 then the remainder sequence could be abnormal? Am I right?

**Comment by koba-e964** [comment]
日本語版の問題文に制約が書かれていないように見えます (英語版には書いてあります)
