### ISSUE TITLE
[問題案] Counting Primes

### ISSUE THREAD

**Issue by Maruoka842** [yosupo06/library-checker-problems#388]
問題ID: {couting_primes}
問題名: {Counting Primes}

想定アルゴリズム: { Meissel–Lehmer algorithm }
参考資料: { http://sugarknri.hatenablog.com/entry/2019/07/31/102422 、https://min-25.hatenablog.com/entry/2018/11/11/172216 }

# 問題概要

N以下の素数の個数を求めてください。

## 入力

```
N
```

## 制約
1 \leq N \leq 10^10

## 懸案
制約はどのぐらいがいいでしょうか。
参考：https://github.com/kimwalisch/primecount

--

**Comment by yosupo06** [comment]
制約は参考URLのBenchmarksだけを見ると10^13あたりが良さそうに思えるんですが、これは多分相当最適化されてそうですね…　素朴なO(N^{2/3} polylog(N))の実装がAC可能(=10sには入ってほしい)です

良さそうに思えます

**Comment by tko919** [comment]
N=10^11でMeissel-Lehmerが1074ms,LMOが755msだったので、TLはそのままで制約を10^11に引き上げたいです(アルゴリズムの速度差が顕著になると思うので)

**Comment by yosupo06** [comment]
はい いいと思います
