### ISSUE TITLE
[問題案] Static Range Sum

### ISSUE THREAD

**Issue by tsutaj** [yosupo06/library-checker-problems#398]
(任意) 問題 ID: {static_cumulative_sum}
問題名: {Static Cumulative Sum}

# 問題概要

長さ N の数列 A = (a_1, a_2, \ldots, a_N) が与えられるので、以下のクエリを Q 回処理せよ。

- 整数 l, r (l \leq r) が与えられるので、\sum_{i=l}^{r} a_i を答える。

## 入力

```
N Q
a_1 a_2 ... a_N
l_1 r_1
...
l_Q r_Q
```

## 出力

答えを Q 行で出力

## 制約
- 1 \leq N \leq 5 \times 10^5
- 1 \leq Q \leq 5 \times 10^5
- 0 \leq |a_i| leq 10^9 (1 \leq i \leq N)
- 1 \leq l_i \leq r_i \leq N (1 \leq i \leq Q)

## 検討事項
1. この問題が必要であるか
    - 単に演算を累積して行うだけの問題が見た感じ Static RMQ 以外なさそうで、Static RMQ は逆元が存在しないのに対してこちらは逆元が存在するので書きましたが、既存の問題でこの問題を要求するものがすでにありましたら教えてください。
1. どのような演算にするか
    - 逆元が存在するようなものがいいかなと思います (ないものは Static RMQ で verify できそう？)

**Comment by yosupo06** [comment]
ありがとうございます！

目的は多分累積和ライブラリだと思うので、それを前提にしてコメントします

> 1. この問題が必要であるか

(私はしていませんが)累積和をライブラリ化している人というのは一定数居るようなので、いいと思います

> 2. どのような演算にするか

非可換性を無視したいなら整数のsum、チェックしたいなら一次関数だと思います。　普通の累積和のチェックをしたいなら前者の方がいいかなと思います(後者もあっていいと思います)。

> 問題ID

Static Range Sumがいいと思います(もういろんなところが崩壊しているんですが、一応近い問題との統一を保とうという思想があります)

> * 整数 l, r (l \leq r) が与えられるので、\sum_{i=l}^{r} a_i を答える。

(制約を見るにこっちのミスだと思うんですが)半開区間でお願いします

**Comment by yosupo06** [comment]
あ、あと値の範囲は負を入れたい特別な理由がないなら0 <= a_i <= 10^9の方がいいです(これも統一感の話です)

**Comment by tsutaj** [comment]
- 問題タイトル: Static Range Sum
- クエリは sum、 0-indexed 半開区間にする
- 値は非負整数
Static RMQ などと統一する形で、データセット等作ってみます。

一次関数 (affine?) についてなんですが、非可換性が求められ、かつ数列のどちらの端も含まないような区間に関するクエリが与えられたとき、累積和と同じアプローチって使えますか？(しばらく考えましたが、わかりませんでした・・・) (他のデータ構造の Verify にはできると思いました)

**Comment by yosupo06** [comment]
見逃してました、



> 一次関数 (affine?) についてなんですが、非可換性が求められ、かつ数列のどちらの端も含まないような区間に関するクエリが与えられたとき、累積和と同じアプローチって使えますか？(しばらく考えましたが、わかりませんでした・・・) (他のデータ構造の Verify にはできると思いました)

一般には使えないんですが、逆関数を持つ一次関数f(x) = ax + b, (a != 0)ならば何とかなります
f1 f2 f3 f4の合成は(f1 f2の合成)の逆関数と(f3 f4の合成)の合成
