### ISSUE TITLE
[問題案] GCD of Polynomials

### ISSUE THREAD

**Issue by Maruoka842** [yosupo06/library-checker-problems#407]
(任意) 問題ID: {gcd_of_polynomials}
問題名: {gcd_of_polynomials}

(任意) 想定アルゴリズム: {half-GCD}
(任意) 参考資料: { https://dl.acm.org/doi/10.1145/800125.804045 }

# 問題概要

2つの多項式f(x):=\sum_{i=0}^{N-1} a_ix^iとg(x):=\sum_{i=0}^{N-1} b_ix^iが与えられる。
gcd(f(x),h(x))を998244353で割った余り\sum_{i=0}^{N-1} c_ix^iを求めよ。

## 入力

```
N
a_0 a_1 \dots a_{N-1}
b_0 b_1 \dots b_{N-1}
```

## 出力

```
c_0 c_1 \dots c_{N-1}
```

## 制約
1 \leq N \leq 100000
0 \leq a_i < 998244353
0 \leq b_i < 998244353

O(N log^2 N) 想定です。速度は計測しないと分かりません。g(x)^{-1} mod f(x) を出題するのならば、GCDを先に出題するべきではと思い、追加しました。

**Comment by yosupo06** [comment]
え、多項式のGCDってO(N^2)切れるんですか　知らなかったです

**Comment by Maruoka842** [comment]
体係数の多項式のGCDは定数倍してもまたGCDなので、GCDのうちモニック多項式を出力せよが要りますね。

**Comment by yosupo06** [comment]
これはFPSではなくて多項式なので、
```
N M
a_0 a_1 ... a_{N - 1}
b_0 b_1 ... b_{M - 1}
```

で、a_{N - 1} != 0, b_{M - 1} != 0の方が良いです

**Comment by Maruoka842** [comment]
了解です。
