### ISSUE TITLE
[問題案]Convolution(convolution_mod)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#42]

**Comment by kmyk** [comment]
#3 でも触れられていますが、これの mod 1000000007 版や任意 mod 版がほしいです。mod 1000000007 なら単に制約を変更するだけなのでやってプルリクにしようと思うのですが、よさそうですか？ 
(ところでこれは別の issue にするべき？)

**Comment by yosupo06** [comment]
mod 998244353を一般modとして見ればベリファイは可能(なのでmod 1,000,000,007をわざわざ足すことはしない)　というポリシーだったんですが、convolutionの需要は高そうなので足していい気がしてきました

**Comment by yosupo06** [comment]
#145 個別のissueを作りました

**Comment by maspypy** [comment]
fastest solution
https://codeforces.com/blog/entry/142063
