### ISSUE TITLE
問題製作者用オプション

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#432]
#333 

現状ではgenerate.pyのオプションがわかりにくい　多すぎるし複数指定したときの挙動が内部を読まないと分からない

```
./generate.py sample/aplusb/info.toml --dev
```

のように新しいオプションを作って(まだ増やすのかという感じだが)、作問者はこのコマンドを指定するだけで全てうまくいくようにする

具体的にこのコマンドの効果は

- キャッシュ系の無効化
- `--verify`と同等の効果(verifierを走らせる, other solutionsを走らせる)
- `--html`と同等の効果(htmlを出力する)
- `--refhash`と同等の効果(hash.jsonを上書きする、ただし上書きしたら警告を出す)
- health_checkで重大で無いもの(このサンプルをtask.mdで使ってない、genの下に使ってないファイルがある、…)は警告を出すだけでそのまま続ける

この後さらに機能が追加されたとしても作問者は`--dev`以外は意識しなくても作問できるようにする。これがオプションを新設するメリット

**Comment by yosupo06** [comment]
もう少し考えた 無印, `--dev`, `--test` の3つだけにするのはどうだろう(今まであったオプションは消さずに取っておくが、推奨する用途はこの3つ)

- 無印(`./generate.py sample/aplusb/info.toml`) テストケースを見たいと言うユーザー向き
- dev(`./generate.py sample/aplusb/info.toml --dev`) 作問者向き
- test(`./generate.py sample/aplusb/info.toml --test`) 作問者の最終チェック, CI向き

|  | 無印  | `--dev` | `--test` |
| --- | --- | --- | ----|
| ケース生成  | キャッシュする  | キャッシュしない | キャッシュしない |
| verifier  | しない | する | する |
| hash | チェックする | (警告付き)上書きする | チェックする |
| checker | コンパイルする | コンパイルする | コンパイルする |
| other-sol | 無視 | チェックする | チェックする |
| warning | 落とす | 出力のみ | 落とす |
| html | 生成しない | 生成する | 生成する |

**Comment by yosupo06** [comment]
問題文を微調整したいときに不便なことが、発覚…(無印でhtml生成すればいいのでは？)

**Comment by Maruoka842** [comment]
other solutionsの走らせ方ってどこかにありますか？

**Comment by yosupo06** [comment]
--devか--testをつけると走るはずです

**Comment by Maruoka842** [comment]
想定解をどこに置いたらいいか分からないです（solにおいても動かなかったため）。

**Comment by yosupo06** [comment]
- 想定解は `sol/correct.cpp` という名前でおいてください
- それ以外の解答は `sol/hoge.cpp` みたいにおいて、https://github.com/yosupo06/library-checker-problems/blob/master/sample/aplusb/info.toml ここを参考にinfo.tomlを変更してください
- `./generate.py sample/aplusb/info.toml --dev` と実行してみてください

これでダメだったら、具体的にログを貼っていただけると助かります
