### ISSUE TITLE
[問題案]Determinant of Sparse Matrix(sparse_matrix_det)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#44]

**Comment by yosupo06** [comment]
問題文

- (a, b)がdisjoint
- 非0と描いているのにc = 0とはなんぞや

**Comment by bqi343** [comment]
Oops, looks like [this solution](https://old.yosupo.jp/submission/11017) passes despite running into an infinite loop on the following test case:

```
2 2
0 0 1
1 1 1
```

**Comment by heno239** [comment]
testcaseに
M(0,i),M(i,0),M(i,i) (0<=i<N)
が非0になるものがある方がよさそうです
(普通の行列式で0の部分を飛ばすように実装すると通ってしまいましたが、上記のケースでしっかり遅いO(N^3)になりました https://judge.yosupo.jp/submission/82069)
