### ISSUE TITLE
提出されたコードの権利・ライセンス関係

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#458]
Library Checker に提出されたコードの権利まわりについて少々不安を抱えています．
ちゃんとした記載が面倒というのはとてもわかるのですが，ちゃんとした記載があると助かります．

わたしはライセンスに関して詳しくなく，適切な案の提示ができず申し訳ないです．
ここを議場にして詳しい人に意見を出してもらえると……．
気持ちとしては，提出者以外の権利が制限される方向にはっきりするのは構わないと思っています．

--

現実的な話 (1)

提出されたコードを，許可をとらず単にコピペしてプログラミングコンテストに使用している人がいる，という噂をよく目にします (糾弾する意図ではありません)．現状この行為の適法性もよくわからないのですが，例えばお金が絡んでくると面倒が生じる可能性はあるような気がしています．

提出者としては，ちゃんとした記載がないまま何かされうるというのは不安があります．

(個人的には，最低限出典 (提出ページの URL など？) を記載してやっとグレーゾーン，という感覚があります．本当はそのような目安も何かがあると安心です)

--

現実的な話 (2)

提出されたコードを，問題作成に使う (つまり，このリポジトリに置く) というのは，割とありうることで有益かなと思っています．ただしこれはできなくてもそこまで困りません．

**Comment by yosupo06** [comment]
現状のライセンス周りの状態をまとめて書きます

- 私はライセンス(や、著作権周りの法律)に詳しくないです(OSSやってるのにどうなんだ)

- このリポジトリ、及びlibrary-checker-judge, frontendのコードは一部(testlibなど)を除きApache-2.0で公開しています。本当は各ファイルのヘッダにもこれを載せるべきですが、mustではないはずなので問題はないはずです(以下 https://infra.apache.org/apply-license.html より引用)

> Each original source document (code and documentation, but not the LICENSE and NOTICE files) should include a short license header at the top.

- 提出ファイルに関してのライセンスを一切明記していません。この結果、どう使っていいか謎　という状態になるわけではないと認識してます。具体的には https://choosealicense.com/no-permission/ が参考になると思いますが、普通に著作権で保護されるはずです。短いコードなのでどうなのか、という話もあったと思いますが、ユーザーとしては先述のURLを意識しておけば問題はないはずです。

**Comment by yosupo06** [comment]
> 現実的な話 (1)
> 
> 提出されたコードを，許可をとらず単にコピペしてプログラミングコンテストに使用している人がいる，という噂をよく目にします (糾弾する意図ではありません)．現状この行為の適法性もよくわからないのですが，例えばお金が絡んでくると面倒が生じる可能性はあるような気がしています．

Library Checkerのコードを盗用することが適法でなかったとして(ちなみに私の認識ではアウトです)、それをやった人間が悪いのであり、Library Checkerに非はないと思っています。もちろん盗用がダメだと明記した方が親切だという議論の余地は残ります。

> 現実的な話 (2)
> 
> 提出されたコードを，問題作成に使う (つまり，このリポジトリに置く) というのは，割とありうることで有益かなと思っています．ただしこれはできなくてもそこまで困りません．

多分勝手に嘘解法をリポジトリに登録してケースを強化するという話だと思うんですが、個人的には自主的に協力して欲しいな〜と思っています

**Comment by kmyk** [comment]
提出ファイルに関してのライセンスの問題は 2 通りあります。(1.)  提出されたコードを利用したいユーザの権利と、(2.) コードを提出するユーザの権利です。

(1.) の提出されたコードを利用したいユーザの権利については、現状は勝手な利用が禁止されており、「普通に著作権で保護されるはず」という認識で正しいはずです。

(2.) のコードを提出するユーザの権利が問題です。これが書かれていないと、たとえば AtCoder の[ヤマトコン](https://atcoder.jp/contests/kuronekoyamato-contest2019) ([コンテスト受付開始について - chokudaiのブログ](http://chokudai.hatenablog.com/entry/2019/07/24/130248)) のように、「提出されたコードの権利はすべて運営に移る」という可能性が残ります。実際に問題が起きることはないはずですが、権利関係をきっちりやりたい人 (あるいは権利関係をきっちりやりたい会社に雇用されてる労働者) が提出できなくなって困ります。

**Comment by yosupo06** [comment]
以上の話をまとめると、まあライセンスを明記した方が親切という話はあれど、メリットは薄いと考えています。

そして一方で、これ関連の話は調べると無限にMPが削れるというデメリットがあります。正直私はここら辺の話に触れたくないですし、触れると無限に疲れます。

よって圧倒的にメリット <<< デメリット なので触れる理由がなく、放置されている　というのが現状です

**Comment by yosupo06** [comment]
> (2.) のコードを提出するユーザの権利が問題です。これが書かれていないと、たとえば AtCoder の[ヤマトコン](https://atcoder.jp/contests/kuronekoyamato-contest2019) ([コンテスト受付開始について - chokudaiのブログ](http://chokudai.hatenablog.com/entry/2019/07/24/130248)) のように、「提出されたコードの権利はすべて運営に移る」という可能性が残ります。実際に問題が起きることはないはずですが、権利関係をきっちりやりたい人 (あるいは権利関係をきっちりやりたい会社に雇用されてる労働者) が提出できなくなって困ります。

明記していない以上著作権は一切Library-Checkerに移らないものだと思ってたんですが、これは完全な思い込みで、サイトで公開している以上何らかの権利は移ってる(or LibraryCheckerが侵害している)のかな…

**Comment by yosupo06** [comment]
> 権利関係をきっちりやりたい人 (あるいは権利関係をきっちりやりたい会社に雇用されてる労働者) が提出できなくなって困ります。

これに関しては該当者がいるのか、該当者はどのぐらいきっちりしていれば満足なのかが謎で、何とも判断できません。もしライセンスを気にしている人がいるなら、privateな方法でもいいので伝えてくれると助かります。

**Comment by yosupo06** [comment]
とりあえず週末で(2.)について調べます…

**Comment by kmyk** [comment]
> サイトで公開している以上何らかの権利は移ってる(or LibraryCheckerが侵害している)のかな…

おそらくいくらかの権利は移って (あるいは、運営側に付与されて) います。「提出されたコードをインターネット上へ公開すること」は提出者の同意がないとできないためです。
(権利の侵害とは言えないはずです。提出されたコードが公開されることを事前に知ることができ、ユーザはそれを理解した上で提出しているので、暗黙に同意があると解釈して妥当なはずなので (たぶん))

近い例: GitHub にライセンスなしで公開しても、いくつかの最低限の操作 (fork するなど) は許可される ([リポジトリのライセンス - GitHub ヘルプ](https://help.github.com/ja/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license))

**Comment by yosupo06** [comment]
はい　とりあえずgithub gistを参考にすると最低限のことがわかるかも

**Comment by yosupo06** [comment]
わかる？整う

**Comment by yosupo06** [comment]
とりあえず様々なサイトについて雑に調べました

AtCoder (https://atcoder.jp/tos), AtCoder企業マラソン (https://atcoder.jp/posts/384), TopProver (https://top-prover.top/tos), GCJ (https://codingcompetitions.withgoogle.com/codejam/rulesandterms)

など、基本的には

- 所有権, 著作権は提出者が所有する
- 運営(+企業マラソンなら企業)に幾らかの権利を許諾する
- ソースコードをどのようなライセンスで公開するか(=第三者のユーザーにどのぐらいの権利を許諾するか)は無記載

と言うのが基本のスタイルに見えます。どのぐらいの権利を許諾するかはサイトごとに差があります(AtCoder企業マラソンやGCJはかなり強力な権利に思える)

今のところ見つけた例外は、

Github (https://help.github.com/en/github/site-policy/github-terms-of-service#a-definitions)

- 他のgithub userに対するforkで複製可能とかの権利を認めている

yukicoder (https://yukicoder.me/)

- 提出は全て Apache License 2.0 で公開している
- 著作権を提出者が持つか、どのぐらいの権利を提出者がyukicoderに認めているかなどは記載がなさそう？

と言う感じです

**Comment by yosupo06** [comment]
https://codingcompetitions.withgoogle.com/codejam/rulesandterms より引用

> you grant Google a non-exclusive, worldwide, perpetual, irrevocable, free license (with the right to sublicense) to reproduce, prepare derivative works of, distribute, publicly perform, publicly display, and otherwise use such submission

https://www.facebook.com/hackercup/terms より引用

> Competitors agree that Facebook shall have a perpetual, irrevocable, world-wide, royalty-free, transferable, sublicenseable right to use, copy, distribute, modify and make publicly available the Submission

**Comment by yosupo06** [comment]
このリポジトリに提出を輸入する方針は、提出時に少なくとも再配布が可能なライセンスでの公開を強制するということなので厳しと思ってたんですが、yukicoderがやってるなら行けるのか…？

**Comment by kmyk** [comment]
提出を輸入するのは厳しそうで、個別に許可を取るのがよさそう。
yukicoder の規約は、あまり注意深くには書かれてなさそうだし、まねるのはやめておいた方がよさそうに思います。

**Comment by yosupo06** [comment]
細かいところは後で考えるにしろ、大まかに今考えてる方針は

- 規約: 今の状態=著作権等は提出者に帰属するがサービス運営のために幾らかを認める　を明文化するだけ

- 第三者の使用: 提出者個人のライブラリへの動線を整備して(e.g. ユーザープロフィールにライブラリ集へのリンクを登録できるようにする)、そちらで適切なライセンスと共に公開してもらう形

を考えています。

- kmykさんの言う通り提出になんらかのライセンスを付与とかはめんどくさそう
- ジャッジ上だけで完結するのではなく、githubとかそういう現代的(？)な物を広めたいという思想がそういえばあり

**Comment by kmyk** [comment]
G社が利用規約のテンプレを用意してくれてたので、これを借りればよさそう。競プロでなくてハッカソン用だけど知的財産権まわりはどちらも同じなので気にしなくてよい。内容もちょうど「著作権等は提出者に帰属するがサービス運営のために幾らかを認める」になってくれてます。
https://opensource.google/docs/hackathons/#modelterms

"Short-form hackathon terms" と "Long-form hackathon terms" があって、選べるようになってます。short-form の方でも長いと思うなら、次のように、2 段落目そのままと 3 段落目の要約だけあれば十分なはず (たぶん)。

- > Entrants retain ownership of all intellectual and industrial property rights (including moral rights) in and to Submissions.
- As a condition of submission, Entrant grants the organizer a license to use and publicly display the Submission.

**Comment by yosupo06** [comment]
<img width="1213" alt="スクリーンショット 2020-05-12 20 11 05" src="https://user-images.githubusercontent.com/7629145/81679586-49579e80-948d-11ea-90e5-b3182c46f411.png">

うっかりコードを既にmasterにmergeしてしまい、今トラフィックをいじって見えないようにしているんですが(…)、こういう規約を足そうと思っています

Backupとかはするのでreproduceとか必要じゃないか？と考えた結果めんどくさくなったので全部入れです

**Comment by kmyk** [comment]
そのあたりを全部入れするなら、いっそ元々の "Short-form hackathon terms" の残りの部分も全部入れるのも検討してみてほしい。
謎単語が増えて規約が理解しにくくなってる (「publish と distribute と publicly display の違いってなに？」とか正直よく分からない) し、それならいっそ「G社のおすすめのやつそのままです」になってる方が理解しやすいはずので。

**Comment by yosupo06** [comment]
> 「publish と distribute と publicly display の違いってなに？」とか正直よく分からない

よくわからないので全部入れたみたいなところがあります(こういう細かい言い回しが英語で要求されると、終了…)

**Comment by yosupo06** [comment]
検討しましたが、第一段落は(謎単語と関係のない)用語定義、第四段落はハッカソン向けという感じで入れてもなあって感じです。

Long termの方読んでもそれぞれが何なのかはよくわからないので、ここの細かいニュアンスを読み取るのは諦めました。

↑の画像だと分かりませんが、Google Open Source Docsがリンクになってるんで大丈夫じゃないかなって思ってます

**Comment by yosupo06** [comment]
(全部入れようとしてもハッカソン向けのところが多くて「G社のおすすめのやつそのままです」と言えるような形にはならない気がする)

**Comment by yosupo06** [comment]
Entrantsもなんか変な気がしてきたので、Usersに変更したい

**Comment by kmyk** [comment]
そういうことなら画像で貼ってもらったやつを使う方がよさそうです

(ところで第四段落の内容ですが、ハッカソン向けってどういうことだと思って読みなおしたら、私がかなり勘違いしてしてたことが判明しました)

**Comment by yosupo06** [comment]
公開しました

**Comment by kmyk** [comment]
ありがとうございます

**Comment by hos-lyric** [comment]
ありがとうございます！
