### ISSUE TITLE
[問題案] Tree Diameter

### ISSUE THREAD

**Issue by monkukui** [yosupo06/library-checker-problems#465]
問題ID: {tree_diameter}
問題名: {Tree Diameter}
想定アルゴリズム: {DFS を 2 回するやつです}

# 問題概要
$N$ 頂点の重みなし無向木が与えられる．$i$ 番目の辺は，頂点 $a_i$ と頂点 $b_i$ を双方向につなぐ．

最遠頂点対 $(u, v)$ を一つ出力せよ．また，$(u, v)$ 間の距離を出力せよ．

## 入力

```
$N$
$a_0$ $b_0$
$a_1$ $b_1$
$\dots$
$a_{n - 2}$ $b_{n - 2}$
```

## 出力

以下の形式で出力せよ．
```
$u$ $v$
$d$
```
$(u, v)$ は，最遠頂点対を表し，$d$ は $(u, v)$ 間の距離を表す．
なお，正しい解が複数存在する場合は，どれを出力しても構わない．

## 制約
- 入力は全て整数である
- 与えられる入力は木である
- $2 \leq N \leq 500,000$
- $0 \leq a_i \leq b_i \leq N - 1$

## 検討事項
- この問題は必要かどうか？
- 重み付き木にしてもいいかもしれない
- 構築は必要か？（単に，直径だけ出力でもいいかも）

## 補足
初 issue です．よろしくお願いします．
問題作成やテストケース作成など，全てコミコミで commit してみたいなと思い，issue 立ててみました．

**Comment by yosupo06** [comment]
ありがとうございます

> * この問題は必要かどうか？

直径を求めるのはありがちだし微妙に実装がダルいので、全然ありです

> * 重み付き木にしてもいいかもしれない

もし自分のライブラリをベリファイするためにこの問題を追加したい場合、どちらでも必要なほうで良いです

特にそういう感じではないなら、個人的には重み付きの方を推しておきます

> * 構築は必要か？（単に，直径だけ出力でもいいかも）

基本的に構築は可能な限りさせます。もっというと、個人的には直径のパス全部復元させていいと思っています

重みなしの場合

```
$X$
$u$ $p$ ... $v$
```
(X: 直径のパスの頂点数 = 次の行の出力の数)

重みありの場合
```
$X$ $Y$
$u$ $p$ ... $v$
```
(X: パスの長さ, Y: パスの頂点数 = 次の行の出力の数)

がいいです

**Comment by monkukui** [comment]
回答ありがとうございます．
> 直径を求めるのはありがちだし微妙に実装がダルいので、全然ありです

ありがとうございます．作問に取りかかれそうで嬉しいです．

> 特にそういう感じではないなら、個人的には重み付きの方を推しておきます

重み付きにしましょう．

> 基本的に構築は可能な限りさせます。もっというと、個人的には直径のパス全部復元させていいと思っています

パスを復元させる方向でいきましょう．出力形式も上に従います．

**Comment by monkukui** [comment]
verifire でベリファイすること

- 値が制約の範囲内にあること
- 入力が木であること（閉路が無く，連結であること）

**Comment by monkukui** [comment]
checker でチェックすること
- Y が想定解と一致する
- 出力されたパスのサイズ = X 
- 出力されたノード間に辺が存在する
- 同じ頂点は二度通らない
- 実際のコストが Y と一致する
- その他余分な出力を含んでいない（`if (ouf.seekEof())`）

**Comment by yosupo06** [comment]
if (ouf.seekEof())はなくてもなんかチェックされます(testlibの謎)
