### ISSUE TITLE
[問題案] Hafnian of Matrix

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#467]
問題名: Hafnian of Matrix

想定アルゴリズム/参考資料
Björklund, A. (2012, January). Counting perfect matchings as fast as Ryser. In Proceedings of the twenty-third annual ACM-SIAM symposium on Discrete Algorithms (pp. 914-921). Society for Industrial and Applied Mathematics.

# 問題概要
n × n 行列のハフニアンを mod 9982443553 で出力

## 入力

```
```

## 出力

```
haf(A)
```

## 制約
N <= 32 ~ 38 程度？
方向が固まったら計測して決定するつもりです

## 検討事項
- 入力形式
    - 対角成分が 0 の対称行列を与える
    - (下 or 上) 三角の部分だけ与える
- https://github.com/yosupo06/library-checker-problems/issues/286
これをどうするか (別の問題としても良さそうに思っています)

**Comment by yosupo06** [comment]
ハフニアンを知らなかったんで調べたんですが、要するに(重み or 多重辺)ありの無向グラフの完全マッチングの個数ですね

**Comment by yosupo06** [comment]
- 入力形式 : 対角成分が0の対称行列でいいと思います　変に上三角だけ与えてもサンプルが見にくくなるだけそう

- #286 とりあえずどっちか作るならこっちだと思うので、放置でも
