### ISSUE TITLE
[問題案]K-th of Partition Function(partition_function)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#47]

**Comment by yosupo06** [comment]
K-th要素がどこにもないから名前をPartition Functionに変えるべき

**Comment by adamant-pwn** [comment]
Partition number $p(n)$ can generally be compute in $O(n^{1/2+o(1)})$ for a given $n$ ([link](https://arxiv.org/pdf/1205.5991.pdf)).
