### ISSUE TITLE
C++14 -> C++17

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#477]
需要があるならC++のバージョン上げてもいいかも

メリット

- 書きやすくなる

デメリット

- C++17に対応していないジャッジにこのリポジトリのコードが投げられなくなる
- C++17に対応してない古いコンパイラが動かなくなる　ユーザーがどのぐらいのコンパイラを使っているのか不明

**Comment by MiSawa** [comment]
個人的には, このリポジトリに入れるために C++14 まで戻したので, バージョンは高いほうが嬉しいです.

**Comment by yosupo06** [comment]
参考: https://gcc.gnu.org/projects/cxx-status.html
参考(ubuntu18): https://packages.ubuntu.com/bionic/gcc

"一般的"な環境で特別なことをせずに動く　を要件にしています

ubuntu16.04: 一応LTS範囲内、もういいかな…
ubuntu18.04: 平気そう
mac: 平気そう
windows: 自分が使わないため謎…

**Comment by yosupo06** [comment]
windowsで多分一般的なのはMsys2 + mingw-w64 / Cygwinで、どちらも大丈夫そうです

- http://mingw-w64.org/doku.php/download
- https://cygwin.com/packages/summary/gcc-g++.html

online-judge-verification-helperにも影響が行くはずなので確認を取ります @beet-aizu @kmyk どうですか　問題がなければあげます

**Comment by kmyk** [comment]
@yosupo06 verification-helper については大丈夫です。こちらの default の CXXFLAGS はすでに `-std=c++17` してるためです。

https://github.com/online-judge-tools/verification-helper/blob/bf6b3cc4b9636a5230d4b58ce73d03225eca04db/onlinejudge_verify/languages/cplusplus.py#L101

**Comment by yosupo06** [comment]
ありがとうございます！
