### ISSUE TITLE
[問題案] K-Shortest-Walk

### ISSUE THREAD

**Issue by hotman78** [yosupo06/library-checker-problems#509]
問題ID: k_shortest_walk
問題名: K-Shortest Walk

想定アルゴリズム: Eppstein's Algorithm
(任意) 参考資料: https://qiita.com/hotman78/items/42534a01c4bd05ed5e1e

# 問題概要
頂点数 N、辺数 M の単純とは限らないグラフが与えられる。i番目の辺は頂点a_iからb_iにはられており、重さc_iである。

頂点sから頂点tへの1番目からk番目に短いウォークの長さをそれぞれ出力してください。その様な経路が存在しない場合は-1を出力してください。

## 入力

```
~~~
N M K
s t
u_0 v_0 c_0
u_1 v_1 c_1
u_2 v_2 c_2
:
u_{M-1} v_{M-1} c_{M-1}
```

## 出力

```
i行目にi番目に小さいwalkを出力
```

## 制約
1 <= N, M <= 300000
1 <= K <= 300{,}000
0 <= s, t < N
0 <= u_i, v_i < N
0 <= c_i <= 10^9

**Comment by cai-lw** [comment]
Created PR to add English statement #693
