### ISSUE TITLE
[問題案] Dynamic Tree Subtree Add Subtree Sum

### ISSUE THREAD

**Issue by windows-server-2003** [yosupo06/library-checker-problems#521]
問題ID: dynamic_tree_subtree_add_subtree_sum
問題名: Dynamic Tree Subtree Add Subtree Sum

想定アルゴリズム: 部分木Link-cut treeをこねこねするとできた、Toptreeでもいい

# 問題概要
頂点重み付きのN頂点の木にクエリQ個
 - `0 u v w x` : cut u - v, link w - x
 - `1 v p x` : pを親としたときのv以下の部分木の頂点の重みにxを足す(pとvは辺で結ばれてる)
 - `2 v p` : pを親としたときのv以下の部分木の頂点の重みの和を求める(pとvは辺で結ばれてる)

## 入力
```
N Q
a_0 ... a_{N - 1}
u_0 v_0
...
u_{N - 2} v_{N - 2}
Query_0
...
Query_{Q - 1}
```

## 出力
```
...
```

## 制約
Q <= 200000
0 <= a_i <= 10^8 ? 10^9 ?
与えられるのは木
`0 u v w x` : uv間には辺がある、操作後も木
`1 v p x` : vp間には辺がある、0 <= x <= 10^8
`2 v p` : vp間には辺がある

ToptreeだとどうにでもなるけどLCTだと作用素可逆じゃないとダメ(可換はなくてもなんとかなると思う)
足す方の値は10^9にすると64bitから溢れて困る

**Comment by yosupo06** [comment]
見ました、あんまりギリギリを攻めても仕方がないので10^7にしておきましょう

**Comment by windows-server-2003** [comment]
うわ、これveriferにLink-cut tree, generatorにToptree案件か

**Comment by windows-server-2003** [comment]
- 2 <= N <= 200000

同種の問題は1 <= NだけどこれはN = 1だと1個もクエリ投げられないので

**Comment by hly1204** [comment]
I think Toptree can handle both path and subtree sum queries or even more, would you think about more operations or queries on tree?

**Comment by yosupo06** [comment]
Yes, Toptree can handle quite many queries. Of course, there is no reason to add problems that verify more strong functions of Toptree.

**Comment by LirichOfficial** [comment]
could you explain please what is Toptree?

**Comment by maspypy** [comment]
https://en.wikipedia.org/wiki/Top_tree
