### ISSUE TITLE
[機能案] 実行時間順ソート

### ISSUE THREAD

**Issue by ageprocpp** [yosupo06/library-checker-problems#527]
速い人の提出が見たいことがあるので,実行時間順にAC提出をソートする機能をつけてはどうでしょう,

**Comment by yosupo06** [comment]
実は機能としてはもうあったりします(Submission ListのIDというところをクリックすると)

issueが飛んできたということはわかりにくいということなので、`Sort: ID`とかにするといいかもしれないですね

**Comment by ageprocpp** [comment]
ありましたね、すみません（個人的には、AtCoder と仕様が違うのがわかりにくかったです。）

**Comment by tozangezan** [comment]
ソースコードが短い順があった方がいい気もします

**Comment by yosupo06** [comment]
ソースコードが短い順を使おうと思ったことがないんですが、欲しいものですか
