### ISSUE TITLE
[問題案] 閉路検出

### ISSUE THREAD

**Issue by tsutaj** [yosupo06/library-checker-problems#534]
問題ID: {cycle_detection}
問題名: {閉路検出}

想定アルゴリズム: {線形時間}
参考資料: {https://qiita.com/drken/items/a803d4fc4a727e02f7ba} (これのままだと任意始点におそらく対応できませんが、少し変えればできると思っています)

# 問題概要

$N$ 頂点 $M$ 辺のグラフが与えられます。このグラフにサイクルが含まれるならば、(どれでもよいので) サイクルを 1 つ出力してください。サイクルが含まれない場合は含まれないと報告してください。

## 入力

```
N M
u_0 v_0
u_1 v_1
...
u_{M-1} v_{M-1}
```

## 出力

存在する場合 (サイクルの長さを L とする)

${a_i}$ は頂点列のつもりです

```
YES
L
a_0 a_1 ... a_{L-1}
```

存在しない場合

```
NO
```

## 制約

- $1 \leq N \leq 5 \times 10^5$
- $1 \leq M \leq 5 \times 10^5$

## 相談事項

いくつか方針を決めたいです

- グラフは有向か？無向か？
- 辺は重みなしか？ありか？ (サイクルは何でもいいとしたいので重みなしでいいと思ってます)
- 出力させるのは本当に頂点列でよいのか

**Comment by yosupo06** [comment]
ありがとうございます！

> グラフは有向か？無向か？

どちらでも大丈夫です　決めあぐねているならば有向で

グラフを単純にするか、という話があって、単純じゃなくていいかなと思っています。

> 辺は重みなしか？ありか？ (サイクルは何でもいいとしたいので重みなしでいいと思ってます)

重みありの場合何を想像しているのでしょうか？たとえば最小重み閉路となると別の問題で、O(NM)くらいかかったはずです

> 出力させるのは本当に頂点列でよいのか

グラフを単純にするならば頂点列でいいです
単純にしないならば辺のID列がいいと思います

**Comment by tsutaj** [comment]
重みありの場合は最小のコストを持つ閉路を求めることを考えてましたが、指摘の通り O(NM) かかるので重みなしでいいかなと思いました。

グラフを単純にしない理由はなんでしょうか？より一般の状況で verify できる (さらにいうと他のジャッジで単純じゃない制約の問題が出て悲しいことにならずに済む) からでしょうか？

**Comment by tsutaj** [comment]
無向の閉路検出だと簡単になっちゃうので (単純グラフの場合、実質的にグラフが木であるかの判定問題になりそう・・・) 有向で用意します。

**Comment by yosupo06** [comment]
> グラフを単純にしない理由はなんでしょうか？より一般の状況で verify できる (さらにいうと他のジャッジで単純じゃない制約の問題が出て悲しいことにならずに済む) からでしょうか？

はい、「さらにいうと他のジャッジで単純じゃない制約の問題が出て悲しいことにならずに済む」が一番の理由です。

が、もちろん何を単純にして何を単純にしないか(とかn=0を入れるかとか)はとても微妙な話で、現状は僕の感性だったり雰囲気だったりになってしまっています。一応

> グラフは、(自明な変形(自己ループ削除 / 多重辺は重みの最大を1本残す)で答えが変わらない AND 単純じゃないと出力に不具合が生じる)時のみ単純

というポリシーは用意(https://github.com/yosupo06/library-checker-problems/blob/master/docs/style.md )しているんですが、これも厳密なものではないです

今回の問題の話をすると、こういうグラフに対してdfsで全域木を作る系(橋, 関節点, lowlink,...)はありがちな話として多重辺があると以下のコードが死にがち　というのがあるので、単純じゃないほうがいいかなと思いました

```
void dfs(int v, int prev_v) {
    for (int u: g[v]) {
        if (u == prev_v) continue;
        dfs(u);
    }
}
