### ISSUE TITLE
Could you please add determinant of matrix in real numbers? 

### ISSUE THREAD

**Issue by SamZhangQingChuan** [yosupo06/library-checker-problems#535]
(任意) 問題ID: {ID}
問題名: {名前}

(任意) 想定アルゴリズム: {名前}
(任意) 参考資料: {URL}

# 問題概要

## 入力

```
```

## 出力

```
```

**Comment by yosupo06** [comment]
In now, I don't plan to handle floating-point problems. I want to ensure the correctness of the model solution, but I don't know how to estimate the error of double.(Actually, I'm curious that how to handle the floating-point error in other online-judge/contest-site ...)
