### ISSUE TITLE
[問題案] nth terms of Formal Power Series

### ISSUE THREAD

**Issue by hotman78** [yosupo06/library-checker-problems#557]
(任意) 問題ID: Nth_Terms_of_fractional 
問題名: nth terms of Fractional Function
(任意) 参考資料: {http://q.c.titech.ac.jp/docs/progs/polynomial_division.html}

# 問題概要
[x^K]P(x)/Q(x) を998,244,353で割ったあまりを求めてください

## 入力

```
N M K
P_0 P_1 P_{N-1}
Q_0 Q_1 Q_{M-1}
```

## 出力

```
答えを一行に出力
```

## 制約
1 \leq N,M\leq 10^5
1 \leq K\leq 10^18
0 \leq P_i,Q_i < 998,244,353

**Comment by yosupo06** [comment]
https://github.com/yosupo06/library-checker-problems/issues/170 これと同じ問題でしょうか

**Comment by hos-lyric** [comment]
最初のほうの項 <-> 母関数の分子 の変換が自明な操作ではないので両方あってもいいとは思います

**Comment by yosupo06** [comment]
なるほど

多分(P(x)の非零の最小次数の項の次数) > (Q(x)の非零の最小次数の項の次数) という制約が必要そうですね 0 / 0 の扱いとかだるいので Q(x)の定数項 != 0でもいいと思います
