### ISSUE TITLE
generator.pyの並列化対応 / generator.pyの高速化

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#56]
#55 を解決するために必要不可欠

**Comment by yosupo06** [comment]
とりあえず放置 限界が来たら再open

**Comment by kmyk** [comment]
GitHub Actions での並列化を検討してるならついでにこっちもしたいです
(速度は 2 倍ぐらいにしかならないが、実装は楽かつ利用もオプション付けるだけで簡単なため。手元実行や verify-helper にも恩恵がある)

**Comment by kmyk** [comment]
@yosupo06 これやるとしたら仕様はどう考えてますか？

1. デフォルトで有効にするか、オプションで指定するか
   - 自動で使われてほしい気持ちはある。でも不安定になりがちだし常に CPU 100% はうれしくない気がする
   1. オプションで指定するならその名前は何か
       - make や GNU parallel などの `-j` `--jobs` 派が標準的だしこれに合わせておくと分かりやすそう。もちろん `--num-parallel` とかの選択肢もあります
1. 実装において、どこを並列化するか
   - 実装の手間を考えるとどこかひとつの for loop をN倍速にする感じになります。このとき (a.) 問題ごとに1スレッド割り当てるか、(b.) 問題は順番に処理してそのテストケースごとに1スレッド割り当てるか、のどちらかになりそう。(a.) だと手元で `-p` で指定したときに無力でうれしくない、(b.) だと並列化できない部分がでてきてアダマールの法則がすこし影響します。もちろん ad-hoc に (a.), (b.) 切り替えもできるが面倒

とりあえずの実装は `-j 2` みたいに指定してテストケースごと並列がよいと思ってます。

**Comment by yosupo06** [comment]
あまりやる気が起きていないです　手間に対して利点が薄いと考えているからです

ざっくり分けて(使用者側 / 開発側) * (CI / 手元)で4種類の用途があるはずで
(CIなどでの)使用者側としても、ケース生成がボトルネックになるというのがあまり出来ると開発側としても
並列化するとlogの出力順序や

**Comment by yosupo06** [comment]
これ会話に失敗していることに気づきました　やるとしたらの話だとkmykさんに同意します

- 問題並列 vs ケース並列: ケース並列でいいと思います(問題並列だといよいよ旨味がなくなるのでは？)
- `-j`だと他のオプションに対して1つだけ異様な感じがするんですが、しかしこういうので`-j`が一般的だというのは強く同意するので、これでいいと思います

**Comment by kmyk** [comment]
主にほしいのは利点1 (使用者 * CI) です。
20並列と比べて利点がかなり薄いのは正しいんですが、実装の手間はそんなに大きくない (多くて20行くらい？) ので、とりあえず簡単に削れるところから削っていきたいという気持ちです。

**Comment by kmyk** [comment]
実装は私がするつもりなのでその手間は無視してよくて、メンテコスト (オプションを増やしたくなさ + コードを増やしたくなさ) と多少の効果とのどっちをとるかの選択になっているはず

**Comment by yosupo06** [comment]
うーん　実際にCIの利用者が遅いと感じているならば追加するべきだとは思いますが、観測されていますか(逆に感じている利用者がいないなら、利点が消えるので実装するべきでないと思います)？

例えばhttps://github.com/kmyk/online-judge-verify-helperの利用者一覧のActionsを適当に眺めても、基本的に4~5分の範囲に収まっているように思えます(私が慣れてしまっただけで、実は4,5分でも長い？)


例:
https://github.com/beet-aizu/library/actions
https://github.com/kmyk/competitive-programming-library/actions

**Comment by kmyk** [comment]
4~5分は CI としては短めですが、verify-helper だと CI が終わらないとできない処理がある (自動で commit が push される仕様のためにCIが終わるまで追加の push ができない、CIが生成したドキュメントのCopyボタンを使って問題提出をしたい) ので可能なら短くしたいです。

(ところで、有用性に関する議論が長引くということは実装しない方がよい気がしてきました。ひとまずやめておこうかなと思います)

**Comment by yosupo06** [comment]
CIが4,5分でもネックになりうるのは理解しました

あまり急を要するissueではないと思うので、とりあえずこのissueはopenで残しておきます　遅いと感じてここに行き着いた人はemoticonなどを付けていただけると

**Comment by yosupo06** [comment]
今の所特段の需要はなさそうと判断し、一回closeします
