### ISSUE TITLE
[問題案] Range Inversion Query

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#563]
問題名: Range Inversion Query

想定アルゴリズム: 平方分割 O((N + Q)√N)
参考資料: https://stackoverflow.com/questions/21763392/counting-inversions-in-ranges

# 問題概要
長さ N の数列が与えられる
[l, r) の転倒数を出力、を Q 回処理

## 入力

```
N Q
a_0 a_1 ... a_{N-1}
l_0 r_0
l_1 r_1
:
l_{Q-1} r_{Q-1}
```

## 出力

```
```

## 制約
N <= 10^5 ~ (計測して判断)

## 検討事項
- 問題名
    - Range Inversion Count とかの方が良い？
- 数列の条件
    - 0 <= a <= 10^9 で重複ありの予定
- 空のクエリを入れるかどうか

**Comment by yosupo06** [comment]
Static Range Inversions Queryとかでいいと思います(Static: 静的なので / Range Inversions: https://arxiv.org/pdf/1908.11819.pdf 適当に調べたらRangeInversionsQueryが出てきたので)

**Comment by yosupo06** [comment]
> 数列の条件
> 0 <= a <= 10^9 で重複ありの予定

いいと思います
空のクエリを入れるかどうか
