### ISSUE TITLE
[問題案] Composition of Formal Power Series

### ISSUE THREAD

**Issue by hotman78** [yosupo06/library-checker-problems#569]
問題ID: composition_of_formal_power_series
問題名: Composition of Formal Power Series

参考資料: http://www.eecs.harvard.edu/~htk/publication/1978-jacm-brent-kung.pdf

# 問題概要

母関数 $f(x) = \sum_{i = 0}^{N - 1} a_i x^i$および$g(x) = \sum_{i = 0}^{M - 1} b_i x^i$が与えられます。f(g(x))をk項目まで求めてください

## 入力

```
N M K
a_0 a_1 a_2 ... a_{N-1}
b_0 b_1 b_2 ... b_{M-1}
```

## 出力

```
c_0 c_1 c_2 ... c_{K-1}
```

## 制約
N,M,K<=10000(手元で7秒程度なのでもうちょっと小さくした方がいいかも)

**Comment by yosupo06** [comment]
- 想定計算量はO((n log n)^{1.5})であってますか？
- modで998244353ですよね(念の為)

後は問題なさそうです

**Comment by hos-lyric** [comment]
- f(g(x)) と g(f(x)) のどっちにするかは準備する人の好みでいいですかね (わたしは特に意見ありません)
- b_0 = 0 (合成の内側の方の定数項が 0) は制約に課しますか？　一般の形式的冪級数だと定義できなくて，今回は f が多項式なので  \sum_{i=0}^{N-1} a_i (\sum_{j=0}^{M-1} b_j x^j)^i mod x^K を求めよということなら問題なく定義されます (この場合細かいことを言うと "Composition of Polynomials" が適切なのかもしれません)．b_0 = 0 があるかどうかでアルゴリズムにどのくらい影響があるかは存じていません．

**Comment by yosupo06** [comment]
確かに、b_0 = 0にしてN = M = Kにしたほうが自然な気がします(形式べき級数の先頭N項だけ与えられるという考え方)

**Comment by hos-lyric** [comment]
わたしは N = M が自然とはあまり思わないですが (convolution_mod と似たようなものだと思うので)，まあ準備がしやすいほうでいいと思います
(というのを準備がなされてから言ってすみません #572 )

**Comment by yosupo06** [comment]
無限長かもしれない母関数f / gが2個与えられます。f(g(x))の先頭N項を求めたいです

という設定ならばfとgの先頭N項を与えればいい、となり、自然のように思えました

**Comment by noshi91** [comment]
https://judge.yosupo.jp/problem/composition_of_formal_power_series
FORUM がリンクされていないようです

**Comment by rsk0315** [comment]
https://github.com/yosupo06/library-checker-problems/pull/613
forum 追記してみました
