### ISSUE TITLE
[問題案] Enumerate Palindromes

### ISSUE THREAD

**Issue by tko919** [yosupo06/library-checker-problems#574]
問題ID: enumerate_palindromes
問題名: Enumerate Palindromes

想定アルゴリズム: Manacher's Algorithm

# 問題概要
長さ$N$の文字列$S$が与えられます。
$S$に含まれる回文の中心として考えられる位置は文字、文字と文字の間の$2N-1$通りあります。
それぞれ左から$i+1$番目を位置$i$とするとき、文字列中で位置$i$を中心とする最長の回文の長さ$T_i$を出力してください。(存在しない場合は0)

## 入力

```
S
```

## 出力

```
T_0 T_1 ... T_{2N-2}
```

## 制約
- $1 \leq N \leq 500,000$
- $S$は英小文字からなる。

**Comment by yosupo06** [comment]
aaaaaaaaaaaa...の時に出力が壊れる気がします、T_iは長さですか？

**Comment by tko919** [comment]
あ、確かにそうですね　長さに変更します

**Comment by yosupo06** [comment]
長さなら良さそうです、改行せずに`1 2 3 4`みたいに出力させることにしましょう(他の文字列系の問題がこうだからと言うだけの理由です)

**Comment by polyomino-24** [comment]
問題のリンクが存在していな気がしました
