### ISSUE TITLE
Composition of Formal Power Seriesのテストケースについて

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#575]
次のケースでいくつかの提出が落ちると思われますが、テストケースに入っていないようです。
(自分の提出( https://judge.yosupo.jp/submission/18897 ) ではg(x) mod x^3を微分して0次の係数が0の時にinv()を呼んでいるためassertionに引っかかっています。writer解も同様のバグで落ちてそう…？)

100
5 4 3 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
0 0 1 2 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1

**Comment by yosupo06** [comment]
#572 

対応できそうならば対応していただけると嬉しいのですが、どうでしょうか…？ @hotman78

**Comment by hotman78** [comment]
今気づきました
対応します

**Comment by yosupo06** [comment]
#569
