### ISSUE TITLE
問題ページに説明用の画像を入れたい

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#579]
仕組みが用意されていたりしますか

**Comment by yosupo06** [comment]
あまり考えていなかったのですが、

1. 画像をどこかにアップロードしてmarkdownの画像埋め込み機能を使う
  a. 画像アップロード機能を追加？
2. base64で画像データをmarkdownの中に直接埋め込む

のどちらかになると思います

**Comment by beet-aizu** [comment]
1. でやることにします、ありがとうございます。
