### ISSUE TITLE
[Problem suggestion] Convex Layers

### ISSUE THREAD

**Issue by dragonslayerintraining** [yosupo06/library-checker-problems#582]
This problem (nested convex hulls) was discussed [here](https://codeforces.com/blog/entry/75929).
I forked this repository and was about to create a pull request when I realized I should make an issue first.

**Comment by yosupo06** [comment]
Cool! So, could you give me the problem statement first? 
Rough sketch is enough. We want to adjust the small details for keeping consistency with other problems.

**Comment by dragonslayerintraining** [comment]
You are given n distinct points in the plane with integer coordinates.
While there are points remaining, remove all points on the boundary of the convex hull of the remaining points.
For each point, output which iteration it was removed in.

1 <= n <= 200000
0 <= x_i, y_i <= 10^6
Time limit: 5 seconds

My implementation is O(n(logn)^2). The discussion linked above mentions a faster O(nlogn) solution that doesn't seem more complicated, but I haven't looked into it.

**Comment by yosupo06** [comment]
Thanks! That sounds good and no problem. So, there is no problem to make PR. If you have some trouble while preparing the problem, don't hesitate me to ask :)

**Comment by dragonslayerintraining** [comment]
Some checks were not successful but I don't know why.

**Comment by dragonslayerintraining** [comment]
Ok, checks passed now.

**Comment by yosupo06** [comment]
Thanks for your great and polite job! I reviewed but no problem, so this PR was merged and your problem was appeared in https://judge.yosupo.jp/problem/convex_layers .

(and FYI,  I added a japanese statement in #585 )
