### ISSUE TITLE
Pythonのバージョン

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#588]
GitHub Actions から Python 3.5.9が消えたようです（3.5.10に置き換えたら動きました）
3.5のサポートが9/13で切れるようですが、依存の見直しは検討していますか？

**Comment by yosupo06** [comment]
今CIが壊れてデプロイができなくなっています

**Comment by yosupo06** [comment]
もうセキュリティ周りの修正もされなくなるなら、むしろ切ったほうがいいですね　3.5は切ります
