### ISSUE TITLE
[Problem suggestion] Chordal graph recognition

### ISSUE THREAD

**Issue by dragonslayerintraining** [yosupo06/library-checker-problems#591]
Given an undirected graph with n vertices and m edges, determine if it is [chordal.](https://en.wikipedia.org/wiki/Chordal_graph)
If so, find a [perfect elimination ordering](https://en.wikipedia.org/wiki/Chordal_graph#Perfect_elimination_and_efficient_recognition).
If not, find an induced cycle of at least 4 vertices.

1<=n,m<=200000
Time limit: 5 seconds

I think the following is true (Please check. The resources I found on this problem don't explain how to efficiently find the cycle):
Let v_1, v_2, ... v_n be the vertices in the order found by maximum cardinality search (MCS).
The reverse of this ordering is a perfect elimination ordering if and only if the graph is chordal.
Otherwise, there exists i<j<k such that v_i and v_j are neighbors of v_k but v_i and v_j are not adjacent. There must exist some l<j such that v_l is adjacent to v_j but not v_k (since MCS picked v_j instead of v_k) If v_i and v_l are adjacent, we found a cycle. Otherwise, repeat the argument to extend the path with a vertex not adjacent to v_k. Eventually we get a cycle containing these three vertices and other vertices not adjacent to v_k. The shortest such cycle is an induced cycle of at least $4$ vertices. The final algorithm is O(nlogn) or O(n).

**Comment by yosupo06** [comment]
Thanks!

Your algorithm seems correct for me.

**Comment by bqi343** [comment]
@dragonslayerintraining Could you elaborate on "repeat[ing] the argument to extend the path with a vertex not adjacent to v_k." What vertex are you using to extend the path (i or j or l)? If l<i then is it always true that there exists some m<i such that (v_m,v_i) exists but (v_m,v_k) doesn't?

**Comment by dragonslayerintraining** [comment]
@bqi343 You're right. I didn't realize that. Maybe you could understand the proof [here](https://www.cs.cmu.edu/~janh/courses/411/18/lec/03-chordal-mcs.pdf) (I didn't).
Now I'm not sure if my approach to constructing a cycle is correct.

The $v_N$ is indeed a typo.
