### ISSUE TITLE
[問題案] nCk mod m

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#593]
(任意) 問題ID: {ID}
問題名: nCk mod m

(任意) 想定アルゴリズム: 拡張Lucasの定理 + CRT
(任意) 参考資料: https://ferin-tech.hatenablog.com/entry/2018/01/17/010829

# 問題概要
nCk mod m を求めよ

## 入力

```
n k m
```

## 出力

```
ans
```

## 制約
 1 <= n <= 10^18, 0 <= k <= n, 2 <= m <= 1000000

**Comment by hos-lyric** [comment]
- 0 <= n がいいかなと思います
- 1 <= m がいいかなと思います
- 実行時間等の兼ね合いもありそうですが m <= 10^7 がいいかなと思います (log つかないですよね？)

**Comment by hos-lyric** [comment]
m 固定で (n, k) 複数ケースとかもいいかもしれません

**Comment by yosupo06** [comment]
想定解の計算量を書いていただけると助かります(参考のブログには明示的には書かれていなさそう？)

**Comment by yosupo06** [comment]
前処理O(m) + O(log n + log k)ぐらいなら、hosさんの言う通り複数ケースでいいと思います　ケース数などは実測と相談ということで

**Comment by adamant-pwn** [comment]
It seems the intended algorithm here involves $O(p^e)$ pre-computation. It's generally possible to do with $O(pe)$ pre-computation instead, though the time per query degrades to something like $O(e^2 \log n)$. I wrote a [blog](https://codeforces.com/blog/entry/116681) about it recently. Might be an idea for extended version?
