### ISSUE TITLE
[問題案] N-th term of a linearly recurrent sequence

### ISSUE THREAD

**Issue by hly1204** [yosupo06/library-checker-problems#601]
(任意) 問題ID: 114514
問題名: N-th term of a linearly recurrent sequence

(任意) 想定アルゴリズム: a fast algorithm to calculate the N-th term of a series like p/q, here p and q are polynomials.
(任意) 参考資料: https://arxiv.org/pdf/2008.08822.pdf 
In the paper there is also an algorithm to find d terms from $u_{n}$ to $u_{n+d-1}$, maybe the question can be modified to that.

# 問題概要
$u_{n+d}=\sum_{i=0}^{d-1}c_{i}u_{n+i}$, given $c_{i},u_{i},i\in \{0,\dots, d-1\}$, find $u_{k}$.

## 入力

```
d k
c_{0} c_{1} \dots c_{d-1}
u_{0} u_{1} \dots u_{d-1}
```

## 出力

```
u_{k}
```

## 制約
$c_{i},u_{i}\in \mathbb{F}_{998244353}$

**Comment by beet-aizu** [comment]
サンプルに c が左右非対称なものも追加してほしいです
