### ISSUE TITLE
[Range Chmin Chmax Add Range Sum] testcases are weak

### ISSUE THREAD

**Issue by mickeyandkaka** [yosupo06/library-checker-problems#609]
Problem: Range Chmin Chmax Add Range Sum

I'm now learning segment tree beats，and try to implement，but currently I can't deal with the [problem](https://codeforces.com/edu/course/2/lesson/5/4/practice/contest/280801/problem/E)

So, I want to see other's implemention, however many submission failed on the given testcases. I pick some of them.

[this](https://judge.yosupo.jp/submission/28937)
[this](https://judge.yosupo.jp/submission/26679)
[this](https://judge.yosupo.jp/submission/29213)
[this](https://judge.yosupo.jp/submission/23533)

Reason:  When there's ckmax operation, if in the given interval max value < v, they will simply ignore this, which is totally wrong. They have the same mistake with my implemention.

## sample in

```
10 15
0 0 0 0 0 0 0 0 0 0
1 1 8 4
0 4 9 1
0 3 6 5
1 0 5 3
1 2 2 5
3 0 1
3 1 2
3 2 3
3 3 4
3 4 5
3 5 6
3 6 7
3 7 8
3 8 9
3 9 10
```

## sample out

```
3
4
5
4
3
3
1
1
1
0
```

**Comment by SSRS-cp** [comment]
The sample input is against the restrictions. l < r must be satisfied for every query, but in the fifth query l=r=2.

**Comment by mickeyandkaka** [comment]
> The sample input is against the restrictions. l < r must be satisfied for every query, but in the fifth query l=r=2.

sorry, I will check it .....
