### ISSUE TITLE
[問題案] bitwise and convolution

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#619]
https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-727557401
問題名: bitwise and convolution

想定アルゴリズム: 高速ゼータ変換、高速メビウス変換

# 問題概要
C_k = Σ[i & j = k] A_i B_j
mod 998244353

## 制約
n <= 2^20

## 検討事項
- 問題名
    - 値と添え字のどちらを and するのか分からないかもしれない
- 制約
    - n が 2 冪でないものも入れるかどうか
    - n をもっと大きくするか (IO がネック？)

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/subset_convolution と合っていると嬉しいです、具体的にはnと長さ2^nの配列を与える方式です。

そもそもIOが律速の問題になる気がするので、nは20でいいと思います

**Comment by noshi91** [comment]
set_intersection_convolution ということですか？

**Comment by yosupo06** [comment]
いえ、問題名はそのままで大丈夫です。その他の入力 / 出力形式とかを合わせてほしい、という意図でした　すいません
