### ISSUE TITLE
[問題案] Bitwise Or Convolution

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#621]
問題名: Bitwise Or Convolution

想定アルゴリズム: 高速ゼータ変換、高速メビウス変換

# 問題概要

長さ 2^n の数列 a, b が与えられる
c_k = Σ[i | j = k] a_i b_j を mod 998244353 で出力

## 入力

```
n
a_0 a_1 ... a_{2^n-1}
b_0 b_1 ... b_{2^n-1}
```

## 出力

```
c_0 c_1 ... c_{2^n-1}
```

## 制約
0 <= n <= 20
0 <= a_i, b_j < 998244353

**Comment by noshi91** [comment]
a, b を反転して
https://github.com/yosupo06/library-checker-problems/issues/619
これを適用した後 c を反転すると同じなので、不要な気がしてきました
ほとんどコピペなので準備は簡単なのですが

**Comment by yosupo06** [comment]
正直bitwise and convolutionとの距離が近すぎて、1つで十分な気がしています

**Comment by beet-aizu** [comment]
僕は欲しいです　理由：コンテスト中にそんなことをしたくはないので

**Comment by beet-aizu** [comment]
思想の問題だと思うんですが、欲を言えば line_add_get_min に対する line_add_get_max とかも用意してあるとうれしいです（実際符号反転パートがバグっていたので）

**Comment by yosupo06** [comment]
> コンテスト中にそんなことをしたくはないので

これはとてもわかります、実際に自分もCHT(max)とCHT(min)を両方用意していますし、コンテスト中に符号反転のコードを書いたらバグります。

なのでCHT(max), CHT(min)を両方用意するとして、例えば以下のようなコードを書けば CHT(max) をベリファイするのに line_add_get_max はいらないんじゃないか、ということを考えています。

```cpp
void verify() {
    cht_max cht;
    for (int i = 0; i < q; i++) {
        int type = input();
        if (type == 0) {
            int a = input(), b = input();
            cht.add_line(-a, -b);
        } else {
            int p = input();
            print(-cht.get_max(p));
        }
    }
}
```

**Comment by beet-aizu** [comment]
> 例えば以下のようなコードを書けば

この部分をジャッジ側で提供する仕組みを作るのはどうでしょうか？
つまり、ある問題の (入力, 出力) から別の(入力, 出力) を生成するということです

 line_add_get_max を作らない一番の理由はメンテナンスコストだと思っていますが、この認識は正しいですか？

**Comment by yosupo06** [comment]
- メンテナンスコスト
- 問題を追加するときの手間
- バリエーションを愚直に増やすとトップページが見にくくなる
- 同じアルゴリズムの提出を複数問題に散らばらせたくない

あたりがデメリットです

例えばissueページにmaxクエリへのコンバート例として↑のソースコードを置いておくとかはアリだと思います
