### ISSUE TITLE
[問題案] Bitwise Xor Convolution

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#622]
問題名: Bitwise Xor Convolution

想定アルゴリズム: ウォルシュ・アダマール変換

# 問題概要

長さ 2^n の数列 a, b が与えられる
c_k = Σ[i ^ j = k] a_i b_j を mod 998244353 で出力

## 入力

```
n
a_0 a_1 ... a_{2^n-1}
b_0 b_1 ... b_{2^n-1}
```

## 出力

```
c_0 c_1 ... c_{2^n-1}
```

## 制約
0 <= n <= 20
0 <= a_i, b_j < 998244353

https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-547908438
https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-616515657

**Comment by yosupo06** [comment]
よさそうです
