### ISSUE TITLE
[問題案] Inverse Matrix

### ISSUE THREAD

**Issue by sansen0796** [yosupo06/library-checker-problems#626]
(任意) 問題ID: inverse_matrix
問題名: Inverse Matrix

(任意) 想定アルゴリズム: 掃き出し法
(任意) 参考資料: https://en.wikipedia.org/wiki/Gaussian_elimination

# 問題概要
N * N の 行列 A が与えられる
A^(-1) を mod 998244353 で出力

## 入力

```
N
A_{0, 0} A_{0, 1} ... A_{0, N - 1}
A_{1, 0} A_{1, 1} ... A_{1, N - 1}
...
A_{N - 1, 0} A_{N - 1, 1} ... A_{N - 1, N - 1}
```

## 出力

```
A^(-1)_{0, 0} A^(-1)_{0, 1} ... A^(-1)_{0, N - 1}
A^(-1)_{1, 0} A^(-1)_{1, 1} ... A^(-1)_{1, N - 1}
...
A^(-1)_{N - 1, 0} A^(-1)_{N - 1, 1} ... A^(-1)_{N - 1, N - 1}
```

## 制約
1 <= N <= 500

## 検討すべき事項
- 問題名、問題ID
- 入力に正則でない行列を許すか、許すなら出力はどうするか
- この問題が要るか。というのも Determinant of Matrix を解くコードがあるならそれに書き足せば逆行列も求められる上、セルフジャッジも容易であるから

**Comment by yosupo06** [comment]
よさそうです

> 入力に正則でない行列を許すか、許すなら出力はどうするか

入れてほしいです　ダメなら -1 を出力など

> この問題が要るか。というのも Determinant of Matrix を解くコードがあるならそれに書き足せば逆行列も求められる上、セルフジャッジも容易であるから

合って良いと思います
