### ISSUE TITLE
[問題案] Chromatic Number

### ISSUE THREAD

**Issue by tko919** [yosupo06/library-checker-problems#628]
問題ID: chromatic_number
問題名: Chromatic Number

想定アルゴリズム: bitDP,包除原理+FZT
参考資料: https://www.slideshare.net/wata_orz/ss-12131479

# 問題概要
 N 頂点 M 辺の単純無向グラフが与えられます。 i 番目の辺は {u_i,v_i} です。
彩色数 C を求めてください。

## 入力

```
N M
u_0 v_0
\vdots
u_{M-1} v_{M-1}
```

## 出力

```
C
```

## 制約

N<=18

**Comment by yosupo06** [comment]
よさそうです

**Comment by yosupo06** [comment]
何らかのmodで数え上げると思うんですが、確率評価とかどうなっているのか気になってきました

**Comment by tko919** [comment]
https://twitter.com/tko919_/status/1366704087580823555?s=20
mod∈[2^{w-1},2^w)なるwを取ると、失敗確率はO(N^3/2^w)になるようです
一応素朴なbitDPが通る制約にはするつもりです
