### ISSUE TITLE
[問題案] 多項式のexp(とlog(とsqrt))

### ISSUE THREAD

**Issue by beet-aizu** [yosupo06/library-checker-problems#63]
GF(998244353)上の N次多項式F(x)が与えられる。
exp(F(x)) = \sum_{k=0}^{\infty} \frac{F(x)^k}{k!} mod x^n を求める

あとlogとかsqrtもほしいです（小声）

**Comment by hos-lyric** [comment]
実は F_p だと p! で割る項があるから定義できなくて，有理数体で定義してそれをいつもの形式で出力せよという感じにしないと問題文が嘘なんですよね (F_p 警察)

制約をちゃんとするのがとても大事で
exp: 定数項が 0 (でいいのかな)
log: 定数項が 1 (ですか？)
sqrt: 問題 sqrt_mod と合わせるなら 2 乗して入力のやつになるのを 1 つ答える，ないならそう個l耐える，みたいな形式？ (sqrt の存在判定は，ちょっと非自明)

**Comment by yosupo06** [comment]
sqrtは定数項がmod sqrt出来れば定義できるのはわかるんですが、logとexpを魔法としてしか認識してないです

**Comment by yosupo06** [comment]
分割数列挙みたいな、内部でlog, expと呼ばれるなにかを使うだろうけど、出力に疑いの余地はないみたいなのだと定義警察が来なくて平和(？)なので、とりあえずlogをなかで使うやつがあれば嬉しいです(分割数はlogは手作業でexpしかつかわないので

**Comment by yosupo06** [comment]
いや、↑の式でk = 0からp - 1の和にすれば定義の問題は解決するのか？

**Comment by hos-lyric** [comment]
sqrt が定義できる条件は非 0 最低次の次数が偶数かつ係数が平方剰余，だと思うんですよね，sqrt(X) は，ありません

p - 1 次までの和にすると解決はしそうだけど exp や log がいい感じになることをちゃんと考えるのめんどいな (それはそうなんだけど)
わたしが言おうとしたのは，問題文では exp 等の定義は \Q[[X]] でやっといて，n <= 10^5 では n 次の係数の分母は 998244353 で割り切れないことが証明できるのでそれを出力してください，がいいと思いましたというやつです

**Comment by hos-lyric** [comment]
ライブラリチェック問題としては応用問題じゃなくて exp, log, sqrt それぞれそのままがいいなと思うというかそういう思想だと思ってた

**Comment by yosupo06** [comment]
問題としては十分シンプルならなんでも良いつもりで、当然log expそのままも入れたいんですが、定義とかがよくわかんないならとりあえず定義が明確なやつ足しとくかって感じでした

**Comment by yosupo06** [comment]
母関数 $f(x) = \sum_{i = 0}^{N - 1} a_i x^i$ が与えられます。この母関数のexpの先頭 $N$ 項を求めてください。つまり

$(\sum_{k = 0}^{N - 1} f(x)^k / k!) % (x^N)$ を出力してください

# 入力
```
N
a_0 a_1 a_2 ... a_{N - 1}
```

# 制約

- 1 <= N <= 500,000
- a_0 == 1

# 出力
```
b_0 b_1 ... b_{N - 1}
```

ただし g(x) = \sum_{i = 0}^{N - 1} = b_i x^i$ とする

**Comment by yosupo06** [comment]
これで行きます

**Comment by yosupo06** [comment]
人によって使ってるexpの出力が違う だともっと検討が必要なんですが、 exp / logはみんな出力自体は同じものを使っていて、それをどう意味付けるかという話だと認識したんでとりあえず適当な定義を置いておくことにしました(出力さえ変わらなければ問題文は後から変更して問題が起きないです)

**Comment by yosupo06** [comment]
sqrtはちょっと制約が難しいんでもう少し調べます

**Comment by yosupo06** [comment]
やっぱりlogも定数項がどうなるかとか、log (f(x) + 1)とlog (f(x))のどっちのほうが筋がいいのかとかがわからなくなりました(後者だと定義に微分とか積分が必要？)

**Comment by yosupo06** [comment]
定数項は0を出すで平気そう(自分調べ)で、定義はどうとでもなるので、log (f(x) + 1) or log f(x)のどっちがいいかが本質っぽい

**Comment by hos-lyric** [comment]
- log (1 + X) = X - X^2/2 + X^3/3 - ... と f との合成で log (1 + f(X)) を定める (f の定数項は 0)
- exp の逆操作として log を定める

があって，まあ同じ定義になるんですけど，log1p と log のどっちを自然な操作と考えるかは趣味の問題っぽい気もします
(exp より expm1 のほうが自然だ！と言い出すと，混沌……)
(実用のシチュエーションを考えると，ライブラリとして準備するのは f(x) -> log f(X) なのかなぁ)
(log の実用例は，α 乗とかです (実用？))

定数項は 0 を出力であってます
(log f(X) = \int dX f'(X) / f(X) で定義するとそれがちょっとわからないけど)

**Comment by yosupo06** [comment]
log f(x)にします 僕のライブラリがそれなので

**Comment by yosupo06** [comment]
f(g(x))が出来るのか ゆるぼ
