### ISSUE TITLE
[問題案] Ordered Set

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#632]
問題名: Ordered Set
想定アルゴリズム: van emde boas tree / 64分木 など

# 問題概要

N以下の非負整数からなる集合Sが与えられます。以下で説明されるクエリを順にQ回処理してください。

1 k : kをSに挿入する(クエリ前はkがSに属さないことが保証される)
2 k : kをSから取り除く(クエリ前はkがSに属することが保証される)
3 k : kがSに属する場合は1,そうでない場合は0を出力
4 k : Sに属するkより大きい要素のうち最小のものを出力(存在しない場合は-1を出力)
5 k : Sに属するkより小さい要素のうち最大のものを出力(存在しない場合は-1を出力)

## 入力

クエリを処理する前の集合Sは0,1からなる長さN+1の文字列Tで与えられる。T_iが1の時、かつその時に限りiはSに属する。

```
N Q
T
c_0 k_0
c_1 k_1
...
c_{Q-1} k_{Q-1}
```

## 制約

N <= 10^7
Q <= 10^6
0 <= k_i <= N (c_i = 1, 2, 3)
-1 <= k_i <= N (c_i = 4)
0 <= k_i <= N + 1 (c_i = 5)

## 検討事項

- Ordered Setという題名は適切なのか？
	- 将来的にkth element, lower/upper_bound, prefix sumなどを全部載せたものが追加される可能性があり、これと区別する必要がある？
	-  Ordered Setよりいい題名が思いつきませんでした… より良い題名があったら教えてください
	- 追記：Predecessor Problemというものを知りました [Wikipedia](https://en.wikipedia.org/wiki/Predecessor_problem) こちらの方が適切そう…
- 制約(N = 10^7)の妥当性
	- 入力の量は問題なさそう(初期状態の入力を01列にしているため)
	- (1) N=10^7は大きすぎないか？
		- 想定解(van emde boas tree/64分木)なら2^24 = 1.6 * 10^7付近を上限にしたい感がある
		- N = 10^6だと平衡二分木のverifyにも使えるがN=10^7だとTLギリギリになりそうという欠点(?)はある
	- (2) N = 10^18にして初期状態を空集合にしてもいいのでは？
		- その制約だと実用上はstd::setで事足りそうであまり需要がない

**Comment by yosupo06** [comment]
- 0以上N以下 ではなくて、0以上N未満にしましょう (このジャッジ数列が半開で値が両閉なんですが、このNは数列の長さっぽいです)

クエリ1,2: (クエリ前はkがSに属さないことが保証される), (クエリ前はkがSに属することが保証される) これ無いほうがよさそうです
クエリ3,4: より上, より下　じゃなくて以上、以下にすると制約が0 <= k_i < Nに揃っていい感じだと思います

Predecessor Problem よさそうです
制約は10^7で問題ないですが、std::setで10sに間に合ったりすると嬉しいです(mustではないです)

**Comment by NyaanNyaan** [comment]
半開区間、了解です

クエリの細かいところについてはどちらにするか迷っていた記憶があるのでそちらに合わせます

制約については10^7要素追加するset解が手元のPC(ジャッジサーバーより遅い)で5.5sで動くことを確認したのでたぶん大丈夫そうです
