### ISSUE TITLE
[問題案] k-th Root (Integer) (kth_root_integer)

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#64]
整数 a, k が与えられる．
floor(a^(1/k)) を求めよ．

0 <= a < 2^64
1 <= k < 2^64

(1 <= k < 64 とかでもいいけど)

**Comment by hos-lyric** [comment]
複数ケース (ファイルサイズが許す限りたくさん)

**Comment by yosupo06** [comment]
さすがにkがデカくてもギャグなんで、1 <= k <= 64にします

**Comment by yosupo06** [comment]
ところで想定はオーバーフローに注意しながら二文探索ですか？

**Comment by yosupo06** [comment]
k = 2, 3あたりが必要になる感覚はわかる

**Comment by hos-lyric** [comment]
ライブラリを作るなら k <= 64 とか仮定せずに動くようにしたいかなぁと思っただけで (if 文ひとつ入れなさい)，まあどちらでも．k = 64 が入ってればええやろという感じはとてもありますね

毎回怖がりながら書くのが嫌すぎて提案しました
なんと，ちゃんとした想定解は用意してないんですよね
pow で近似して付近を調べるとかかなぁと思ってたけど，きれいかつ安全にやりたい

**Comment by yosupo06** [comment]
とりあえず足しました(想定解は、二分探索)

**Comment by sansen0796** [comment]
all_k3.cpp と near_border.cpp が希望するケースを生成しないように読めます
どちらも58行目で mypow を呼ぶべきですがしていません
