### ISSUE TITLE
[sort_by_argument] テストケースの強化

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#648]
$x$ 軸の正・負の部分の区別がいい加減でも AC が出ているようです。

https://judge.yosupo.jp/submission/38132

例えばこのコードが AC になっていますが、(1,0) と (-1,0) のソートが行えません。

10
1 0
1 0
-1 0
-1 0
1 0
-1 0
1 0
-1 0
1 0
-1 0

みたいなケースはどうでしょうか。
（utpc を解くために最短実行時間の偏角ソートのロジックをパクったら、ひどいことに…）

**Comment by maspypy** [comment]
small all ですら撃墜できそうなバグ見えたが、なぜかうまいこと撃墜できないのか…。
(a,0) と (-a,0) の間に頂点があると、それらを介して正しい順にソートされる感じかな。

x 軸上にのみたくさん点がある場合を handmade or random で生成すると良さそうですかね。

作業は私が行えると思います。

**Comment by yosupo06** [comment]
よさそうです

**Comment by yosupo06** [comment]
#248
