### ISSUE TITLE
[問題案]Exp of Formal Power Series(exp_of_formal_power_series)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#65]
母関数 $f(x) = \sum_{i = 0}^{N - 1} a_i x^i$ が与えられます。この母関数のexpの先頭 $N$ 項を求めてください。つまり

$(\sum_{k = 0}^{N - 1} f(x)^k / k!) % (x^N)$ を出力してください

# 入力
```
N
a_0 a_1 a_2 ... a_{N - 1}
```

# 制約

- 1 <= N <= 500,000
- a_0 == 0
- 0 <= a_i < 998244353

# 出力
```
b_0 b_1 ... b_{N - 1}
```

ただし g(x) = \sum_{i = 0}^{N - 1} b_i x^i とする

#63

**Comment by hos-lyric** [comment]
あとで変えられる部分はまた pull request なりなんなりだそうと思います

mod が書いてないことに，気づいたんですよね
a_0 以外は 0 <= a_i < 998244353 ですか

**Comment by yosupo06** [comment]
そうです

**Comment by hos-lyric** [comment]
問題名は後から直すのがめんどそうということにも気づけた
通常型母関数というよりは形式的冪級数じゃないかなとちょっと思った

**Comment by yosupo06** [comment]
ありがとうございます(fixed)

**Comment by hos-lyric** [comment]
formal power series を fps と呼ぶ文化広めたいですね (これは半分提案半分雑談です)
(いやなんでもよいんですけど，ながいので……)

https://docs.sympy.org/latest/modules/series/formal.html#sympy.series.formal.fps
用法はあるらしい (?)

**Comment by yosupo06** [comment]
formalが無いと意味がちょっと変わるのかな、とりあえず付けておきます

**Comment by yosupo06** [comment]
問題名は(もちろん限度はあるけど)ある程度までは長くても困らないことに気付いたんで、あんまり有名じゃない略称は使わないことにしました(これも深く考えてなかったんで既に統一感が終わってるんですが)
