### ISSUE TITLE
[問題案] Matrix Product

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#654]
問題名: Matrix Product

想定アルゴリズム: 愚直 /Strassen Algorithmなど

# 問題概要

$N \times N$行列$A, B$が与えられます。$C \equiv A B \pmod 998244353$を求めてください。

## 入力

```
N
A_11 A_12 ... A_1N
...
A_N1 A_N2 ... A_NN
B_11 B_12 ... B_1N
...
B_N1 B_N2 ... B_NN
```

## 出力

```
C_11 C_12 ... C_1N
...
C_N1 C_N2 ... C_NN
```

## 制約
1 <= N <= 1024

行列積の十分大きいケースでのオンラインジャッジが欲しかったのでIssueを建てました。

手元だとmodintを除いて数行の実装でN=1024が900ms程度で動いたのでN<=1024としました。(攻めすぎかも？)

行列のサイズを正方行列以外も含めるかは悩んでいます。(制約が複雑になりそうなので)

**Comment by yosupo06** [comment]
(問題名がMatrix Productなら)正方行列以外も含めたほうがいいと思います

```
N M K
(N * M)行列
(M * K)行列
```

出力

```
N * K行列
```

がいいと思います

制約はN=1024でいいと思います(TLは10sにしておいてほしいです)
