### ISSUE TITLE
[問題案] Convolution (mod 2^64)

### ISSUE THREAD

**Issue by hos-lyric** [yosupo06/library-checker-problems#664]
問題ID: convolution_mod_2_64
問題名: Convolution (mod 2^64)

想定アルゴリズム・参考資料:
- 10^9 くらいの良い素数 5 個でやって復元 (入力長 2^22 で 6 個かな？)
- https://codeforces.com/blog/entry/45298 (ちゃんと読んでません)
- https://doi.org/10.1007/BF00289470 (まったく読んでません)

# 問題概要
https://judge.yosupo.jp/problem/convolution_mod と同じ
mod 2^64

## 制約
- 1 <= N, M <= 2^19
- 0 <= a_i, b_i < 2^64

# 検討事項
- 存在価値は，mod 2^64 の問題は (単なる嫌がらせとかではなく) 出題されてしまうのでというのと，違うコードが要求されるのでというのと，各種アルゴリズム比較用です
- ID がかっこよくない
- 2^128 じゃない理由を詰められると実は困ってしまう
- サイズ制約はとりあえず他 2 つと同じものを書いてみたけどよくわかりません，ファイルが大きいことは確か

cc @noshi91

**Comment by yosupo06** [comment]
mod 2^64特化がmod 5個よりも速いならば、入れてもいいかなという気持ちがあります

**Comment by hos-lyric** [comment]
いろいろ比べた結果長さによって速かったり遅かったりすることがわかったので，是非入れたいなとなりました．
(N + M - 1 以上の最小の「2 冪」「3 冪」「3 冪の 2 倍」がどれになるかに依存……)

(速度感)
N, M = 2^19 だとそんなに変わらないですが mod 素数 5 個よりちょっと速いかもしれないものがあります
N, M = 3^12 にすると mod 素数 5 個だけ遅くなるので差がつきます……
N, M = 2^20 だと mod 素数 5 個がたぶん最もよいです (手元だと入出力除いて 0.7 sec くらいです)

**Comment by yosupo06** [comment]
了解です

**Comment by yosupo06** [comment]
- IDは仕方がない部分があります（特殊な記号を入れるとどこが壊れるかわからないので）
- 2^64でいいと思います
- 制約は他に合わせて2^20にしましょう　差がつくもの(e.g. 3^12)を入れておいていただけると嬉しいです

**Comment by cai-lw** [comment]
This is actually very ideal for verifying Karatsuba's algorithm and a lot of people have done that:rofl:
