### ISSUE TITLE
[Problem proposal] Range Frequency

### ISSUE THREAD

**Issue by ldct** [yosupo06/library-checker-problems#666]
You are given an integer sequence `a_0, a_1, ..., a_{N-1}` in order. Process the following Q queries offline:

- `l_i, r_i, e_i`: print the number of times that `e_i` occurs in `(a_{l_i}, ... a_{r_i})`

**Comment by yosupo06** [comment]
LGTM

**Comment by noshi91** [comment]
0 <= N <= 5e5, 0 <= Q <= 5e5
0 <= a_i <= 1e9
0 <= l_i <= r_i <= N
で良いでしょうか？
