### ISSUE TITLE
Inverse Matrix correct solution fails to compile

### ISSUE THREAD

**Issue by plasmatic1** [yosupo06/library-checker-problems#678]
Trying to compile the correct solution for the problem inverse_matrix on my local machine is giving me the following error: https://pastebin.com/vxNLFJhy

For reference, I'm using https://github.com/online-judge-tools/verification-helper/ to verify the correctness of my codebook templates.  Maybe there is a way to make it so that compilation warnings are not treated as errors, but I'm not sure how to do so.

I can also provide the code for `tests/math/matrix_inverse.test.cpp` if necessary, but it looks like an error with the correct solutions.

**Comment by plasmatic1** [comment]
Some more thoughts on the issue:

- It seems like github actions has no issues processing the problem and gives a [correct verdict](https://plasmatic1.github.io/templates/tests/math/matrix_inverse.test.cpp).
- Locally, I'm running on WSL2 with Ubuntu version 18.04 LTS.  Maybe this is an issue with WSL?
- Here is the relevant piece of code I was trying to test https://github.com/plasmatic1/templates/blob/master/tests/math/matrix_inverse.test.cpp

**Comment by NyaanNyaan** [comment]
https://stackoverflow.com/questions/49845474/why-does-gcc-diagnose-a-unused-variable-for-structured-bindings-while-clang-does
This seems to be bug in gcc and has been fixed in the latest version.
