### ISSUE TITLE
[問題案] Shift of Sampling Points

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#680]
(任意) 問題ID: shift_of_sampling_points
問題名: Shift of Sampling Points（標本点のシフト)

想定アルゴリズム: ラグランジュ補間+畳み込み O((N+M) log (N+M))

# 問題概要

N-1次の多項式f(x)の標本点f(0), f(1), ..., f(N-1)が与えられます。
i = 0, ..., M-1に対してf(T＋i) mod 998244353を計算してください。

## 制約

- 1 <= N, M <= 500000
- 0 <= T < 998244353
- 0 <= f(i) < 998244353

## 入力

```
N M T
f(0) f(1) ... f(N-1)
```

## 出力

```
f(T) f(T+1) ... f(T+M-1)
```

- 0除算周りでバグらせがちでverifyがほしかったので立てました

- 問題名は議論の余地がありそう

**Comment by hos-lyric** [comment]
かなり優しくした版の verify 用問題を貼っておきます：

- https://www.luogu.com.cn/problem/P5667
- https://loj.ac/p/166

より一般的な制約でジャッジを設置するのには賛成です．
(貼ったのは長さが同じだしシフト後 0 を跨がないしなので)

(ところで，下降冪の形に直してシフトすると 0 除の場合分けとかは登場せずに済んだ気がします)

--

> 問題名

思ったことを雑に書きます：
https://judge.yosupo.jp/problem/polynomial_taylor_shift と同様に "Polynomial" がどこかにほしいような気もします．
"Polynomial Shift" という言葉はそれはそれであるようですが意味が変わってしまっているかもしれません．
"Taylor Shift" がの指す範囲があまりちゃんとわかっていないので，"Taylor" を含めることの是非はわかりません．

**Comment by NyaanNyaan** [comment]
verify問題ありがとうございます！

> (貼ったのは長さが同じだしシフト後 0 を跨がないしなので)

はい、0をまたぐ場合のverifyを書きたかった面が強いです。

> (ところで，下降冪の形に直してシフトすると 0 除の場合分けとかは登場せずに済んだ気がします)

考えてみましたが、1/(T+i)!を要素とするToeplitz行列が出てきて場合分けが必要になりそうな雰囲気がしました(やり方がまずいのかもしれません)

> 問題名

"Polynomial Shift"だと多項式自体のシフトになりそうなので"Shift of Sampling Points of Polynomial"が適切でしょうか…？(自信ないです)

**Comment by hos-lyric** [comment]
> 下降冪の形に直してシフト

まず f(x) = \sum_{i=0}^N a[i] x^{\underline{i}} の形にして，
それを f(x+T) = \sum_{i=0}^N b[i] x^{\underline{i}} の形にするには
二項定理もどき (x+T)^{\underline{i}} = \sum_{j=0}^i \binom{i}{j} x^{\underline{i-j}} T^{\underline{j}} を使うと普通の多項式のシフトと同じようにできて，
T がでてくるのはその下降冪だけ，という感じです．

> "Shift of Sampling Points of Polynomial"

自信ないですがよさそうな気がします．

**Comment by yosupo06** [comment]
LGTM

**Comment by NyaanNyaan** [comment]
> 二項定理もどき (x+T)^{\underline{i}} = \sum_{j=0}^i \binom{i}{j} x^{\underline{i-j}} T^{\underline{j}} 

この式を使うのは気づきませんでした、なるほどです。
有用なアルゴリズムを教えて頂きありがとうございます！！！
