### ISSUE TITLE
[問題案] 問題名

### ISSUE THREAD

**Issue by rishabhdeepsingh** [yosupo06/library-checker-problems#690]
(任意) 問題ID: Fibonacci
問題名: Fibonacci

# 問題概要
Given `n` find the nth Fibonacci number modulo P (prime)

## 入力

```
50
```

## 出力

```
586268941
```

## 制約
$ n <= 10^18$

**Comment by cai-lw** [comment]
Fibonacci is a special case of an existing problem https://judge.yosupo.jp/problem/kth_term_of_linearly_recurrent_sequence
