### ISSUE TITLE
Split "Math" into smaller topics

### ISSUE THREAD

**Issue by cai-lw** [yosupo06/library-checker-problems#694]
Problems in "Math" are already kind of sorted by topics so I suggest splitting it into the following categories.

- Number theory
- Polynomials
- Combinatorics
- Modular Arithmetic
- Miscellaneous

The name "math" is confusing since technically every algorithm is math. The concept of "math" is too large compared to other existing categories like "graph", "matrix", "string", etc.. There are also too many problems in "math" making it somewhat difficult to find problems.

**Comment by hos-lyric** [comment]
I agree with splitting. I hope it's done when technical difficulties are resolved.

- "Number theory" and "Modular Arithmetic": Perhaps a bit hard to distinguish?
- "Polynomials": I assume this would include power series. Having this as a separate category would be really useful.

**Comment by cai-lw** [comment]
@hos-lyric 
> "Number theory" and "Modular Arithmetic": Perhaps a bit hard to distinguish?

Due to the prevalence of mod 998244353/1000000007 in competitive programming, I think modular arithmetic deserves its own category. But I'm also fine with merging them with other number theory topics.

> "Polynomials": I assume this would include power series.

Yes

**Comment by yosupo06** [comment]
By backend changing, we becomes to be able to modify top page by editing this file https://github.com/yosupo06/library-checker-problems/blob/master/categories.toml

**Comment by yosupo06** [comment]
By splitting polynomial problems, I feel # of problems in "Math" is acceptable, so close this issue for now. (We will create another topic (probably Number theory) in the future.)

**Comment by maspypy** [comment]
closed な issue に書き込むという行いが一般的であるかどうか知らないです、立て直した方が良いようであればそうします。

> I feel # of problems in "Math" is acceptable

「math が多すぎる」というよりも、「分類名として不適切である」という理由から、変えたいと思うのですが、この点についてはいかがお考えですか？私は以下に強く同意しています。

> The name "math" is confusing since technically every algorithm is math. The concept of "math" is too large compared to other existing categories like "graph", "matrix", "string", etc.. 

math を「その他」のような意味で使用していませんか？綺麗な分類が難しくて未分類枠ができてしまうことは理解できますが、その枠が math という名前であることには反対です。難しいものは「その他」「未分類」「その他のmath」のような名称の分類をつけるのが良いと思います。

仮の具体案も置いておきます。

Sequence
  "stirling_number_of_the_first_kind",
  "stirling_number_of_the_second_kind",
  "bernoulli_number",
  "partition_function",
  "montmort_number_mod",
  "sum_of_exponential_times_polynomial",
  "sum_of_exponential_times_polynomial_limit",
  "find_linear_recurrence",
  "kth_term_of_linearly_recurrent_sequence",

NumberTheory
  "counting_primes",
  "enumerate_primes",
  "factorize",
  "binomial_coefficient",
  "sum_of_totient_function",
  "sum_of_floor_of_linear",
  "sqrt_mod",
  "kth_root_mod",
  "discrete_logarithm_mod",
  "tetration_mod",

Miscellaneous ?
  "kth_root_integer",
  "nim_product_64",
  "sharp_p_subset_sum",
  "two_sat"

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/pull/1193
