### ISSUE TITLE
[問題案] Binary Matrix Row Reduction

### ISSUE THREAD

**Issue by cai-lw** [yosupo06/library-checker-problems#697]
問題ID: binary_matrix_row_reduction
問題名: Binary Matrix Row Reduction

想定アルゴリズム: Gaussian Elimination with bit operations
参考資料:

# 問題概要

Given a NxM matrix over GF(2). Find its rank R as well as R linearly independent bases of its row space.

## 入力

```
N M
A[0][0] A[0][1] ... A[0][M-1]
A[1][0] A[1][1] ... A[1][M-1]
...
A[N-1][0] A[N-1][1] ... A[N-1][M-1]
```

## 出力

```
R
A[0][0] A[0][1] ... A[0][M-1]
A[1][0] A[1][1] ... A[1][M-1]
...
A[R-1][0] A[R-1][1] ... A[R-1][M-1]
```

## 制約
1<=N,M
N*M<=4x10^6

## Comments
Gaussian Elimination with binary matrices is commonly used for problems about XORing things together. Although Library Checker already has several problems using Gaussian Elimination, implementing it with bit operations is a non-trivial change. Also, Library Checker doesn't seem to have any problem that requires speeding up with bit operations.

The complexity is O(NMmin(N,M)/W) where W=64 is machine word size. Implementations using fixed size bit arrays such as `std::bitset` will be killed, since their complexity is O(NMmax(N,M)/W). If we want to allow using `std::bitset`, we can add N,M<=2x10^3.

We can also consider other problems requiring Gaussian elimination, such as computing determinant or solving system of linear equations. However, for binary matrices, I think the most common use case is finding linearly independent bases.

**Comment by hos-lyric** [comment]
Yeah, I also think it's worth having this problem!

For the constraints, only limiting NM sounds fine to me. We can then add some cases with small max(N,M) (with distinguished file names) for users enthusiastic about verifying the fixed size version. 
(In O(NMmax(N,M)/W), you mean by max(N,M) the maximum over all inputs, right?)

**Comment by cai-lw** [comment]
@hos-lyric 
>In O(NMmax(N,M)/W), you mean by max(N,M) the maximum over all inputs, right?

Yes

**Comment by cai-lw** [comment]
Well, I think this might be too easy and too similar to general Gaussian elimination.
I will propose another problem for bit sets.
