### ISSUE TITLE
[問題案] 彩色数

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#714]
問題名: 彩色数, 頂点彩色, グラフの彩色 (復元有なら後者 2 つが適切？)

想定アルゴリズム: 乱択 (correct.cpp をどうするか検討)

# 問題概要

無向グラフが与えられるので彩色数を出力

- 自己ループ？(有りでもよいと思う)
- 多重辺？(有りが良いと思う)
- 復元？(復元で計算量が少し悪くなるかもしれない)

## 入力

```
n m
u_0 v_0
:
```

## 出力 (復元ありの場合)

自己ループ含む場合
```
-1
```

含まない場合
```
k
c_0 c_1 ... c_{n-1}
```

## 制約

0 <= n <= 20

## その他

f[S] := S に包含される独立集合の個数
の値の種類数が少ないので同じ値でまとめると高速になるなどの話もあるらしいです。

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/chromatic_number
