### ISSUE TITLE
[問題案] Bell number

### ISSUE THREAD

**Issue by cai-lw** [yosupo06/library-checker-problems#716]
(任意) 問題ID: bell_number
問題名: Bell Number

Since there are problems for partition numbers and Stirling numbers of the second kind, it is natural to have Bell numbers as well.

(任意) 想定アルゴリズム: Use "Exp of Formal Power Series" to compute the following generating function
(任意) 参考資料: https://en.wikipedia.org/wiki/Bell_number#Generating_function

# 問題概要
Given an integer N, compute the k-th Bell number mod 998244353 for 0<=k<=N

## 入力

```
N
```

## 出力

```
B_0 B_1 ... B_N
```

## 制約
0<=N<=500000

**Comment by hos-lyric** [comment]
I think it is good to have this one.
(I have no idea whether o(N log N) ways is known or not.)
