### ISSUE TITLE
[問題案] Convolution(large)

### ISSUE THREAD

**Issue by NyaanNyaan** [yosupo06/library-checker-problems#720]
# 問題概要

Convolution (Large)

T 個のテストケースに答えてください。

整数 N, M, S が与えられます。
まず、以下の疑似コードにより長さ N の列 A, 長さ M の列 B を復元してください。

- 追記：コーナーケースを入れる必要性も考えると、入力は以下の乱数ではだめそう

```
state = S
for i = 0...N-1
    state = (state * 1103515245 + 12345) modulo 2^31
    a_i = state >> 2
for i = 0...M-1
    state = (state * 1103515245 + 12345) modulo 2^31
    b_i = state >> 2
```

次に

c_k = [x^k] (sum_i A_i x^i)(sum_j B_j x^j) mod 998244353

を満たす列 c_0,c_1, ..., c_{N+M-2} を計算して、すべての要素の xor を取ったものを出力してください。

## 入力

```
T
N_1 M_1 S_1
N_2 M_2 S_2
\dots
N_T M_T S_T
```

## 制約

- T <= 100
- N, M <= 2^{19}
- 0 <= S < 2^31
- 10 sec

https://judge.yosupo.jp/problem/convolution_mod は速度を計るにはテストケースが小さすぎる問題があり、実行時間のブレを減らすために制約が大きい版がほしくなったので立てました。(N <= 2^{22} にするみたいな案もありそう)

**Comment by defnotmee** [comment]
The constraints have a weird typo in it, it says 1 <= n, m <= 2^24 = 2^24.

I believe it's supposed to be either 1 <= n, m <= 2^24 or n, m = 2^24.

**Comment by maspypy** [comment]
Thank you for reporting it!
I will fix it. 
It was originally displayed as 「$\cdots=16777216=2^24$」, and now, the constant is automatically converted into exponential form.
