### ISSUE TITLE
[問題案]Sqrt of Formal Power Series(sqrt_of_formal_power_series)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#73]
母関数 $f(x) = \sum_{i = 0}^{N - 1} a_i x^i$ が与えられます。sqrt f(x) を求めてください。つまり

$f(x) = g(x) \times g(x) % (x^N)$ となる g(x)を出力してください

# 入力
```
N
a_0 a_1 a_2 ... a_{N - 1}
```

# 制約

- 1 <= N <= 500,000

# 出力

解答が存在しない場合
```
-1
```

```
b_0 b_1 ... b_{N - 1}
```

ただし g(x) = (exp_of_formal_power_seriesと同一)とする

#63

**Comment by yosupo06** [comment]
https://github.com/yosupo06/library-checker-problems/issues/63#issuecomment-532599639

**Comment by yosupo06** [comment]
一般的なライブラリでは以下の三種類

- 定数項を1と仮定する
- 定数項を非0の平方剰余数と仮定する
- 非 0 最低次の次数が偶数かつ係数が平方剰余 (上記コメント参照)

**Comment by yosupo06** [comment]
非 0 最低次の次数が偶数かつ係数が平方剰余 (上記コメント参照) これでいきます

**Comment by yosupo06** [comment]
sqrt mod持ってないから準備できねえ！笑

**Comment by hos-lyric** [comment]
sqrt_mod が準備できた理論により (過激思想)

**Comment by yosupo06** [comment]
sqrt_modの想定解のコードを流用することで準備に成功しました

**Comment by yosupo06** [comment]
https://twitter.com/beet_aizu/status/1176805868081307648

**Comment by yosupo06** [comment]
単項式を追加すると落ちるらしいので、追加
