### ISSUE TITLE
[問題案] (再起) Biconnected Components

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#731]
問題ID: biconnected_components
問題名: Biconnected Components

想定アルゴリズム:
参考資料:  
https://en.wikipedia.org/wiki/Biconnected_component  
https://github.com/yosupo06/library-checker-problems/issues/371

# 問題概要

無向グラフ（多重辺可、自己ループ不可）が与えられるので、biconnected components ごとに、含まれる辺の番号を出力。

## 入力

```
N M
u_0 v_0
u_1 v_1
:
u_{M-1} v_{M-1}
```

## 出力

1 行目は成分の個数 K を出力、次の K 行それぞれに辺集合を出力

```
L e_0 e_1 ... e_{L-1}
```

## 制約

- N,M \leq 500 000

--------------- 以下、検討 -----------------

## 他の出力形式は？

- 頂点集合 / 集合内で番号振り直し
  - 配列を使いまわして線形時間で生成できる
- block-cut tree
  - 頂点集合から生成できる
- 各辺が属する成分の番号 (例は [Edge Coloring of Bipartite Graph](https://judge.yosupo.jp/problem/bipartite_edge_coloring))
  - Two-Edge-Connected Components に倣うため
- 辺を (u,v) で出力
  - 外部の問題で重み付きだったときに不便になるうえ、出力量が微増する
  - 前例：どちらも可能な場合に、
    - 辺番号を出力 [Cycle Detection](https://judge.yosupo.jp/problem/cycle_detection)
    - 各辺が属する成分の番号を出力 [Edge Coloring of Bipartite Graph](https://judge.yosupo.jp/problem/bipartite_edge_coloring)
    - (u,v) を出力 [Shortest Path](https://judge.yosupo.jp/problem/shortest_path) 、 [Matching on Bipartite Graph](https://judge.yosupo.jp/problem/bipartitematching) 、 [Matching on General Graph](https://judge.yosupo.jp/problem/general_matching) 、 [Tree Diameter](https://judge.yosupo.jp/problem/tree_diameter)
    - (u,v) 出力のほうが前例は多い

## 自己ループは？

- 既存のライブラリで対応が分かれている?
  - 「biconnected components self loop」で検索
    - https://vtk.org/doc/nightly/html/classvtkBoostBiconnectedComponents.html
      > Self-loop edges that start and end at the same vertex are not assigned a biconnected component, and are given component id -1.
    - https://ogdf.uos.de/doc/group__ga-connectivity.html
      > Each self-loop is counted as one biconnected component and has its own component number.
- 入力から自己ループを線形時間で見つけて出力に追記するのは容易なので、ジャッジでは除外しても良いと考えています。

**Comment by NachiaVivias** [comment]
## 連結？
- うーん

**Comment by adamant-pwn** [comment]
@yosupo06 current intended solution is clearly wrong. On the test case `min01`, which is `5 0`, it outputs

```
4
1 1
1 2
1 3
1 4
```

but the actual answer clearly has `5` components, including `1 0`.

**Comment by maspypy** [comment]
will be fixed

https://github.com/yosupo06/library-checker-problems/pull/807

**Comment by SSRS-cp** [comment]
出力中の K とは何かの説明がありません
