### ISSUE TITLE
[問題案] prefix-substring LCS

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#732]
問題ID: prefix_substring_lcs
問題名: prefix-substring LCS

想定アルゴリズム: Alves, C. E. R., Cáceres, E. N., & Song, S. W. (2008). An all-substrings common subsequence algorithm. Discrete Applied Mathematics, 156(7), 1025-1035. O((ST + Q) log(T))

# 問題概要

文字列 S, T と Q 個のクエリが与えられる。

クエリ: S[0:a) と T[b:c) の最長共通部分列の長さを出力

## 入力

文字列 or 数列 (多分本質的に変わることは無い)

## 出力

ハッシュ化するか検討。

## 制約

|S|, |T| <= 10^3
Q <= 5 * 10^5

**Comment by yosupo06** [comment]
いい気がします

- (何も理解していません！)論文を流し読みした雰囲気、|S|はもっと大きくても平気だったりするでしょうか？
- 流石にsubstring-substring LCSは無理でしょうか

**Comment by noshi91** [comment]
・SETH を仮定すると LCS 自体が O(n^(2-ε)) にならないので、O((ST + Q) log(T)) で結構最適に近い気がします。定数倍もっと詰める話なら、実装してみて考えます。
・O(ST + QT) のアルゴリズムは存在するようです。Sakai, Y. (2019). A substring–substring LCS data structure. Theoretical Computer Science, 753, 16-34. prefix-substring は O(STlog(T) + Qlog(T)) なので上位互換ではないです
・OK です
・OK です

**Comment by yosupo06** [comment]
なるほど、では元の制約でよさそうです

**Comment by noshi91** [comment]
N = 0 や Q = 0 は許容しない方が良いですか？

**Comment by yosupo06** [comment]
> N = 0 や Q = 0 は許容しない方が良いですか？

はい(そこまで強い意見ではないんですが、現状多くの問題が許していないので)

**Comment by noshi91** [comment]
私がフォーマットの確認を忘れたからです。
