### ISSUE TITLE
[問題案] Static Range LIS Query

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#737]
問題名: Static Range LIS Query

想定アルゴリズム: Tiskin, A. (2008). Semi-local string comparison: Algorithmic techniques and applications. Mathematics in Computer Science, 1(4), 571-603.

# 問題概要

長さ N の順列 P と Q 個のクエリが与えられます。

- l r: P[l, r) の LIS の長さを出力

## 制約

N, Q <= 10^5

**Comment by yosupo06** [comment]
良さそうです
