### ISSUE TITLE
[問題案] Gcd Convolution

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#749]
問題ID: gcd_convolution

想定アルゴリズム: 整除関係に関するゼータ・メビウス変換
計算量: O(N\log\log N) あるいは O(N\log N)

# 問題概要
$a_1, \ldots, a_N$ と $b_1, \ldots, b_N$ が与えられる。
$c_k = \sum_{\gcd(i,j)=k} a_ib_j$ として、$c_1, \ldots, c_N$ を出力

## 制約
$1\leq N\leq 10^6$

----

作業の手間はほとんど変わらないので、ついでに lcm を作ってしまってもよい

**Comment by maspypy** [comment]
mod 998244353

**Comment by adamant-pwn** [comment]
https://codeforces.com/gym/102354/problem/B is somewhat related, perhaps...

**Comment by yosupo06** [comment]
LGTM

lcmだと出力長がO(n^2)になりませんか？

**Comment by maspypy** [comment]
(gcd) 近いうちに作ります。

(lcm) あー、勝手に N までの部分を出力する想定でいました。

Dirichlet 積を N 部分まで計算するような状況は珍しくない気がしますが、
lcm convolution のそれを見たことがあるかどうかは忘れました。
bit and/or が両方あるのでこれもかなと思ってたけど、lcm だけ定義がちょっと不自然なら微妙かな。
