### ISSUE TITLE
[問題案]Bernoulli Number(bernoulli_number)

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#75]
https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-534534502

$N$ が与えられます。ベルヌーイ数 B_0, B_1, B_2, ..., B_N を mod 998244353 で出力してください。

- 0 <= N <= 500,000

**Comment by yosupo06** [comment]
https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-534534502

**Comment by yosupo06** [comment]
これ母関数計算するだけなら一瞬で準備終わらないか？やるか

**Comment by yosupo06** [comment]
x / (exp(x) - 1)を俺のライブラリで計算したら愚直と違うものが出てきた

**Comment by hos-lyric** [comment]
ありがち：
- n! で割ってない
- exp(X) - 1 が可逆ではないために正しく割り算できてない

実は Bernoulli 数の流儀は符号が若干諸説あるらしい
B_0 から順に 1, -1/2, 1/6, 0, -1/30, 0, 1/42, ... が標準的なのかな

**Comment by yosupo06** [comment]
n!をかけたらうまく行き始めました　ありがとうございます
