### ISSUE TITLE
[Problem suggestion] Det A mod M

### ISSUE THREAD

**Issue by adamant-pwn** [yosupo06/library-checker-problems#750]
Example: https://acm.timus.ru/problem.aspx?space=1&num=1845

Algorithm: Gaussian elimination, but use extended Euclidean algorithm instead of division. (see also https://codeforces.com/blog/entry/98376)

Given `NxN` matrix `A = {a_ij}`, print `det(A) mod M`.

## input

```
N M
a11 a12 ... a1N
a21 a22 ... a2N
:
aN1 aN2 ... aNN 
```

## Constraint

`N <= 500, M <= 10^9`. `M` might be composite.

**Comment by yosupo06** [comment]
LGTM

Minor: Title should be "Determinant of Matrix (arbitrary mod)" or something (because "Determinant of Matrix" is already there)
