### ISSUE TITLE
Weak tests in Static Range LIS Query

### ISSUE THREAD

**Issue by EntropyIncreaser** [yosupo06/library-checker-problems#753]
[This code](https://judge.yosupo.jp/submission/75650) assumes that the length of LIS <= 1000 and get AC. Since the expected LIS of a random permutation is O(sqrt N), random data is not enough.

**Comment by dengyaotriangle** [comment]
Adding data where the given permutation is sorted, or nearly sorted (with only ~n inversions) should help.

**Comment by yosupo06** [comment]
#739
