### ISSUE TITLE
[問題案] Convolution (MergeTech)

### ISSUE THREAD

**Issue by physics0523** [yosupo06/library-checker-problems#763]
問題名: Convolution (MergeTech)

想定アルゴリズム: 畳み込みのマージテク

# 問題概要
整数係数の多項式 が N 個与えられるので、それらの積を mod 998244353 で求めよ。

## 入力
```
N
Poly_1
Poly_2
...
Poly_N
```

各多項式は以下の形式
```
M
A_0 A_1 ... A_{M-1}
```

## 出力
M-1 の総和を X として
```
B_0 B_1 ... B_X
```

## 制約
1 <= sum(M) <= 500000
0 <= A_i < 998244353

**Comment by yosupo06** [comment]
良さそうです

名前は Product of Polynomial Sequenceとかにしましょう
