### ISSUE TITLE
sum_of_totient_function のテストケースが弱い

### ISSUE THREAD

**Issue by hidesato-fujii** [yosupo06/library-checker-problems#764]
以下の2種類がほしいです

・N=1
(N//logN)^(2/3) や (N//loglogN)^(2/3) で上下に分けるときに0除算などで落ちます

・N=3000くらい
(N//logN)^(2/3)<N^(1/2) を満たすNのどれか
(N//logN)^(2/3) で上下に分けるときにindexの扱いに失敗すると落ちます

**Comment by yosupo06** [comment]
#384
