### ISSUE TITLE
[問題案] pow_of_formal_power_series (sparse)

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#767]
# 問題概要
疎な fps
$f = \sum_{i=0}^{K-1} a_ix^{b_i}$
が与えられる。$f^M \mod{x^N}$ を求めよ。

## 制約
- $1\leq N\leq 1000000$：pow of fps の 2 倍
- $1\leq M\leq 1000000000$：pow of fps と同じ
- $0\leq K \leq 5$
- $0\leq a_i < p$
- $0\leq b_0 < b_1 < \cdots < b_{K-1} < N$

## 解法、計算量
$g = f^M$ とする。$f_0\neq 0$としてよい。
$g' = Mf^{M-1}f'$ より $fg' = Mgf'$ が成り立つ。この $n$ 次部分を比べると、
$$(n+1) f_0 g_{n+1} = \text{（より小さな $g_i$ の線形結合）}$$
の形の式が得られる。係数ひとつあたり $O(K)$ 時間。全体で $O(NK)$ 時間。

## 参考情報
資料：https://atcoder.jp/contests/abc222/editorial/2742

なお、$f_0 = 1$ であるとき $M$ が負や有理数でも問題が定義できて、同じ式で計算できる。
（(1+ax)^{M} を線形時間でやってくれるだけでもちょっと便利？）

## 決めること
- $K$ の上限（普通の pow of fps：$O(N\log N) $ と見た目上差が出ると嬉しそう）
- $K=0$ を含めるか

**Comment by maspypy** [comment]
K乗が定義できていれば大丈夫なので、有理数乗（sqrt とか）もいける。

**Comment by maspypy** [comment]
関連
https://judge.yosupo.jp/problem/pow_of_formal_power_series

**Comment by maspypy** [comment]
あまり考えずに pow だけ立てたけれど、inv, log, exp とかも全部 sparse だと速くなりそう。（実用上も exp はあるといいかも。）
作業的には私が作れるやつ全部作ってもよいですが、pow も含めて、問題にするかどうか admin 判断に任せます。

**Comment by yosupo06** [comment]
ああこれ素ならなんでもいいんですね　fの最大次数が小さくないといけないのかと思っていました

Kの上限 => 切りよく(?)10とかでいいんじゃないでしょうか　https://judge.yosupo.jp/problem/pow_of_formal_power_series　の最速が180ms(=Nが二倍なら360ms)なので、流石に差はつくと思います

K=0は入れましょう　代わりにa_i != 0にしましょう　(ref https://judge.yosupo.jp/problem/sparse_matrix_det)

**Comment by yosupo06** [comment]
作業的には私が作れるやつ全部作ってもよいですが、pow も含めて、問題にするかどうか admin 判断に任せます。

全部あるなら入れていいと思います

**Comment by maspypy** [comment]
一応解説をここにおいておきます。係数を $f_i, g_i$ などと書きます。

全部、$O(NK)$ 時間で計算できます。

[inv of fps (sparse)]
$fg = 1$ とすると、$n\geq 1$ のとき $\sum_{0\leq i\leq n} f_ig_{n-i} = 0$ です。
$f_0g_n = -\sum_{0 < i\leq n}f_ig_{n-i}$ を用いて昇順に、各 $g_n$ が計算できます。
本問は $1/f$ ですが、より一般に、疎な fps で割る除算が同様の計算量でできます。

[log of fps (sparse)]
$(\log f)' = f'/f$ を inv of fps と同様に計算してから積分すればよいです。

[exp of fps (sparse)]
$F = \exp(f)$ とすると、$F_0 = 0$ かつ $F' = Ff'$ が成り立ちます。 
$F$ の $n-1$ 次が計算できているとき、右辺の $n-1$ 次が計算できます。したがって $F'$ の $n-1$ 次が計算できるので $F_n$ が計算できます。

[pow of fps (sparse)]
定数項が $1$ の場合に帰着しておきます。$F = f^M$ とすると、$fF' = MF$ です。$g = F'$ とすれば、
$n$ 次を比較すると、$\sum f_ig_{n-i} = MF_n$ より $g_n = MF_n - \sum_{i>0}f_ig_{n-i}$ となります。
$F$ が $n$ 次まで計算できていると、右辺が計算できて、$g_n$ が計算できて、$F_{n+1}$ が計算できます。

[sqrt of sps (sparse)]
定数項が $1$ の場合に帰着します。すると有理数乗が定義できて、$(f^{1/2})'=1/2f^{-1/2}$ も成り立つため、完全に pow of fps と同じ方法で計算できます。
