### ISSUE TITLE
[Problem proposal] Dynamic Range Frequency

### ISSUE THREAD

**Issue by ldct** [yosupo06/library-checker-problems#769]
You are given an integer sequence a_0, a_1, ..., a_{N-1} in order. Process the following Q queries:

-  `i, x`: set `a_i <- x`
- `l, r, x`: print the number of times that `x` occurs in `(a_l, ... a_r)`

**Comment by yosupo06** [comment]
LGTM

"Point Set Range Frequency" is suitable name in this online judge, because we already have the similiar problems, and should keep name rules.
- https://judge.yosupo.jp/problem/point_set_range_composite
- https://judge.yosupo.jp/problem/static_range_frequency

**Comment by maspypy** [comment]
作業者募集
