### ISSUE TITLE
[Problem Proposal] Static Range Count-Distinct

### ISSUE THREAD

**Issue by ldct** [yosupo06/library-checker-problems#770]
You are given an integer sequence a_0, a_1, ..., a_{N-1} in order. Process the following Q queries:

- `l, r, x`: print the number of distinct elements in `(a_l, ... a_r)`

**Comment by yosupo06** [comment]
LGTM

**Comment by maspypy** [comment]
作業者募集

**Comment by maspypy** [comment]
つくります
