### ISSUE TITLE
Biconnected Components の問題設定のバグ

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#773]
https://judge.yosupo.jp/problem/biconnected_components

問題文によると「二重連結成分の辺数」が 0 となる成分（つまり孤立点）があるが、出力から省かれていて矛盾している。（というか問題文を書いたのは私です。すみません。）

**Comment by maspypy** [comment]
孤立点は出力から省略せよ、とするのが、非破壊的で作業が少なさそう。
ただ K を出力させていて、これが成分数と不一致であるのは気持ち悪さがありますね。

出力が頂点列だと良くないことが起きるんでしたっけ。
「成分とは subgraph である」。というのを強調して
K
|V|, v1, v2, ...
|E|, e1, e2, ...
|V|, v1, v2, ...
|E|, e1, e2, ...
（1 + 2K 行）
を出力としてしまうのもよいと思います。

**Comment by NachiaVivias** [comment]
確かに（ $K$ のせいもあって）問題文だけの修正できれいにはできなさそうですね。

出力内容も変える場合は、ほかの問題に倣うという意味で頂点集合を出力させるのが良いと思っています。（良くないことが起こるから避けたとかではなく、 #731 がすべてです）

申し訳ありませんが、私が作業する場合は 7 月以降になりそうです。

**Comment by yosupo06** [comment]
ああ、二重連結成分=辺をグループ分けするもの　という認識でいたのですが、これだと孤立点が無視されるんですね

**Comment by yosupo06** [comment]
確かにKがよく知られた"二重連結成分の成分数"と違うのはよくなさそうです　破壊的変更になりますが出力形式を↑に変更しても大丈夫です
