### ISSUE TITLE
リファレンスの追加

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#79]
ちょっと想像よりはるかに意味不明なライブラリが増えてきて、検索したらパッと資料が出て来るみたいな感じじゃなくなってきたので、問題ごとになんらかへのリンクとかがあるとうれしそう

**Comment by kmyk** [comment]
これほしいです。
運用の楽さを考えると問題ページから問題案の issue へリンクを張るのがよい気がする (例えば https://judge.yosupo.jp/problem/unionfind から https://github.com/yosupo06/library-checker-problems/issues/33 へのように)

**Comment by yosupo06** [comment]
はい、issueへのリンクを貼ることにします　どういう風に貼るか(task.mdに直接markdownとして書く / {{example example_00}}のように{{ref #xx}}とか作る / issue番号をinfo.tomlかproblems.tomlで設定すると自動で貼られる　など)

**Comment by kmyk** [comment]
「issue の URL を `info.toml` に書いておくと自動でリンクが貼られる」を推したいです

根拠:

-   issue へのリンクが貼られる位置を細かく調整できるようにするよりも、手間が減ったり位置が統一されてくれた方がうれしい
-   URL の一部 (たとえば issue 番号の整数) だけをソースに書くのは、ソースからだと目的の URL に飛ぶのが面倒で不便になりがち
-   個々の問題ページの HTML を生成するのに必要な情報は `problems.toml` でなく `info.toml` に書かれてほしそう

**Comment by yosupo06** [comment]
遅れましたがこれにしました　ありがとうございます！
