### ISSUE TITLE
[problem suggestion] Polynomial factorization over Zp

### ISSUE THREAD

**Issue by adamant-pwn** [yosupo06/library-checker-problems#794]
Problem name: Polynomial factorization over $\mathbb Z_p$

Assumed algorithm: [Cantor–Zassenhaus algorithm](https://en.wikipedia.org/wiki/Cantor–Zassenhaus_algorithm)
Reference: https://codeforces.com/blog/entry/104318?#comment-926910

# Problem summary

Given a polynomial

$$
f(x) = a_0 + a_1 x + \dots + a_n x^n
$$

over $\mathbb Z_p$, where $p$ is prime number, find its factorization into irreducible polynomials:

$$
f(x) = f_1(x) \dots f_m(x).
$$

## Input

```
n p
a0 a1 ... an
```

## Output

Output the number of divisors $m$, and then the divisors coefficients, one in each row.

## Constraints

$2 \leq p \leq 10^9$ and $n \leq 10^3$, perhaps, $p$ is prime.

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/94

**Comment by maspypy** [comment]
close because duplicated with #94
