### ISSUE TITLE
[問題案] Rooted Tree Isomorphism Classification

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#796]
問題名: Rooted Tree Isomorphism Classification （ "Isomorphism" はいらないかも ）

想定アルゴリズム: 小さい順に ID を振る
参考資料: https://atcoder.jp/contests/nikkei2019-2-final/tasks/nikkei2019_2_final_d

# 問題概要

## 入力

N 頂点の根付き木

## 出力

N 個の非負整数 A[i] (< N)

頂点 i の部分木と頂点 j の部分木が根付き木として同型 iff A[i] == A[j]

## 制約

1 <= N <= 500 000

## 備考

木ハッシュという話題もある

O(N) もある（ AHU algorithm → SA-IS, LCP array ）が、遅い

この手の問題が AtCoder （有志,企業コン）に 3 回出た

- [木、](https://atcoder.jp/contests/nikkei2019-2-final/tasks/nikkei2019_2_final_d)
- [Set of Trees](https://atcoder.jp/contests/xmascon19/tasks/xmascon19_k)
- [Lexicographic Euler Tour](https://atcoder.jp/contests/nadafes2022_day1/tasks/nadafes2022_day1_l)

私は AHU algorithm のオリジナルの文献にアクセスできていません

この種類の部分木をまとめてどう呼べばよいのか私は知りません

**Comment by maspypy** [comment]
出題形式等の議論がすこしあります。作業がされる様子はないので無視しても良いと思います。↓

https://github.com/yosupo06/library-checker-problems/issues/246

**Comment by yosupo06** [comment]
この出力形式いいですね　最初に種類数Kも出したいです
