### ISSUE TITLE
[問題案] Longest Increasing Subsequence

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#803]
問題ID: longest_increasing_subsequence
問題名: Longest Increasing Subsequence

# 問題概要
長さ N の数列 a_0, a_1, ..., a_{N-1} が与えられるので、最長増加部分列の長さを求め、その長さの増加部分列を 1 つ答える。

## 入力

```
N
a_0 a_1 ... a_{N-1}
```

## 出力
K: LIS の長さ
i_0, i_1, ..., i_{K-1}: 添字
i_0<i_1<...<i_{K-1}, A_i_0<A_i_1<...<A_i_{K-1}

```
K
i_0 i_1 ... i_{K-1}
```

## 制約
1 <= N <= 500000
1 <= a_i <= 10^9

**Comment by yosupo06** [comment]
良さそうです
