### ISSUE TITLE
[問題案] Range Xor-Min

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#805]
問題ID: range_xor_min
問題名: Range Xor Min

想定アルゴリズム: ソートされた列を載せる Binary Trie
参考資料: https://heno239.hatenablog.com/entry/2018/12/20/135141

# 問題概要
長さ N の数列 a_0, a_1, ..., a_{N-1} がある。
Q 個のクエリが与えられる。各クエリでは l, r, x が与えられるので、min{a_i xor x | l≦i<r} を出力する。

## 入力

```
N Q
a_0 a_1 ... a_{N-1}
l_0 r_0 x_0
l_1 r_1 x_1
...
l_{Q-1} r_{Q-1} x_{Q-1}
```

## 出力
各クエリに対し 1 行

## 制約
1≦N≦200000
0≦A_i<2^30
0≦l<r≦N
0≦x<2^30

## メモ
#499 に似ているのでいらないかもしれないです
計算量が A_i, X の最大桁数を D として Θ(NDlogN) で重めなので、制約の調整が必要

**Comment by yosupo06** [comment]
wavelet系でlog 1個ではないですか？
