### ISSUE TITLE
[問題案] Jump on Tree

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#809]
(任意) 問題ID: {ID}
問題名: {名前}

# 問題概要
木が与えられる。次を $Q$ 個求めよ。

- $u$ $v$ $x$：$u$ から $v$ に距離 $x$ 進んだ頂点

距離は辺重みを $1$ としたもの。

制約：$0 \leq x \leq N - 1$

## 検討事項
- $d > dist(u, b)$ は $-1$ を出力 OR 制約ではじく
    → テストケース作りを考えると、$-1$ を出力の方が楽なので、そっちで。
- 問題名

話題になっていたので立てました、ので需要はありそう。

**Comment by maspypy** [comment]
https://twitter.com/SSRS_cp/status/1548355109129977856?s=20&t=D0YHSpu29zN1E379m29SFw

**Comment by maspypy** [comment]
Jump on Tree とかでいいのかしら。

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/617

を真に含んでいる。個人的には Level Ancestor を作らないことにしてしまってよいのではないかと。

**Comment by SSRS-cp** [comment]
Dynamic Tree 版も需要があるかもしれません
