### ISSUE TITLE
generate.py の動作要件を明示してほしい

### ISSUE THREAD

**Issue by kmyk** [yosupo06/library-checker-problems#81]
`generate.py` の動作のための条件を明示してほしいです。
利用にあたって「Python 3.6 なら動くのか Python 3.7 が必要なのかよく分からない」「`g++` さえあればよいと思っていたが、実は `dmd` も必要だった」「Windows でも動くと思ってたけど path まわりでこけて落ちる」みたいなのがあると困るためです。

**Comment by yosupo06** [comment]
書きました、現状のプランでは将来的にもpython3, pip3, C++以外を要求するつもりはないです

**Comment by kmyk** [comment]
ありがとうございます。確認しました
