### ISSUE TITLE
[問題案] min_of_mod_of_linear

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#813]
問題名：min_of_mod_of_linear

## 問題
（案1）
$f(x) = ax+b \bmod m$ とする. $L\leq x < R$ における $f$ の最小値を出力せよ。

（案2）
$f(L), \ldots, f(x-1) > f(x)$ を満たす $x$ 全体は $O(\log m)$ 個の等差数列の和集合である。この等差数列を適当な形で出力させる。

##  制約・入力

https://judge.yosupo.jp/problem/sum_of_floor_of_linear に準ずる。

合わせるなら、$(L, R) = (0, N)$ でもよい。
(案2) なら、$(L, R) = (0, \infty)$ として入力は $a, b, m$ だけにしてしまうとよい。

## 案2 の補足
例えば、3x+6 mod 10 なら、
[(0,6), (2,2)]
[(2,2), (5,1), (8,0)]
のように 2 つの等差数列に分かれる。個人的には verify したいものは (案2) であるが、出力を説明したりするのも面倒なので (案1) でよいという気がする。

## 出題例
<details>
https://atcoder.jp/contests/arc127/tasks/arc127_f
https://codeforces.com/contest/1182/problem/F
<summary>
min のみ欲しい
</summary>
</details>

<details>
https://atcoder.jp/contests/agc045/tasks/agc045_f
<summary>
等差数列への分解も欲しい
</summary>
</details>

**Comment by yosupo06** [comment]
案1よさそうです, `ans(a, b, m, L, R) = ans(a, aL + b, m, 0, R-L)`ですか？だったらさすがにL = 0でいい気がします。

案2は答えが一意じゃないような気がしていて、ちゃんとcheckerがかけるのかすらよくわかっていません
