### ISSUE TITLE
[問題案] Deque Operate All Composite

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#815]
問題名: Deque Operate All Composite
問題ID: deque_operate_all_composite

## 問題

長さ $0$ (一次)関数の列 $f = ()$ があります。$Q$ 個のクエリが飛んできます。処理してください。

`0` $a\ b$ : 列 $f$ の先頭に一次関数 $\lambda x. ax + b$ を追加する
`1` $a\ b$ : 列 $f$ の末尾に一次関数 $\lambda x. ax + b$ を追加する
`2`: 列 $f$ の先頭の一次関数を削除する
`3`: 列 $f$ の末尾の一次関数を削除する
`4` $x$: $f = (f_{l}, \dots, f_{r - 1})$ として $f_{r-1}(f_{r-2}(\cdots(f_{l}(x))\cdots)) \bmod998244353$ を出力する。$f = ()$ の場合は $x$

##  制約

実測はしていないですが、とりあえず [Queue Operate All Composite](https://judge.yosupo.jp/problem/queue_operate_all_composite) と同じ制約です。

- $1 \leq Q\leq 5\times 10^5$
- $1 \leq a \lt998244353$
- $0 \leq b, x \lt998244353$
- クエリ 2, 3 が来るとき、列 $f$ は空ではない

## 想定解 / 参考資料

SWAG の内部で用いる two-stack queue を two-stack deque に変える。

- SWAG の参考資料 : https://motsu-xe.hatenablog.com/entry/2021/05/13/224016
- two-stack deque の参考資料 : https://www.slideshare.net/catupper/amortize-analysis-of-deque-with-2-stack

## 入力

```
Q
Query_1
:
Query_Q
```

## Note

作業はできないと思います

**Comment by yosupo06** [comment]
よさそうです
