### ISSUE TITLE
[問題案] Vertex Add Range Contour Sum On Tree

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#816]
問題名: Vertex Add Range Contour Sum On Tree
問題ID: vertex_add_range_contour_sum_on_tree

## 問題

$N$ 頂点の木 $T$ が与えられる。 $T$ の $i$ 番目の辺は $u_i$ と $v_i$ を双方向に結ぶ重み $1$ の辺である。また、各 $i = 0, \ldots, N-1$ に対して、頂点 $i$ には整数 $A _ i$ が書かれている。以下の形式で表されるクエリが $Q$ 個与えられるので、順番に処理せよ。

- `1` $v\ x$ : 頂点 $v$ に書かれた値に $x$ を加算する。即ち、 $A _ v \leftarrow A _ v + x$ とする。
- `2` $v\ l\ r$ : 頂点 $v$ からの距離が $l$ 以上 $r$ 未満の頂点に書かれた値の総和を出力する。

##  制約

- $1 \leq N \leq 200000$
- $1\leq Q \leq 200000$
- $0 \leq A _ i \leq 10 ^ 9$
- $0 \leq u_i, v_i \lt N$
- $0 \leq v \lt N$
- $0 \leq x \leq 10 ^ 9$
- $0 \leq l \lt r \leq N$
- $T$ は木である

## 想定解

重心分解で < $\Theta(N \log N)$ , $\Theta((\log N) ^ 2)$ >

- [重心分解で 1 点更新区間取得](https://noshi91.hatenablog.com/entry/2022/03/27/042143)

## 入力

```
N Q
A_0 ... A_{N-1}
u_0 v_0
:
u_{N-2} v_{N-2}
Query_1
:
Query_Q
```

## 問題例

- https://atcoder.jp/contests/yahoo-procon2018-final-open/tasks/yahoo_procon2018_final_c (更新無し / 区間取得)
- https://atcoder.jp/contests/joisc2022/tasks/joisc2022_h (1 点取得 / 区間作用)
- https://yukicoder.me/problems/no/1038 (1 点取得 / 区間作用)

## Disucussion

- 問題名は適切か
  - Contour Sum という用語に根拠はありません
- 前計算の $\log$ が $1$ つ増えますが、辺を重み付きにもできます
  - ただ、辺重み無しの $\Theta(N \log N)$ の時点で定数倍がかなり重そうです
- 畳み込む演算は可換モノイドであればよいのですが、~~$\min$ が適切かどうかは分かっていません~~ 一点加算・総和取得に変更しました
  - ~~$\mathrm{mod}\ m$ の総積など?~~
- 制約は要調整です
  - $N=200000, Q=400000$ の https://atcoder.jp/contests/joisc2022/tasks/joisc2022_h で 2~4 秒程度です

## Note

- ~~作業は出来ないと思いますが、(辺重みなし版の) 想定解は持っているので提供できます~~ 作業します。
  - https://suisen-cp.github.io/cp-library-cpp/library/tree/range_contour_aggregation_query_on_tree.hpp

**Comment by SSRS-cp** [comment]
min はテストケースが作りにくそうです。
逆元を消す必要はありますか？なければ単純に一点加算と総和取得でも良いと思いました

**Comment by suisen-cp** [comment]
確かに、無理に逆元を消す理由は無いですね。可逆性を仮定する解法の verify にもなりますし、一点加算・総和取得でよい気がしてきました

**Comment by yosupo06** [comment]
よさそうです
