### ISSUE TITLE
[問題案] スターリング数 （small p, large n）

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#817]
## 問題
素数 $p$ が与えられる。$Q$ 回次を解け：$s(n,k) \bmod p$ を求めよ。

## 制約
- $p\leq 5000$、素数
- $0\leq k\leq n\leq 10^{18}$

## 資料
解説を書きました。https://maspypy.com/stirling-%e6%95%b0%e3%82%92-p-%e3%81%a7%e5%89%b2%e3%81%a3%e3%81%9f%e4%bd%99%e3%82%8a%e3%81%ae%e8%a8%88%e7%ae%97

第 1, 2 種ともに、$O(p^2)$ 前計算のもと、クエリごとに $O(\log_pn)$ 時間でできる。

## 揉めどころ
同じ問題の制約違いの類を、どのくらい作問するのか、どういう問題名で置くのか
みたいなのはこの問題に限らず今後出てきそうな話だという気がする。

**Comment by maspypy** [comment]
stirling_number_of_the_first_kind_a
stirling_number_of_the_first_kind_b
みたいな作問を許容してしまうのも手軽かもしれない

**Comment by SSRS-cp** [comment]
Q の制約が書かれていないですが、実測して調整する感じですか？

**Comment by maspypy** [comment]
https://judge.yosupo.jp/problem/binomial_coefficient
に合わせて T = 200000 とかで。

**Comment by yosupo06** [comment]
よさそうです

問題タイトルは難しいんですが、とりあえずstirling_..._small_p_large_nでどうでしょう(..._a, ..._bよりは情報量があるので)
