### ISSUE TITLE
[問題案] Point Set Range Sort Range Composite

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#818]
# 問題
ソートキーとなる整数 $p$ および、$1$ 次関数 $f = ax+b$ の組 $(p_i, f_i)$ が与えられる。
$Q$ 個のクエリを処理せよ。

- 0 i p a b：$(p_i, f_i)$ を $(p, ax+b)$ に変更
- 1 l r x：合成して x を代入
- 2 l r：$l\leq i < r$ に対する $(p_i, f_i)$ を $p_i$ が昇順となるようにソートする
- 3 l r：$l\leq i < r$ に対する $(p_i, f_i)$ を $p_i$ が降順となるようにソートする

# 制約
- $1\leq N, Q\leq 10^5$
- $0\leq p \leq 10^9$、初期値およびクエリ 0 での値がすべて distinct
- あとは [Point Set Range Composite](https://judge.yosupo.jp/problem/point_set_range_composite) に準ずる

# 解法
空間 $O((N+Q)\log N)$、時間 $O((N+Q)\log N)$
ソートされた区間ごとに、動的セグ木をひとつ持って、これを split, merge する。
もうひとつセグ木を用意して、ソートされた区間の区間積を管理する。

# 参考資料
https://codeforces.com/blog/entry/49446

# 出題例
https://ac.nowcoder.com/acm/contest/33186/F

**Comment by maspypy** [comment]
Point Set も入れようか。

**Comment by yosupo06** [comment]
point setするならpも変更したい気がします　問題全体で出てくるpが重複しないみたいな制約で
