### ISSUE TITLE
[問題案] Vertex Get Range Contour Add On Tree

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#831]
問題名: Vertex Get Range Contour Add On Tree
問題ID: vertex_get_range_contour_add_on_tree

#816 の双対 (?)

## 問題

$N$ 頂点の木 $T$ が与えられる。 $T$ の $i$ 番目の辺は $u_i$ と $v_i$ を双方向に結ぶ重み $1$ の辺である。また、各 $i = 0, \ldots, N-1$ に対して、頂点 $i$ には整数 $A _ i$ が書かれている。以下の形式で表されるクエリが $Q$ 個与えられるので、順番に処理せよ。

- `1` $p$ : 頂点 $p$ に書かれた値を出力する。
- `2` $p\ l\ r\ x$ : 頂点 $p$ からの距離が $l$ 以上 $r$ 未満の頂点に書かれた値に $x$ を加算する。

##  制約

- $1 \leq N \leq 100000$
- $1\leq Q \leq 200000$
- $0 \leq \vert A _ i \vert \leq 10 ^ 9$
- $0 \leq u_i, v_i \lt N$
- $0 \leq p \lt N$
- $0 \leq l \lt r \leq N$
- $0 \leq \vert x \vert \leq 10 ^ 9$
- $T$ は木である

## 想定解

#816 と同様にして < $\Theta(N \log N)$, $\Theta( (\log N) ^ 2)$ >

## 入力

```
N Q
A_0 ... A_{N-1}
u_0 v_0
:
u_{N-2} v_{N-2}
Query_0
:
Query_{Q-1}
```

## Note

- goサインが出れば準備します

**Comment by yosupo06** [comment]
せっかくなら1/3重心分解(正式名称、知らず…)を登場させたい気持ちもあるものの、特に問題案を知らず

**Comment by maspypy** [comment]
↑これは
単に重心分解＋bfsだと、o 可換群 x可換モノイド となるので、逆元のないモノイドを扱うときに重心分解を二分木で表現しなおす実装が欲しいときがあって、それだと思います。（合っていますか？木に強い人）
関連
https://noshi91.hatenablog.com/entry/2022/03/27/042143
https://codeforces.com/blog/entry/104997 の最後

逆元を仮定しない問題を別に作るというのはありだと思います。

それはともかくとして、本問は作ってしまって良いと個人的には思っています。
（別の問題を作るかと言うより、次の問題との重複と見なすかどうかかな）
https://judge.yosupo.jp/problem/vertex_add_range_contour_sum_on_tree

**Comment by maspypy** [comment]
作問するで大丈夫です。

@suisen-cp 
だいぶ時間が経ってしまっていますが、準備する意思ありますか？

**Comment by suisen-cp** [comment]
1-2週間ほど先で良ければ作業します
