### ISSUE TITLE
[問題案] Furthest Pair of Points

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#837]
問題名: Furthest Pair of Points
#836 の最大値バージョン

## 問題
座標平面上に $N$ 個の点がある。$i$ 番目の点の座標は $(x_i, y_i)$ である。距離が最も大きい $2$ 点間の距離と、それらの番号を出力せよ。

## 入力
N
x_0 y_0
x_1 y_1
...
x_{N-1} y_{N-1}

## 出力
ans
i j

## 制約
2≦N≦500000
|x_i|, |y_i|≦10^9

## メモ
・座標を distinct にするか (#836 と揃えたほうがよさそう)
・許容誤差は？
・[嘘解法](https://twitter.com/hogloid/status/852395642991390721) を落とす

**Comment by maspypy** [comment]
少なくとも当面は、小数出力は厳しそうなので、作るなら頂点番号2つ出力でお願いします。
