### ISSUE TITLE
[問題案] Shortest Walk (with negative edges)

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#843]
## 問題名
辺重みのある (N, M) 有向グラフが与えられる。辺重みは非負とは限らない。

始点 $s$ が与えられる。N 行出力。各 $v$ に対して、次を出力

- walk がひとつも存在しない場合：`NONE`
- 最短路長が存在する場合：最短長
- いくらでも小さい walk が存在する場合：`-INFINITY`

## 制約
(3000,3000) くらい？

## 解法
Bellman Ford / SPFA

## 検討
- 問題名 
- 出力

**Comment by SSRS-cp** [comment]
最短路を o(NM) で求められるらしいというのを置いておきます (細かく読んでいないので、-INF の判定ができるかはわかりません)
[https://misawa.github.io/others/flow/cost_scaling_shortest_path.html](https://misawa.github.io/others/flow/cost_scaling_shortest_path.html)

**Comment by SSRS-cp** [comment]
``-INF`` は #211 に合わせて ``-INFINITY`` のほうがよいかもしれません

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/shortest_path

これに合わせるならs -> tでパスを構築させることになりそう

**Comment by maspypy** [comment]
・距離を出力
整数 OR `NONE` OR `-INFINITY`
整数の場合：https://judge.yosupo.jp/problem/shortest_path と同じ形式でパスを出力

これで。

**Comment by maspypy** [comment]
duplicate with #969
