### ISSUE TITLE
Help に 「ICE」 の説明がない

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#848]
https://judge.yosupo.jp/help
https://judge.yosupo.jp/submissions/?problem=common_interval_decomposition_tree&user=&status=&lang=&order=%2Btime&page=0&pagesize=100

**Comment by yosupo06** [comment]
忘れていました　ありがとうございます　というかICEはchecker.cppがコンパイルエラーということなので何らかの修正が必要ですね…　#744
