### ISSUE TITLE
#850 のケースがジャッジに適用されない

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#853]
2022/8/24～ Dynamic Graph Vertex Add Component Sum のジャッジに #850 で追加したケースが含まれておらず、具体的には

- rejudge 含むジャッジ
- 緑/青ACの判定

において含まれない様子を確認しました。

一方で、その現象を確認した後 verification-helper で呼び出すと当該ケースもロードされたため、ケースが存在しないわけではないようです。

**Comment by NachiaVivias** [comment]
850 は一旦 revert したほうがよいでしょうか？

**Comment by maspypy** [comment]
含まれるようになっている気がする

**Comment by NachiaVivias** [comment]
含まれるようになっていますね（ちょうど、さらに新しいケースが追加されたときからでしょうか）

**Comment by yosupo06** [comment]
一度に一気にMRをマージすると(例: MR1 -> MR2)、MR1の後の状態でテストケースをアップロードするスクリプトとMR2の後の状態でテストケースを生成してアップロードするプログラムが並列で走って、運によってはMR1の後の状態のがアップロードされてしまう感じっぽいです
