### ISSUE TITLE
Chromatic Number の無向グラフの指定について

### ISSUE THREAD

**Issue by dum-601** [yosupo06/library-checker-problems#854]
[Chromatic Number](https://judge.yosupo.jp/problem/chromatic_number) を解いていて思ったのですが、 与えられるグラフについての記述が "Given a simple graph with N vertices and M edges. i-th edge is u_i, v_i" となっており、有向グラフか無向グラフか明示的に指定されていません。（M <= N(N - 1) / 2 から、無向グラフであることは推察できますが）

Graph カテゴリの他の問題と同様に、グラフが有向か無向かを明示的に指定したほうが、親切ではないでしょうか。

**Comment by dum-601** [comment]
ご対応ありがとうございます。ついでですが、[Maximum Independent Set](https://judge.yosupo.jp/problem/maximum_independent_set) や [
Matching on Bipartite Graph](https://judge.yosupo.jp/problem/bipartitematching) にも同じことがいえそうです。

**Comment by SSRS-cp** [comment]
有向・無向が明記されていない問題の一覧を作っておきます
・K-Shortest Walk
・Minimum cost b-flow
・Matching on General Graph
・Edge Coloring of Bipartite Graph

**Comment by dum-601** [comment]
K-Shortest Walk と、 Minimum cost b-flow に関しては、"directed from vertex a to vertex b" のような形で表記されていますが、これは有向グラフであると思ってよいのではないでしょうか？

**Comment by SSRS-cp** [comment]
Shortest Path で directed from... と書いてありますが directed graph と明記されているので、揃えたほうがよいと思いました。

**Comment by dum-601** [comment]
確かに、表記をそろえるのが一番いいですね。私もそれに賛成です。

**Comment by maspypy** [comment]
あまり統一みたいなところを頑張りすぎると大変になるので、ある程度ゆるくやっていくのが良いと思いますが、それほど頑張らずに出来そうだったのでやりました。

**Comment by dum-601** [comment]
ご対応ありがとうございました！

ひと段落ついたようなので、ここで close します。
