### ISSUE TITLE
[問題案] Connected Components of Complement Graph

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#865]
問題名: Connected Components of Complement Graph

## 概要
$N$ 頂点 $M$ 辺の単純無向グラフ $G$ が与えられる。$G$ の補グラフを連結成分に分解せよ。

## 入力
いつもの

## 出力
#366 などと同様？

**Comment by yosupo06** [comment]
出力形式は
K
連結成分1
連結成分2
:
連結成分K
でお願いします(二重辺連結成分のほうは辺を出すとかで色々あったんですが、こっちは出力するものが簡潔なので

**Comment by maspypy** [comment]
作業者募集
