### ISSUE TITLE
Tree Diameter に対する Hack Case

### ISSUE THREAD

**Issue by Kazun1998** [yosupo06/library-checker-problems#868]
Hack Code: https://judge.yosupo.jp/submission/104538
(特定の頂点を端点とする最長パスの長さを求め, Rerooting によって最大値をとる2頂点が最長パスの両端)

Hack Case
```
4
0 1 100
0 2 1
0 3 1
```

Example of Expected Output
```
101 3
1 0 2
```

Output of Hack Code
```
101 3
2 0 3
```
( $\operatorname{dist}(2,3)=2$ )

Reason
次の誤った理論を用いている.
- $u$ を端点とする最長 Path が存在し, $v$ を端点とする最長 Path が存在するならば, $u,v$ Path も最長 Path になる.

**Comment by maspypy** [comment]
Hack Case として提供されたものをそのままひとつ足します
