### ISSUE TITLE
[問題案] Cycle Detection (Undirected)

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#869]
https://judge.yosupo.jp/problem/cycle_detection

の無向グラフ版。多重辺あり、ループなし。

**Comment by maspypy** [comment]
出力をどうするか。辺の列から頂点の列を得るのが少し非自明なので、辺の列を出力させるのが使いやすいとは言えない。

**Comment by yosupo06** [comment]
難しいところですが、
(辺番号) u v
(辺番号) u v
:
(辺番号) u v
を出力とかでしょうか
