### ISSUE TITLE
[Problem proposal] Double-Ended Priority Queue

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#874]
Problem name: Double-Ended Priority Queue
(Optional) Problem ID: double_ended_priority_queue

## Problem

多重集合 $S = \\{S_1, \ldots, S_N\\}$ が与えられる。以下の形式のクエリを順に $Q$ 個処理。

- `1 x`: $S$ に $x$ を追加
- `2`: $S$ に含まれる最小の要素を出力して $S$ から除く
- `3`: $S$ に含まれる最大の要素を出力して $S$ から除く

##  Constraint

- $0\leq N\leq 5\times 10 ^ 5$
- $0\leq Q\leq 5\times 10 ^ 5$
- $-10 ^ 9 \leq S _ i, x \leq 10 ^ 9$

## Solution / Reference

Interval Heap

- https://natsugiri.hatenablog.com/entry/2016/10/10/035445

Priority Queue 2 本

- https://twitter.com/0x3b800001/status/1575295046399979520?s=20&t=8LgpEc_d5J3QWPWbvKbwEg

## Input

```
N Q
S_1 ... S_N
Query_1
:
Query_Q
```

## Note

#832 と仕様を合わせる

**Comment by yosupo06** [comment]
良さそうです
