### ISSUE TITLE
[問題案]形式的冪級数での様々な操作

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#88]
種類が多すぎるので分離

- 加算, 減算: とりあえず省略
- 乗算: #42
- 除算: #120 
- exp: #65 
- log: #66 
- sqrt: #73 
- 合成: ???

exp, log, sqrt: https://github.com/yosupo06/library-checker-problems/issues/63
除算, 合成: https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-530915524

**Comment by chaemon** [comment]
P(x)^k (kは10^5など大きいものを想定)を計算するテストを追加していただきたいです。

**Comment by yosupo06** [comment]
合成: https://judge.yosupo.jp/problem/composition_of_formal_power_series
