### ISSUE TITLE
[問題案] Stern Brocot Tree

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#888]
# 概要
いくつかの種類の問題が T 回与えられるので、すべて解く。

- `ENCODE_PATH a b`
SBT において、1/1 から a/b までのパスを `LR` 文字列で表して、その連長圧縮を出力
- `DECODE_PATH k c_1 n_1 c_2 n_2 ... c_k n_k`
連長圧縮されたパスの情報から、有理数を復元して出力。答が $10^9$ 以下であることは保証。
- `LCA a b c d`
SBT において、lca(a/b,c/d) を出力
- `CHILD a b`
SBT において a/b の左の子・右の子を出力
- `ANCESTOR k a b`
SBT a/b の 深さ k の祖先の出力、なければ `-1`
- `RANGE a b` 
頂点 a/b の部分木は、ある有理数開区間である。その両端を出力
# 資料
https://en.wikipedia.org/wiki/Stern%E2%80%93Brocot_tree

# 解法
SBT を top down に探索する or 互除法で $a/b$ の親を探す（これらは実質的には同じはず）と、対数時間でパスが手に入る。パスを連長圧縮すると、長さは log でおさえられるので、これを heavy path みたいに扱うことで、LCA や LA なども対数時間

# 制約
- $T\leq 10^5$
- $1\leq a,b\leq 10^9$ かつ互いに素。

# 関連：
https://github.com/yosupo06/library-checker-problems/issues/24
↑これライブラリにしておきたい状況が分からなかったんですが、SBT での LCA という想定でしたか。

他に欲しい機能があれば、簡単なものなら 1 問にまとめてしまってよいと思う。

# 検討
`LCA a b c d` みたいな形式 or `0 a b c d` みたいな形式

**Comment by SSRS-cp** [comment]
PATH の逆はどうでしょう
(1/1 から a/b までのパスを LR 文字列で表した文字列の連長圧縮が与えられるので、a, b  を出力)

**Comment by maspypy** [comment]
資料 https://en.wikipedia.org/wiki/Stern%E2%80%93Brocot_tree

**Comment by maspypy** [comment]
`RANGE a b` 頂点 a/b の部分木は、ある有理数半開区間である。その両端を出力

**Comment by SSRS-cp** [comment]
> 頂点 a/b の部分木は、ある有理数半開区間である。その両端を出力

開区間だと思います

**Comment by SSRS-cp** [comment]
```PARENT a b``` (a/b の親を出力) はどうですか

**Comment by NachiaVivias** [comment]
作業やる宣言だけしておきます。

**Comment by NachiaVivias** [comment]
https://github.com/NachiaVivias/library-checker-problems/tree/stern-brocot/math/stern_brocot_tree

プレビューです。

**Comment by NachiaVivias** [comment]
気になるポイント

- ジェネレータが多い（コーナーケースを入れるなら、もっともっと増える予定）
- CHILD の出力に現れる値のみ制約が $10^9$ ではない。（そこで制約をかけるとコーナーが面倒くさいことになるかも）
- RANGE の出力に 0 や inf が現れる場合がある
- RANGE と CHILD は類似で、両方 verify する必要性は薄そう。
- PARENT は RANGE に近いが、入れたほうがよいか？
- 問題文の加減
- correct.cpp と突き合わせられるのがあると嬉しいです。

**Comment by maspypy** [comment]
(3) 気になるなら、この問題では 「1/0」 を出力させるというのも自然だと思います。
(7) 「tester解」を提供することはできると思います。

**Comment by NachiaVivias** [comment]
> (7) 「tester解」を提供することはできると思います。

お願いしたいです。完成まで期間がかかりそうなので、その間にできるだけ検証しておきたいです。

- (8) （ (2)(4) に追記）やはり CHILD の重要性（ RANGE がある限り、ほぼ 0 だと思う）よりも CHILD を用意するぶんの面倒さが大きいと感じます。特にほかの意見が出なければ CHILD クエリを削除して準備するつもりです。

**Comment by maspypy** [comment]
child って、range と足し算するだけですよね、よいと思います。parent も要らないと思います。
