### ISSUE TITLE
[問題案] Rank of Matrix

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#893]
## 概要
$\mathbb{F}_{998244353}$ を成分とする $N\times M$ 行列の階数を出力せよ。

- $NM\leq 250000$

## 解法
行列の基本変形。$O(NM\cdot \min(N, M))$ 時間。

LC driven なライブラリ整備をしていたら、これが手元になくてすこし慌てた。
上位版の system_of_linear_equations がある。

**Comment by hitonanode** [comment]
$N, M \le 500$ の部分について、 $1 \le NM \le 2.5 \times 10^5$ とかの制約にしておいたほうが、無自覚に $O(N^2 M)$ や $O(N M^2)$ になってしまっている実装を落とせて助かる人もいるかもしれないと思いました（system of linear equations だと答えのサイズが爆発しうるんですが、rank なら整数一個答えるだけなので......）。

**Comment by maspypy** [comment]
やります
