### ISSUE TITLE
[問題案] Static Convex Hull (2 dimensional) 

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#897]
https://github.com/yosupo06/library-checker-problems/issues/808 の弱い版

# 問題概要
N 個の点を入力として与える。
凸包の頂点列を反時計回りに出力せよ。

# 検討
- 辺上の端点以外の点を含めて？外して？出力

----
点を含んでいるかとか、面積はとか、そういうのは必要なら、多角形に対する何かを問う問題を別に作ればよいと思う。

**Comment by NyaanNyaan** [comment]
辺上の端点以外の点は外す方が一般的だと思っています。(が、たまに含める方を要求する問題があり、そちらも欲しいため少し悩ましい…)
同じ位置に複数はあった方がよさそう。
index は(辺上の点と違って)必要になったら map で復元可能だと思うのでどちらでもよさそうに感じました。

**Comment by noshi91** [comment]
index の計算を使う場面はあるので、「index も一緒に計算するライブラリが、座標は合っているけど index は間違っているというようなバグを踏みうるか」というのが論点になるかもしれません。
座標を出力させると、点が重複しているときにどちらの点を出力するのかという問題が起きないので楽ですが、どの点を始点にするかという部分でどのみち特殊ジャッジになるので実は嬉しくないかもしれない？

**Comment by KentaroMatsushita** [comment]
index は Nyaan さんがおっしゃってるように復元は簡単なのに対して要らないときにも余計なデータをもたせるような構造になってしまいそうなのでいらないと思ってます。

どのみち始点の問題でスペシャルジャッジにするなら、(用語を忘れてしまったのですが)
辺上\凸多角形の頂点の点なら
`0 x y`
凸多角形の頂点の点なら
`1 x y`
のように反時計回りとかで出力させるのが良いかなと思っています(重複はそのぶんだけ出力させたほうが素直？始点が重複の途中から始まるとスペシャルジャッジが少し大変そう)

**Comment by SSRS-cp** [comment]
復元は簡単なのに対して要らないときにも余計なデータをもたせるような構造になってしまいというのは、他の問題 (最短路など) にも言えませんか？

**Comment by KentaroMatsushita** [comment]
noshi さんの意見を全面的に借りるんですが、「復元パートがバクの元(verify する価値があるかどうか)」が焦点だと思っていて、座標があっていれば index はあまり間違えようがない(間違ってても自分でチェックできる)ので不要だと思っています

**Comment by maspypy** [comment]
流れ的に

・入力は座標の重複を許す
・出力は点の座標の列のみ（インデックスなし）

で良さそうな気がします。

あとは、辺上の点などを出すかが難しいなと思っていたのですが、
「2 角形」のときに、辺上の点の並び順（A→B、B→Aのどちらの辺上にあると見なすか）が意味不明だということに気づいて、辺上の点を出力させるのはいまいちではないかと思ってきました。
頂点だけにした方がスッキリすると思ったのですが、どうでしょうか？

**Comment by hos-lyric** [comment]
> ・入力は座標の重複を許す
> ・出力は点の座標の列のみ（インデックスなし）

賛成です．

> 始点

スペシャルジャッジがよさそうですね．決めることはできそうですが canonical っぽいものはなく好みが割れそうなので……

> 辺上の点

とりあえずこの問題では辺上真に内部の点は出力に含めないに一票です．
(→ 1 点なら 1 点，線分なら両端点を好きな順，面積正なら境界となる多角形の頂点を反時計回り，でしょうか)

以前辺上の点の有無に対応してライブラリを作ったつもりが 2 角形で破壊されたという経験があってその手のチェックはあると実際嬉しそうなのですが，需要があれば別の問題として立ててしまっていいように思います．

**Comment by SSRS-cp** [comment]
辺上の点がある出力から辺上の点を消すのは容易ですが逆は自明ではないので、辺上の点を調べるのも verify できるとうれしいです

**Comment by maspypy** [comment]
辺上の点を調べるというのは、
https://atcoder.jp/contests/abc296/tasks/abc296_g
に相当するものがあればよい話ですか？

**Comment by maspypy** [comment]
・入力は座標の重複を許す
・出力は点の座標の列のみ（インデックスなし）

これで、作業者募集としておきます。
