### ISSUE TITLE
[問題案] multipoint evaluation on geometric sequence

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#906]
# 概要
$n$ 次多項式 $f$ および $a, r, m$ が与えられる。
$0\leq i < m$ に対して $f(ar^i)$ を計算せよ。
998244353

# 制約
$n, m \leq 2^{19}$
$0\leq a < 998244353$
$0\leq r < 998244353$

# 解法
https://noshi91.github.io/algorithm-encyclopedia/chirp-z-transform#noredirect

畳み込み 1 回やるだけ

# 備考
https://github.com/yosupo06/library-checker-problems/issues/746

の想定解法で使う。上の問題では、多次元インデックスのあれこれや、1 の n 乗根を探す等の余計な要素も多いため、別にこっちも作っておいた方が分かりやすいように思う。

**Comment by hos-lyric** [comment]
$a = 1$ 固定でもいいかもしれません．どちらでもいいです．

$r = 0$ はあっていいと思います．

**Comment by maspypy** [comment]
作業者募集。

**Comment by maspypy** [comment]
作業者やります
