### ISSUE TITLE
[問題案] Count Points in Triangles

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#908]
[概要]
$N$ 個の点 $A_i$ および、 $M$ 個の点 $B_j$ が与えられる。次の $Q$ 個のクエリに答えよ。

`i_0 i_1 i_2`： $\{A_{i_0}, A_{i_1}, A_{i_2}\}$ の凸包に対して、「内部にある $B_j$ の個数」を答える

[制約]
- $N\leq 500$
- $M\leq 500$
- $Q\leq 10^6$
- 座標の範囲は $\pm 10^9$ 

一般の位置などの仮定は何もせず、共線な 3 点がクエリされた場合には 0 を答えることを想定している。内部なので、周上の $B_j$ は数えない。

[解法]
$O(N^2M)$ 前計算のもと、クエリあたり $O(1)$ でやる。
雑に言えば、すべての $(i, j)$ に対して、 $OA_iA_j$ に対する適切な前計算をして、 $A_iA_jA_k = OA_iA_j + OA_jA_k + OA_kA_i$ のようにやればできる。

位置関係による微調整が面倒なので library checker にあると良いと考えた。

用途の例：凸多角形を作るdp https://atcoder.jp/contests/abc202/tasks/abc202_f

**Comment by maspypy** [comment]
作業者募集。

**Comment by NachiaVivias** [comment]
作業します。
