### ISSUE TITLE
[テストケース案]Factorizeについて

### ISSUE THREAD

**Issue by shakayami** [yosupo06/library-checker-problems#909]
https://judge.yosupo.jp/submission/114334
みたいなコードが、4295098369を100個並べたテストケースによって撃墜されるみたいです
https://judge.yosupo.jp/submission/114352
みたいなコードにすれば通るらしいです。

**Comment by NachiaVivias** [comment]
```py
46            elif d==N:
47                res[N]+=1
48                return res
```

114334 の提出ではこの部分が間違っているようです。素因数の $\rho$ と $N$ の $\rho$ が同時に周期に入ったときに $\gcd(x-y,N)=\gcd(0,N)=N$ になります。

この原因だと与える合成数が大きいほど間違える期待が減りますが、 $10000$ まで試し割りする処理が入っているのであまりに小さいケースではかえって間違えず、ケースを入れる場合は値の大きさなどに気を付ける必要がありそうです。

もしかすると $4295098369$ 限定で $\rho$ の形がよいのかもしれません。

**Comment by maspypy** [comment]
4295098369 を 100 個並べたケースを足します

**Comment by maspypy** [comment]
done
