### ISSUE TITLE
Convolution の問題文が数列の存在しない項を参照している

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#913]
p進大好きbot さんによって報告された問題点です。（ https://twitter.com/non_archimedean/status/1607526212091654148 ）

## 問題点

$a_N,a_{N+1},\ldots$ や $b_M,b_{M+1},\ldots$ は特に定義されていませんが、一方でシグマで明らかに参照されているので、正確には問題を定義できていません。

該当する問題
- Convolution  `convolution_mod`
- Convolution (Mod 1,000,000,007)  `convolution_mod_1000000007`
- Convolution (Mod 2^64)  `convolution_mod_2_64`
- Convolution (Large)  `convolution_mod_large`

$\sum_{i,j,i\oplus j=k}$ のように条件を書いているパターンの問題文もありますが、それは暗黙の了解があると考えれば問題ないのかもしれません。（私は詳しくないですが）

**Comment by NachiaVivias** [comment]
## 解決案の例

- https://twitter.com/non_archimedean/status/1607527297015508992
  - a,b は $N+M$ 項以上あることにする。
  - シグマの範囲をいい感じにする。

- 多項式ベースの問題文にする。
  - Multivariate Convolution では、多項式があってその係数が入出力されるということになっています。
- 条件を書くシグマを使うことにする。

**Comment by maspypy** [comment]
$c_k = \sum_{i+j=k} a_ib_j$ でなおします。

**Comment by maspypy** [comment]
done
