### ISSUE TITLE
[問題案] Enumerate Quotients

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#922]
問題名: Enumerate Quotients

## 問題概要
$x=1,2,\dots,N$ に対する $f(x)=\lfloor\frac{N}{x}\rfloor$ は $O(\sqrt{N})$ 個の値が同じ区間に分かれる。この区間の情報を出力

## 入力
```
N
```

## 出力
$M$ 個の区間に分かれ、$i$ 番目の区間では $x=L_i, L_i+1, \dots, R_i$ に対し $f(x)=Q_i$ となるとき、
```
M
Q_1 L_1 R_1
Q_2 L_2 R_2
...
Q_M L_M R_M
```
と出力。ただし $x$ が小さい順に出力する。

例えば、$N=10$ なら
```
5
10 1 1
5 2 2
3 3 3
2 4 5
1 6 10
```
と出力する。

## 制約
$1 \leq N \leq 10^{12}$

## メモ
出力の個数がやや多くなるのが不安

出力方式は他にも考えられる。自分のライブラリの形式を書いたが、半開区間にして M+1 個の境界だけ出力なども考えられる
```
5
1 2 3 4 6 11
10 5 3 2 1
```

**Comment by hos-lyric** [comment]
個人的には，数論関数系なので区間は $[L, R)$ より $(L, R]$ の表示の方が好みです．

```
5
0 1 10
1 2 5
2 3 3
3 5 2
5 10 1
```
と
```
5
0 1 2 3 5 10
10 5 3 2 1
```
に 1 票ずつ．他の人の意見も聞きたいです．

**Comment by maspypy** [comment]
どちらにしたい気持ちも分かる状態…。間をとって、(商, 個数) を出すとかは微妙でしょうか。

**Comment by maspypy** [comment]
これ、結構、ちゃんと速度差を見たい人が居る問題だと思うんですよね。
で、現状のどの方針でも、商列挙よりも出力がボトルネックになってしまうのがいまいちな感じはします。

すべての商に対する何かを出力させると良いと思った（https://judge.yosupo.jp/problem/enumerate_triangles の形式）のですが、何か良いものはあるでしょうか。

良いものがあれば、制約も、$10^15$ くらいまでは上げて良い気がしています。マルチテストケースでもよいかも。

**Comment by maspypy** [comment]
bit 演算とかガチャガチャしたものの総和。とかな気がしますが。

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/issues/149

**Comment by hos-lyric** [comment]
いろいろ考えると

```
5
1 2 3 5 10
```

でいいんじゃないかという気になってきました．後々追加されるかもしれない数論関数累積和系にもこのフォーマットが使えそう．

これをハッシュ化したものもありですね． #149

**Comment by maspypy** [comment]
5
1 2 3 5 10

これでお願いします。
