### ISSUE TITLE
[問題案] intersection of F_2 vector spaces

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#923]
[問題概要]
xor に関する F_2 ベクトル空間の共通部分の基底を一組出力せよ。

T テストケース

入出力形式：
$n$ $u_0$ $\ldots$ $u_{n-1}$
$m$ $v_0$ $\ldots$ $v_{m-1}$

入出力ともに基底

[制約]
- $T\leq 10^5$ （入出力が大きくなるので、要調整）
- $0\leq n, m \leq 30$
- $0\leq u_i, v_i < 2^{30}$ かつ線形独立

**Comment by maspypy** [comment]
作業者募集です。

**Comment by koba-e964** [comment]
これやります

**Comment by koba-e964** [comment]
着手してから気づいたのですが、意外に共通部分の計算が難しいです。何か資料などありましたら提示していただけるとありがたいです 🙇‍♀️

**Comment by yosupo06** [comment]
問題タイトルのF_2を(他の問題に合わせて)LaTeX記法にした方がいいかも
