### ISSUE TITLE
[問題案] mod p equation

### ISSUE THREAD

**Issue by koba-e964** [yosupo06/library-checker-problems#924]
Problem name: mod p equation
Problem ID: mod_p_equation

## Problem

$a_nx^n+\cdots+a_1x+a_0=0 \pmod{998244353}$ を満たす整数 $0\le x<998244353$ の個数を求めよ。

##  Constraint

- $1 \le N \le 10^5$
- $0 \le a_0,a_1,\ldots,a_n<998244353$
- $a_n\ne 0$

## Solution / Reference
入力された多項式を f と置く。Cantor-Zassenhaus による mod p の因数分解を特殊化して、g := gcd(f, x^p-x) を計算することで1次の因数だけ取得することができる。個数であれば deg(g) が答えで計算量は $O(n \log n (\log n + \log p))$。解を全て出力する場合は final splitting が必要で、 $O(n \log^2 n(\log n + \log p))$ と思われる。

- https://twitter.com/hotmanww/status/1619932701531967488 (問題)
- https://twitter.com/kobae964/status/1619937565616001031 (解法本体)
- https://twitter.com/hotmanww/status/1619939661148987394 (half GCD で gcd が $O(N \log^2 N)$ 時間)

## Input

```
N
a_0 ... a_n
```

## Output

```
Z
```

Z は解の個数

## Note / Disucussion

- 出力させるものを `個数` にするか `全ての解` にするか?

**Comment by SSRS-cp** [comment]
解の個数を出力するのと解を出力するので計算量・実装量がかなり異なるのであれば、両方の問題を作ってしまうことを提案します

**Comment by maspypy** [comment]
解の個数は pow して gcd とるだけですよね。解が求まるのにわざわざ個数だけ聞くものを別に置くほどのものではないという印象があります。

解を求めるのも https://github.com/yosupo06/library-checker-problems/issues/94 とアルゴリズムがほとんど同じだと思っていますが、因数分解せよというのと求解せよというのはどちらも独立に重要な問題設定だと思うので、これはあってよいと思っています。

**Comment by maspypy** [comment]
（個数を求めよ、を別に作るという強い要望があればまた改めて相談ということで）

とりあえずは「解を全て求めよ」を作るということでお願いしたいと思います。

**Comment by maspypy** [comment]
https://en.wikipedia.org/wiki/Berlekamp%E2%80%93Rabin_algorithm
あまり真面目に探していなかったが，もうちょっと近い文献があった．
実際にやっていることは「Cantor-Zassenhaus による mod p の因数分解を特殊化」とほとんど同じ．
考えたのと同じ計算量が書いてあって安心．
