### ISSUE TITLE
[Problem proposal] Triangle detection

### ISSUE THREAD

**Issue by koba-e964** [yosupo06/library-checker-problems#926]
Problem name: Triangle detection
Problem ID: triangle_detection

## Problem

単純無向グラフが与えられる
3 頂点であってどの組も互いに結ばれているものを一つ見つけるか、ないことを報告せよ

類題: https://github.com/yosupo06/library-checker-problems/issues/442

##  Constraint

- $1 \leq N, M \leq 10^5$
- 与えられるグラフは単純

## Solution / Reference

https://www.researchgate.net/publication/220618165_Finding_a_Minimum_Circuit_in_a_Graph の方法で $O(M^{3/2})$

## (Optional) Input

```
N M
u_0 v_0
: 
u_{M-1}, v_{M-1}
```

## (Optional) Output

```
Yes
a b c
```

or
```
No
```

**Comment by yosupo06** [comment]
https://judge.yosupo.jp/problem/enumerate_triangles ?

検出だけならもっといい計算量あるんでしょうか

**Comment by koba-e964** [comment]
数えるのも $O^*(M^3/2)$ でできたんですね…。
close します
