### ISSUE TITLE
Matrix Product のジャッジがおかしい

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#928]
以下、おかしいと考えた根拠を並べます。

・昔 AC した提出がリジャッジで落ちる（WA, RE）
https://judge.yosupo.jp/submission/100612
解法にランダム要素はなく、テストケース追加類もない問題だと思うんですが、何かジャッジ環境の変化などありましたか？

・なるべくシンプルに愚直解っぽいものを書いてみたら WA が出ている
https://judge.yosupo.jp/submission/127025

・Fastest から最速実装を拾ってきて提出すると WA, RE が出る
https://judge.yosupo.jp/submission/127029

----
library checker の最新を git clone して手元で試したところ、正常なテストケースを作ってくれているように見えるんですが。

**Comment by yosupo06** [comment]
ありがとうございます　ref #929
