### ISSUE TITLE
[テストケース案] Factorize 半素数ケースについて

### ISSUE THREAD

**Issue by KoeTsukakoshi** [yosupo06/library-checker-problems#930]
[要約]半素数ケースの素数の大きさを若干離したケースが欲しい

ケースに対し作為的な実装で実行時間を大幅に短縮できる恐れがあります
ケース追加で回避可能です

https://judge.yosupo.jp/submission/126779
(fastest防止のため完全平方でバグらせています、big系ケースが速いのが本質です)
フェルマーの平方差法とρ法を組み合わせると大幅に短縮されます

一般に合成数(半素数)の分布は
１、桁の大きく離れた半素数 > ２、1,2桁違いの半素数 > ３、非常に近い半素数
であり、フェルマーの平方差法に強くRSA合成数の基準となる
２のケースがあってもよいのかなと思います。

[テストケース案]
pを10^8 ～10^9　からランダムに選ぶ
q をpqが10^18を超えない最大の素数、またはそれに近い素数を選ぶ(数値設定はお任せします)

1:1 ~ 1:100 の因子比の合成数となり
ρ法には平均で数倍弱くなりますが
より包括的な平方差法であるLehman法でも計算量はO(n^1/3)なので
平方差法でのズルはできなくなると思います

github未経験なので、
何かおかしな点があったらご指摘ください

**Comment by maspypy** [comment]
作業者募集中です。

**Comment by lpha-z** [comment]
contributions-welcome とのことでしたので、実装し、#1107 にプルリクエストを投げました。
上記[KoeTsukakoshi](https://github.com/KoeTsukakoshi)さんのコメントを見ながらの方が議論しやすいと思いますので、こちらで詳細のコメントを行います。

テストケースの追加により“ずる”ができなくなっていることの確認、およびロー法に必要以上に弱くなっていないかの検証を行いました。

## 実行結果

|テストケース名|correct|rho_with_difference_of_square|コメント|
|:-|-:|-:|:-|
|big2_00|354ms|2ms|ずる可能|
|big2_01|357ms|2ms|ずる可能|
|big2_02|366ms|2ms|ずる可能|
|big2_worse_00|857ms|2ms|ずる可能。correctが使っている特定の疑似乱数の最遅ケース|
|big_semiprime_gen_00|348ms|365ms|【今回追加】ずるは困難|
|big_semiprime_gen_01|341ms|367ms|【今回追加】ずるは困難|
|big_semiprime_random_00|271ms|315ms|【今回追加】ずるは困難|
|big_semiprime_random_01|303ms|315ms|【今回追加】ずるは困難|
|pow2_02|47ms|4ms|平方数のテストであり、ずる可能|
|その他のテストケースの最遅|33ms|33ms|max_00やcarmichael_00が難しいようだ|

【今回追加】と記したテストケースがなければ rho_with_difference_of_square が correct に対して10倍以上速いです。
今回のテストケースにより最遅ケースは rho_with_difference_of_square は correct と同等の360ms程度となります（big2_worse_00は使う疑似乱数を変えれば遅くないので除外）。

## ロー法に弱いテストケースとなっていないか

今回のテストケースでは、因子比を1:1～1:100としました。
因子比が1:1の時、二つの素因数はどちらも10^9程度です。
因子比が1:100の時、小さい方の素因数は10^8程度、大きい方の素因数は10^10程度です。
後者がロー法に最も弱いケースですが、小さい方の素因数のサイズは1/10程度にしかなっておらず、ロー法に対して1.78倍（10の4乗根）程度弱くなるにとどまります。

また、semiprime_genの方は、テスト結果を見る限りではロー法に対しての強さはほとんど変わっていないようです。
これは、semiprime_genは小さい方の素因数を一様乱数で生成したため、因子比が1:1に近いケースが多く生成されていることが原因だと思います。

semiprime_randomは、素数を生成して掛け合わせるのではなく、ランダムに生成した自然数が半素数であればテストケースとする、という単純な実装です。
素数を生成して掛け合わせる方法はなんらかのバイアスがかかるかな、と思ってこういうテストケースも追加してみました。
ロー法に対しては少しだけ弱くなっているようです。

----

コメント等指摘歓迎です。よろしくお願いいたします。
