### ISSUE TITLE
[問題案] wildcard pattern matching

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#931]
Problem name: wildcard pattern matching

## Problem

文字列 $S, T$ がある。英小文字 / '?'

各 $i\leq |S|-|T|$ に対して、$S[i:i+|T|]$ が $T$ にマッチするかを判定し、結果を 01 列で出力せよ。

S = `?a?aa`
T = `ba?`
ANS = `101`

##  制約

- $1 \leq |T|\leq |S| < 2^{19}$
- 英小文字 or ?

## 資料
https://qiita.com/MatsuTaku/items/cd5581fab97d7e74a7b3

## 数列の場合の解法
各文字を乱択した値に置き換えてから例の計算をすれば、低次の多項式なので失敗確率 O(1/mod) にできる。
あるいは、mod を数個使えば決定的にできる。

**Comment by maspypy** [comment]
作業者募集。

**Comment by maspypy** [comment]
もめどころ：文字列 or 数列

**Comment by NachiaVivias** [comment]
> もめどころ：文字列 or 数列

admin で議論の場を設けた結果、文字列で決着したので、それで作業者募集にします。

以下、そこで出た意見の抜粋です。

・英小文字でなくても解ける場合は一般数列にしたほうが応用しやすそう
・文字列用途が多そう
・文字列の場合専用の特殊化がある
・数列ライブラリも、文字列で通るならまずバグってないだろう
・複数の mod を使う場合も結果の AND とればできる
・文字列系は `array<26>` を用いる実装が考えられて、制約が 10^9 だと verify できない
・過去問との整合性
