### ISSUE TITLE
[テストケース案] Sort Points by Argument

### ISSUE THREAD

**Issue by Ricky-pon** [yosupo06/library-checker-problems#932]
同じ点を大量に含むテストケースが欲しいです。

`cross_product(a, b) > 0` を `cross_product(a, b) >= 0` のように書いているコードを落とす（RE にする）ことができます。

例：https://judge.yosupo.jp/submission/87649

**Comment by maspypy** [comment]
作業者募集中です。

**Comment by NachiaVivias** [comment]
作業します。
