### ISSUE TITLE
[テストケース案] Vertex Set Path Composite

### ISSUE THREAD

**Issue by sakikuroe** [yosupo06/library-checker-problems#936]
[Vertex Set Path Composite](https://judge.yosupo.jp/problem/vertex_set_path_composite) に、[Vertex Add Path Sum](https://judge.yosupo.jp/problem/vertex_add_path_sum) のテストケースである almost_line_hoge や line_hoge に相当するテストケースがほしいです。
現状、経路の圧縮 (?) パートがうまく機能していないコードで、Vertex Set Path Composite が通ってしまうと思います。

Vertex Set Path Composite が通ったコードを、少し書き換えて Vertex Add Path Sum に投げると almost_line や line で[落ちました](https://judge.yosupo.jp/submission/130524)。また、ABC294-G でも[落ちました](https://atcoder.jp/contests/abc294/submissions/39887275) (こちらはどういうテストケースか確認はできないのですが......)。

例えば、次のようなケースを手元で作成してみると、N = 10000 くらいで落ちます。
```
N N
1 0
1 1
⋮
1 N-1
0 1
1 2
⋮
N-2 N-1
1 0 0 0
1 0 1 0
1 0 2 0
⋮
1 0 N-1 0
```

**Comment by yosupo06** [comment]
#190

**Comment by maspypy** [comment]
作業者募集中です。
