### ISSUE TITLE
[問題案] Addition of Big Integers

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#941]
## 問題概要
整数 A, B が与えられるので、A+B を出力

## 制約
$-10^{500000} \leq A, B \leq 10^{500000}$

## メモ
多倍長整数の問題がないので提案 (AOJ にありますが)

減算、乗算、整数除算もあるとよいと思います

**Comment by maspypy** [comment]
四則演算、4 つとも作ってしまってよいと思っています。

除算：割る数は正の数にする。商と余りの 2 つを出力。
他は同じ入出力形式、制約でいけると思います。

**Comment by NachiaVivias** [comment]
入力値に負符号がつく場合がある設定なら、加算と減算を両方実装するのはあまりにも無意味ではないですか？

あとマルチテストケースがよいと思います。（桁数・桁数の差・最上位の繰り上がりの有無の組み合わせのローラーとか、できればやりたいが、今のジャッジだとファイルが多いだけで遅いので）

**Comment by maspypy** [comment]
作業者募集で。

**Comment by maspypy** [comment]
+, ×, ÷ ですね。どれかだけでも助かります。

**Comment by NyaanNyaan** [comment]
÷ の作業をします

**Comment by maspypy** [comment]
和と積の作業をします。

**Comment by maspypy** [comment]
done
