### ISSUE TITLE
Polynomial Composite Set Power Series

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#944]
Problem name: Polynomial Composite Set Power Series

## Problem

次数 $M$ 未満の多項式 $f$ と $N$ 元集合上の集合冪級数 $s$ が与えられたとき、 $f(s)$ を計算する

##  Constraint

- $0 \leq M \leq 10^5$
- $0 \leq N \leq 20$

## Reference

- https://codeforces.com/blog/entry/92183

## Input

$M$ $N$
$[x^0]f$ $[x^1]f$ $\ldots$ $[x^{M-1}]f$
$s_0$ $s_1$ $\ldots$ $s_{2^N-1}$

## Note

Composition of Polynomial and Set Power Series などの名前の方が良いかもしれない。

想定解を作ってあって、テストケースはランダムで足りそうなので、すぐに作業できます。

**Comment by hos-lyric** [comment]
よさそうです．

冪級数の合成の話一般に言えるのですが，「外側が多項式」「内側の定数項が 0」のどっちが自然か (あるいは両方のジャッジを用意するか) というのがちょっと悩みどころですね．
「内側の定数項が 0」用の問題は「$f_0, \ldots, f_N$ を与えて $\sum_{i=0}^N f_i \frac{s^i}{i!}$ を出力」がいいかなと思っていて，これは本質だけ取り出せているという点で綺麗なのですが，提案されたバージョンのジャッジを用意する方がユーザー側の問題変換が簡単寄りになってよいのかもしれません．

**Comment by noshi91** [comment]
「外側が多項式」のライブラリを「内側の定数項が 0」で verify すると、M と N を間違えたり、内側の定数項の取り扱いを間違えたコードがチェックできないというのが気になります。ただ、頑張るとできるというのと、「外側が多項式」のライブラリは使う場面が無さそうなので設定が綺麗になる方で良いかなという気がしています。

**Comment by SSRS-cp** [comment]
「外側が多項式」でない場合というのはどういうことでしょうか

**Comment by noshi91** [comment]
形式的冪級数 $f$ と、定数項が $0$ の集合冪級数 $s$ に対し $f(s)$ を計算するという事です。

**Comment by SSRS-cp** [comment]
その場合も f を M 次までで切って多項式とみなすことにより「外側が多項式」の場合に帰着されませんか？(勘違いしていたらすみません)

**Comment by maspypy** [comment]
「集合～」であることはその議論には関係ないので省くと、例えば f(1+x) の M 次までを計算ことは f の M 次までを与えても無理で、その以前に一般の形式的べき級数 f に対してそのような操作は定義されないということです。

**Comment by SSRS-cp** [comment]
外が形式的冪級数で内側の定数項が 0 の場合というつもりでした

**Comment by noshi91** [comment]
hos-lyric さんの指摘の通り、 $\displaystyle \sum _ {i = 0} ^ {N} f _ i \frac{s ^ i}{i!}$ は $i!$ が可逆でない場合にも計算できるので、この定式化だと内側の定数項が 0 であることが重要になってきます。そして内側の定数項が 0 であるとき、 $f$ は (SSRS-cp さんの指摘の通り実装上は多項式と同じですが) 形式的冪級数と考える方が理論的に綺麗なので、そのように表現しています。例えば $\mathrm{sqrt}(1 + s)$ を計算すると言ったとき、少なくとも式変形の段階では $\mathrm{sqrt}(1 + x)$ を $N$ 次で切り捨てて...などは考えないです。

**Comment by maspypy** [comment]
問題はよいと思います。

set power series という名前がどのくらい標準的なのかがよく分からないです。
power series ってべき乗を並べているから power だと思っていたのであまり良い名前じゃないような気もするのだが。

**Comment by noshi91** [comment]
競プロ文脈だと Elegia (EntropyIncreaser) が先駆者という印象があり、彼が set power series と呼ぶならそうなのだろうくらいに思っています。
既存の言葉だけでやるなら evaluation of polynomials on the subset convolution ring とか？ subset convolution の環に名前が付いてるのか知らないですが

**Comment by maspypy** [comment]
まあそうですね。何か名前がついていないかと少し調べたんですが、特には見つからなかったです。

**Comment by maspypy** [comment]
特に問題なさそうなので、作業待ちにしておきます

**Comment by hos-lyric** [comment]
■ 設定
> 「外側が多項式」のライブラリを「内側の定数項が 0」で verify すると、M と N を間違えたり、内側の定数項の取り扱いを間違えたコードがチェックできないというのが気になります。ただ、頑張るとできるというのと、「外側が多項式」のライブラリは使う場面が無さそうなので設定が綺麗になる方で良いかなという気がしています。

はい，この通りだと思うので，お任せという意見のままです．

> 補足: 例えば sqrt of formal power series https://github.com/yosupo06/library-checker-problems/issues/73 で a_0=1 の制約がないので、こういうのは全体的にできるだけ制約をゆるくする方針だと個人的には思っています

これは個人的には $a_0 = 1$ あったほうがよかったのではないかと思っていて，そういうような気持ちです．

■ 名前
多変数の power series を打ち切ったものなので，あるいは $x$ の集合乗というのを多変数によって定義するという数学書でたまにありそうなやつと解釈できるので，set power series で悪くないような気がします．確かに power と言ったら普通 2 乗以上を考えていそうではありますが……．

中国語「集合幂级数」は vfleaking さんの 2015 OI 論文 (Codeforces のリンク先から辿れます) がきっかけで中国語競プロコミュニティでは十分拡散された状態だと思います (さらにそれに出所があったかはわからないです)．

アカデミア情報はわからないが競プロコミュニティで使われている，というタイプのタイトルは今までなかったかもしれません．個人的には，内輪ネタっぽくなく・適切に内容を表していて・露骨な衝突がなければ，非アカデミア語を使っていっていいのではと思っています．

問題文では $\mathbb{F} _ {998244353} [x_0, x_1, \ldots, x_{N-1}] / (x_0^2, x_1^2, \ldots, x_{N-1}^2)$ での演算といってしまってもいいと思います (タイトルもそれにしてもいいですが長い)．

**Comment by hotman78** [comment]
今更になって申し訳ないのですが、 $s$ の定数項を $0$ としてしまうと $s^{N+1}=0$ が成り立ってしまい問題の性質が大分変化してしまうような気がするのですがどうでしょうか

**Comment by maspypy** [comment]
それは認識された上で準備されているはずです。

**Comment by hotman78** [comment]
議論の内容について勘違いをしていました
申し訳ないです
