### ISSUE TITLE
[問題案] Lyndon Factorization

### ISSUE THREAD

**Issue by maspypy** [yosupo06/library-checker-problems#948]
# 問題
文字列が与えられるので、Lyndon factorization を出力せよ。

input: babaabaa

|b|ab|aab|a|a|

output: 0 1 3 6 7 8

# 制約
- 英小文字
- $|S|\leq 500000$

# 資料
https://en.wikipedia.org/wiki/Lyndon_word
https://cp-algorithms.com/string/lyndon_factorization.html
https://codeforces.com/blog/entry/106725
https://qiita.com/nakashi18/items/66882bd6e0127174267a

**Comment by hos-lyric** [comment]
よさそうです．

より強い情報を聞くこともできそうですが (例：各 prefix について min suffix を聞く)，自然な形の一つとしてこれが準備されていてよいと思います．

**Comment by maspypy** [comment]
作業者募集です。

**Comment by NachiaVivias** [comment]
作業します。
