### ISSUE TITLE
[問題案] Reversion of Formal Power Series

### ISSUE THREAD

**Issue by hotman78** [yosupo06/library-checker-problems#950]
Problem name: Reversion of Formal Power Series
Problem ID: reversion_of_formal_power_series

## Problem

形式的冪級数 $f(x) = \sum_{i=0}^{N-1} a_i x^i \in \mathbb{Q}[[x]]$ が与えられます ($a_0 = 0, a_1 \neq 0$)。
$f^{-1}(x) = \sum_{i=0}^{\infty} b_i x^i$ の先頭 $N$ 項を求めてください。

つまり、

$$
g(f(x))=x
$$

となる $g(x) = \sum_{i=0}^{N-1} b_i x^i \in \mathbb{Q}[[x]]$ を求めてください。係数を $998244353$ で出力してください。

##  Constraint

- $1 \leq N \leq 8000$
- $0 \leq a_i < 998244353$
- $a_0 = 0$
- $a_1  \neq 0$

## Solution / Reference
合成 + ニュートン法

1. http://www.eecs.harvard.edu/~htk/publication/1978-jacm-brent-kung.pdf
2. codeforces のブログ(メンテナンス後追記)

## Input

$N$
$a_0$ $a_1$ $\cdots$ $a_{N - 1}$

##  Output

$b_0$ $b_1$ $\cdots$ $b_{N - 1}$

## Note / Disucussion
想定解に使用する合成のアルゴリズムは $\mathcal{O}(N^{2})$ の行列積を使用した方法(参考文献 1) の方がいいかなと考えています。（速度面において $\mathcal{O}((NlogN)^{3/2})$ に落とすメリットがあまりないため）

**Comment by hos-lyric** [comment]
よさそうです．

問題名は Reversion でだめということはないと思うのですが Compositional Inverse の方がわかりやすいので好みです．アカデミア語についてはどっちもあるっぽいということしか知りません．ソース： Stanley, Enumerative Combinatorics および "compositional inverse" で検索した結果

以下細かい点です：
- $2 \le N$ と書いた方がよさそう
- この言い方だと $g(f(x)) \equiv x \pmod{x^N}$ のことっぽい
- 記法については $f^{-1}(x)$ の他に $f ^ {\langle -1 \rangle} (x)$ や $f(x) ^ {\langle -1 \rangle}$ もある程度一般的という認識ですが，これはどちらでもよいです

**Comment by maspypy** [comment]
作業者募集です。

**Comment by hotman78** [comment]
作業始めました
