### ISSUE TITLE
[問題案] Minimum Spanning Tree

### ISSUE THREAD

**Issue by NachiaVivias** [yosupo06/library-checker-problems#953]
Problem name: Minimum Spanning Tree
Problem ID: minimum_spanning_tree

## Problem

$N$ 頂点 $M$ 辺の連結な重み付き無向グラフが与えられる。

$i$ 番目の辺は  $(a_i, b_i)$ であり、重さは $c_i$ である。

最小全域木を求めよ。

##  Constraint

- $1\leq N$
- $N-1\leq M$ ・連結
- $N,M\leq 5\times 10^5$
- 多重辺・ループを含むことも可能

## Input

```
N M
a_0 b_0 c_0
 :
```

## Output

$1$ 行目に、重みの総和。

$2$ 行目に、採用する辺の番号を空白区切りで出力。

## Note / Disucussion

originally posted by [windows-server-2003](https://github.com/windows-server-2003) : https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-630126515

**Comment by maspypy** [comment]
- 辺重みは非負
- 多重辺・ループあり

よいと思います。全域森といえばそれというのがどのくらい一般的なのかとかは、自分は全然知らないです。
https://en.wikipedia.org/wiki/Spanning_tree#Spanning_forests

**Comment by noshi91** [comment]
辺重み負、割とないですか？と思うんですがどうでしょうか (最大化したいときとか)。
最小全域森は使う場面が分かってないです。

**Comment by maspypy** [comment]
ああ、そうかも。（「最小コストで連結にせよ」と最小全域木が同値じゃなくなるなあと考えてしまったが、関係なかったです）

**Comment by NachiaVivias** [comment]
確かに、 MST と比べて全域森を使う場面がほぼなさそう。最大重みの辺で連結にするだけで、本質に響かないので木にしておきます。

**Comment by noshi91** [comment]
https://github.com/yosupo06/library-checker-problems/blob/master/docs/style.md
style.md には負でアルゴリズムが変わり得る場合のみ負になるという方向の記述がありますね。非負で最小全域木が良いでしょうか？

**Comment by shirotsume4** [comment]
多重辺があるので，辺番号を出力させるほうが良いかもしれません

**Comment by NachiaVivias** [comment]
> 多重辺があるので，辺番号を出力させるほうが良いかもしれません

しばらく様子を見て、辺番号出力に変更しようと思います。

 #897 (Static Convex Hull) では index 出力の案が負けているので、仮案としては両端出力としましたが、私は辺番号出力に賛成です。

再考したところ、 897 と事情が違うところもあるので（辺の両端と重みを全部出力してもスペシャルジャッジになる）、統一する必然性はなさそうです。

**Comment by NachiaVivias** [comment]
issue 本文を更新しました。 $(a _ i, b _ i,c _ i)$ を出力なら十分自然なので、たぶん作業者の都合でどちらでもということになります。

**Comment by maspypy** [comment]
↑これで大丈夫です。

$(a_i, b_i)$ 方式だと、多重辺があるときにグラフが決まらなくていまいち。
$(a_i,b_i,c_i)$ または辺番号の列のどちらかであれば大丈夫です。

**Comment by kzrnm** [comment]
作業してみます。
