### ISSUE TITLE
[バグ] Vertex Add Path Sum の long-path-decomposition_killer が範囲外参照している

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#957]
https://github.com/yosupo06/library-checker-problems/blob/master/datastructure/vertex_add_path_sum/gen/long-path-decomposition_killer.cpp#L26
```assert(p < n - 1);``` を入れると落ちる。
長さが 2 ずつ減少していくパスたちの端点を一列につないだケースだが、つなぐための辺が 1 本多くなっている。

**Comment by noshi91** [comment]
#955 こちらにも同じケースを追加する予定なので、これが本当にバグか確認しないと 955 が merge できないという状況です。

**Comment by maspypy** [comment]
> これが本当にバグか
配列外参照している時点で、バグであるという判断で良いのでは

----
頂点が (sqrtn)^2 + 1、辺の個数が (sqrtn)^2 になりますよね。なおしかたはいくつかありそうですが、

- sqrtn = sqrt(N_AND_Q_MAX - 1)
- n = sqrtn * sqrtn + 1

という 2 つをなおせば大丈夫な気がします。

**Comment by noshi91** [comment]
一応、勘違いしてないかもう 1 人に確認して欲しいという意図でした。
作成されたケースの意図を推察すると、longest path decomposition がそれぞれのパスになるようにしたいので、while(len > 1) とするのが最も綺麗かなと思います。それで良いでしょうか？

**Comment by maspypy** [comment]
それでも大丈夫そうです。修正も少なく済みますね。

**Comment by shirotsume4** [comment]
今見ました．noshiさんの修正案に従って直しておきます．

**Comment by noshi91** [comment]
while (len > 1) にすると範囲外参照が消えるだけでケースは同じになると思っていたんですが、hash が変わっている？
