### ISSUE TITLE
[問題案] Stirling Number of the First Kind (Fixed k)

### ISSUE THREAD

**Issue by kaichou243** [yosupo06/library-checker-problems#962]
問題名: Stirling Number of the First Kind (Fixed k)

##  問題文
第1種スターリング数 $s(n,k)$ を以下を満たす係数として定義します：
$x(x-1) \cdots (x-(n-1))=\displaystyle\sum_{k=0}^{n} s(n,k)x^k.$
整数 $N,K$ が与えられます。 $K \leq n \leq N$ に対して $s(n,K) \bmod 998244353$ を求めてください。
##  制約

- $0 \leq K \leq  N \leq 200000$

## Solution / Reference

- $(-1)^{n+K} \times n! \times [x^n] \frac{(- \log(1-x))^K}{K!}$

## Note / Disucussion

- 制約は適当です

**Comment by maspypy** [comment]
「Fixed N」と同じく、$N\leq 500000$ でよいと思います。
