### ISSUE TITLE
[問題案] counting $C _ 4$'s

### ISSUE THREAD

**Issue by noshi91** [yosupo06/library-checker-problems#973]
Problem name: counting $C _ 4$'s

## Problem

無向グラフが与えられる。
部分グラフであって $C _ 4$ と同型なものの個数を数える

##  Constraint

- $M \leq 3 \times 10 ^ 5$
- ループあり多重辺あり？

## (Optional) Note / Disucussion

- #442 が $M = 10 ^ 5$ なんですが fastest が 11ms なので、制約を増やしています
- アルゴリズムの都合上 #442 のように hash を定義しても動作するんですが、列挙できるわけではないので、個数数えるだけでも良さそう
- 有向とか辺の多重度が与えられるとか色々ありそう

**Comment by KentaroMatsushita** [comment]
ただ数えるだけだとどこかの+1と-1が相殺して悲しいことになる可能性がありそう？（ケースがある程度あれば早々ならないと思いますが）

応用とか考えると各頂点/辺を含むとかでもいいのかなと思ってます（辺の多重度でも精度は上がりそうですが、殆どが無向グラフの場合な気がしていてあまり嬉しくなさそうという印象）

**Comment by noshi91** [comment]
- 各頂点と各辺について、それを含む $C _ 4$ の個数を数える

**Comment by maspypy** [comment]
多重辺ありだと、最大ケースで $(M/4)^4$ ですか。

選択肢は

- $2^{64}$ 以上の整数を出力
- 適当な mod で出力
- 多重辺なし
- $M\leq 200000$

など？

**Comment by noshi91** [comment]
mod P で verify には足りそう、 $M$ は様子見ながらさらに大きくすることも考えている、ということで mod P にしたいと考えています。

**Comment by maspypy** [comment]
> 各頂点と各辺について、それを含む $C_4$ の個数を数える

これでお願いします。

**Comment by NachiaVivias** [comment]
作業中です

**Comment by maspypy** [comment]
一応ここにメモ

問題案は頂点、辺を通るカウントだったが、頂点ごとの場合や総数の計算は辺の場合の足し算割り算で簡単なので、準備していただいた辺カウントバージョンで ok ということにしました
