### ISSUE TITLE
[問題案] f: 高々 d 次の多項式

### ISSUE THREAD

**Issue by yosupo06** [yosupo06/library-checker-problems#98]
f: 高々 d 次の多項式
f(0), ..., f(d) と a が与えられるので \sum_{0<=i<n} a^i f(i) を求めるやつ

_Originally posted by @hos-lyric in https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-530946631_

**Comment by yosupo06** [comment]
そもそもこの式は何？状態

多項式補完すればO(d log^2 d + n)ぐらいにはなりそうだけど

**Comment by hos-lyric** [comment]
動機：2^0 0^3 + 2^1 1^3 + 2^2 2^3 + ... + 2^(n-1) (n-1)^3 みたいなのを O(log n) で求めるやつ，毎回手計算するのつらくないですか
計算量：O(d + log n)
問題例：https://community.topcoder.com/stat?c=problem_statement&pm=13440&rd=16188
文献：https://min-25.hatenablog.com/entry/2015/04/24/031413

f の与え方として多項式 (or 単項式) を陽に与えるというのもありだと思うけど，文献のようにやると f(0), ..., f(d) を経由するのでそういう形式もありなのかなぁという気持ちです

**Comment by yosupo06** [comment]
もしかしてf(x)を与えるかf(0), f(1), ..., f(d)を与えるかで計算量が変わりますか？

**Comment by yosupo06** [comment]
多項式を与えたほうが問題設定としてはきれいなように思えるんですが、計算量が変わるなら悩ましい

**Comment by hos-lyric** [comment]
複数の値で評価…… multipoint... なので O(d (log d)^2 + log n) になっちゃいますね
(O(d log d + log n) とかにはなるのかもしれない，わかりません)

単項式で与えるのが問題も綺麗で余計な計算量も log d でちょうどいい，かなぁ

**Comment by yosupo06** [comment]
x=0,1,2,...,(d-1)のmultipoint evaluationが実は高速に出来るみたいな展開がある気がしていて、とりあえずこれを考えてみたいと思います

**Comment by yosupo06** [comment]
実は0^k, 1^k, 2^k, ..., n^kの列挙はO(N log MOD / log N)ということがわかりました(篩をして素数だけやる)

**Comment by hos-lyric** [comment]
問題名: Polynomial Geometric Sum (???)

# 問題概要
\sum_{0<=i<n} r^i i^d を mod 998244353 で求めよ

## 入力

```
d r n
```

## 出力

```
answer
```

## 制約
- 0 <= d <= 10^7
- 0 <= r < 998244353
- 0 <= n <= 10^18

----

O(d log log d + log n) くらい
とりあえずこれでどうでしょう，問題設定が綺麗という条件は満たした
等比級数の和を求めるライブラリをチェックしたい人 https://github.com/yosupo06/library-checker-problems/issues/3#issuecomment-589545010 も満足
最初のやつを f(0), ..., f(d) の値から求めるライブラリを作った人も，これがあればチェックできるだろうという希望的推測

**Comment by hos-lyric** [comment]
タイトル命名が何もわかりません
geometric progression は言う，geometric series も言う，geometric sum は言うのか？
適当に polynomial と付けたが polynomial sum ではないし polynomial geometric って何だよだしそもそも monomial だし

r^i i^d みたいな数列に名前ついてないのかな
CodeChef は quasi-polynomial と言っているがそれは違う用語
general geometric series も違うらしい

**Comment by yosupo06** [comment]
https://en.wikipedia.org/wiki/Arithmetico%E2%80%93geometric_sequence d=1なら見つけた

**Comment by hos-lyric** [comment]
The denomination may also be applied to different objects ... のところに火種を感じる

無限和の方は https://mathworld.wolfram.com/Polylogarithm.html の特殊な場合ではあるんですけどこれじゃない感 (あと "Polylogarithm" の名は情報科学と相容れなさすぎる)

**Comment by yosupo06** [comment]
あんまりいい名前なさそうなんで、\sum_{0<=i<n} r^i i^d をタイトルにすればいいんじゃないかなと思います(暴力的ソリューション)

**Comment by yosupo06** [comment]
IDは記号とか入れると様々な不具合が発生しそうなんで、sum_of_ exponentiation_geometric とか(Data Structureの問題とかもどうしようもなくてクエリ書き下してるんで、似たようなものと思えば)

**Comment by hos-lyric** [comment]
exponentiation が指数関数のこととすると実は geometric と同じものを指していた！
適切な「似たようなもの」を思いついたら投げることにします
