### ISSUE TITLE
[問題案] 下降階乗冪の形に直したときの係数

### ISSUE THREAD

**Issue by Forestedf** [yosupo06/library-checker-problems#986]
## Problem

多項式 $\displaystyle f(x) = \sum_{i=0}^{N-1} a_i x^i$ が与えられる。

$\displaystyle f(x) = \sum_{i=0}^{N-1} b_i x^{\underline{i}}$ を満たす $b_0, b_1, \ldots, b_{N-1}$ を mod 998244353 で出力。

##  Constraint

- $\displaystyle 1 \leq N \leq 2^{17}$

## Solution / Reference

- https://atcoder.jp/contests/abc272/editorial/5013

Multipoint Evaluation と畳み込みで $O(N \log^2(N))$ 時間。

## (Optional) Note / Disucussion

- 適切なタイトルは分かりませんでした
- 制約は Multipoint Evaluation に合わせました

**Comment by noshi91** [comment]
https://noshi91.hatenablog.com/entry/2023/05/01/022946
より一般化して Newton 基底への変換が $O(N (\log(N) ) ^ 2)$ で計算できます。
下降階乗冪の方が使用頻度は高そうなのでどちらで準備しても良さそう？

**Comment by Forestedf** [comment]
オーダーが変わらないので広い問題の方で準備した方が良い気がしてきました。ありがとうございます。

------

## Problem

多項式 $\displaystyle f(x) = \sum_{i=0}^{N-1} a_i x^i$ と $p_0, p_1, \ldots, p_{N-2}$ が与えられる。

$\displaystyle f(x) = \sum_{i=0}^{N-1} b_i \prod_{j=0}^{i-1} (x - p_j)$ を満たす $b_0, b_1, \ldots, b_{N-1}$ を mod 998244353 で出力。

##  Constraint

- $1 \leq N \leq 2^{17}$

------

- $N = 1$ を含めるべきでしょうか
- 問題名は Conversion from Monomial Basis to Newton Basis でしょうか（用語の使い方に自信がないです）

**Comment by noshi91** [comment]
- コーナーケースは、自然に定義される分は入れるというのが最近の大まかな方針になっています。何なら $N = 0$ も入れて良いと思います。
- 問題名はそれで良いと思います。Bostan, A., & Schost, É. (2005). Polynomial evaluation and interpolation on special sets of points. Journal of Complexity, 21(4), 420-446. でその用例を確認しました。

**Comment by Forestedf** [comment]
想定解が用意できたので、作業に挑戦しようと思います
