### ISSUE TITLE
[問題案] Rectangle Add Point Get

### ISSUE THREAD

**Issue by SSRS-cp** [yosupo06/library-checker-problems#994]
問題名: Rectangle Add Point Get

## 問題概要

$2$ 次元平面上に重み付きの長方形が $N$ 個ある。$i$ 番目は $[l _ i, r _ i) \times [d _ i, u _ i)$ で重み $w_i$ である。$Q$ クエリ処理せよ。

``0 l r d u w``: 位置 $[l,r) \times [d,u)$、重み $w$ の長方形を追加
``1 x y``: 点 $(x,y)$ を含む長方形の重みの総和を答える

##  制約

- $1 \leq N, Q \leq 100000$
- $0 \leq l < r \leq 10^9$
- $0 \leq d < u \leq 10^9$
- $0 \leq w \leq 10^9$
- $0 \leq x, y < 10^9$

## 解法
2D 双対セグ木/BIT

**Comment by maspypy** [comment]
作業者募集。

**Comment by maspypy** [comment]
つくります

**Comment by maspypy** [comment]
https://github.com/yosupo06/library-checker-problems/pull/1072
