### ISSUE TITLE
[テストケース案] Discrete Logarithm

### ISSUE THREAD

**Issue by suisen-cp** [yosupo06/library-checker-problems#999]
出力を見ると small や even_mod_impossible を除いて解無しのものが 9 割程度 (645/711) を占めていることが分かったので、ケース追加を提案します。

具体的なコーナーケース等を発見した訳ではありませんが、とりあえず解が存在するケースを増やすだけでも嬉しそうだと思いました。

ケース案:
- 全て解が存在するようなケース
- 素数 mod
- Pohlig Hellman に不利なケース (Xの位数が小さな素因数を持たないケース？あまりちゃんと理解してません)

**Comment by maspypy** [comment]
3 つめ、euler_phi(mod) があんまり素因数分解できないとかだと思います。
いわゆる安全素数でいいかなと思っています。

**Comment by NachiaVivias** [comment]
テストケースが追加されました。
* 追加ケースは `max_random_yes` , `max_random_yes_prime` , `random_prime` で、 M はすべて 8x10^8 以上
* `max_random_yes`, `max_random_yes_prime` はすべて解あり
* `random_prime`, `max_random_yes_prime` の M はすべて素数
* `max_random_yes_prime_01.in`, `random_prime_01.in` の M はすべて、いわゆる安全素数
